/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import iuran.IPSP;
import iuran.Iuran;
import java.sql.SQLException;
import java.text.ParseException;
import javax.swing.JOptionPane;
import kasir.Control;
import org.openide.util.Exceptions;
import pelajar.Profil;
import sak.KasirException;

/**
 *
 * @author Master
 */
public class InputTransactionIPSP extends javax.swing.JFrame {
    private IPSP ipsp;
    private IPSP ipspFromDB;
    private IPSP ipspStoreToDB;
    private IPSP ipspCurrent;
    private float minIpsp;
    private float maxIpsp;
    public float ipspTunaiAmount;
    public float ipspBeasiswaAmount;
    public float ipspBeasiswaCostAmount;
    private InputTransactionFrameSeparated itfs;
    private Profil profil;
    /**
     * Creates new form InputTransactionIPSP
     */
    public InputTransactionIPSP(Profil profil, InputTransactionFrameSeparated itfs) {
        try {
            this.ipsp = Control.selectIuran(Iuran.Tipe.IPSP, IPSP.noIndukColName, false, profil.noInduk);
            minIpsp = 0F;
            maxIpsp = this.ipsp.amount - this.ipsp.totalInstallment;
            ipspFromDB = new IPSP();
            ipspFromDB = this.ipsp;
            ipspStoreToDB = this.ipsp;
            ipspCurrent = this.ipsp;
            this.itfs = itfs;
            this.profil = profil;
        } catch (SQLException ex) {
            Exceptions.printStackTrace(ex);
            JOptionPane.showMessageDialog(rootPane, "IPSP Belum Di Setting!\r\n".concat(ex.toString()));
            this.dispose();
        } catch (KasirException ex) {
            Exceptions.printStackTrace(ex);
            JOptionPane.showMessageDialog(rootPane, "IPSP Belum Di Setting!\r\n".concat(ex.toString()));
            this.dispose();
        }
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelIPSP = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldIPSPAmount = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldIPSPNote = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextFieldIPSPIuranAmount = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jTextFieldIPSPSisaAmount = new javax.swing.JTextField();
        jButtonIPSPOK = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldIPSPTunai = new javax.swing.JTextField();
        jTextFieldIPSPBeasiswa = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldIPSPBeasiswaCost = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(480, 500));

        jPanelIPSP.setMinimumSize(new java.awt.Dimension(440, 480));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText(org.openide.util.NbBundle.getMessage(InputTransactionIPSP.class, "InputTransactionIPSP.jLabel1.text")); // NOI18N

        jLabel3.setText(org.openide.util.NbBundle.getMessage(InputTransactionIPSP.class, "InputTransactionIPSP.jLabel3.text")); // NOI18N

        jTextFieldIPSPAmount.setText(org.openide.util.NbBundle.getMessage(InputTransactionIPSP.class, "InputTransactionIPSP.jTextFieldIPSPAmount.text")); // NOI18N
        jTextFieldIPSPAmount.setEnabled(false);
        jTextFieldIPSPAmount.setName(org.openide.util.NbBundle.getMessage(InputTransactionIPSP.class, "InputTransactionIPSP.jTextFieldIPSPAmount.name")); // NOI18N
        jTextFieldIPSPAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIPSPAmountActionPerformed(evt);
            }
        });
        jTextFieldIPSPAmount.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldIPSPAmountFocusLost(evt);
            }
        });
        jTextFieldIPSPAmount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldIPSPAmountKeyTyped(evt);
            }
        });

        jLabel5.setText(org.openide.util.NbBundle.getMessage(InputTransactionIPSP.class, "InputTransactionIPSP.jLabel5.text")); // NOI18N

        jTextFieldIPSPNote.setText(org.openide.util.NbBundle.getMessage(InputTransactionIPSP.class, "InputTransactionIPSP.jTextFieldIPSPNote.text")); // NOI18N

        jLabel13.setText(org.openide.util.NbBundle.getMessage(InputTransactionIPSP.class, "InputTransactionIPSP.jLabel13.text")); // NOI18N

        jTextFieldIPSPIuranAmount.setEditable(false);
        jTextFieldIPSPIuranAmount.setText(String.valueOf(ipsp.amount));
        jTextFieldIPSPIuranAmount.setFocusable(false);
        jTextFieldIPSPIuranAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIPSPIuranAmountActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel17.setText(org.openide.util.NbBundle.getMessage(InputTransactionIPSP.class, "InputTransactionIPSP.jLabel17.text")); // NOI18N

        jTextFieldIPSPSisaAmount.setEditable(false);
        jTextFieldIPSPSisaAmount.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jTextFieldIPSPSisaAmount.setText(String.valueOf(maxIpsp));
        jTextFieldIPSPSisaAmount.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldIPSPSisaAmount.setFocusable(false);
        jTextFieldIPSPSisaAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIPSPSisaAmountActionPerformed(evt);
            }
        });

        jButtonIPSPOK.setText(org.openide.util.NbBundle.getMessage(InputTransactionIPSP.class, "InputTransactionIPSP.jButtonIPSPOK.text")); // NOI18N
        jButtonIPSPOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIPSPOKActionPerformed(evt);
            }
        });

        jLabel4.setText(org.openide.util.NbBundle.getMessage(InputTransactionIPSP.class, "InputTransactionIPSP.jLabel4.text")); // NOI18N

        jTextFieldIPSPTunai.setText(org.openide.util.NbBundle.getMessage(InputTransactionIPSP.class, "InputTransactionIPSP.jTextFieldIPSPTunai.text")); // NOI18N
        jTextFieldIPSPTunai.setName(org.openide.util.NbBundle.getMessage(InputTransactionIPSP.class, "InputTransactionIPSP.jTextFieldIPSPTunai.name")); // NOI18N
        jTextFieldIPSPTunai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIPSPTunaiActionPerformed(evt);
            }
        });
        jTextFieldIPSPTunai.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldIPSPTunaiFocusLost(evt);
            }
        });
        jTextFieldIPSPTunai.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldIPSPTunaiKeyTyped(evt);
            }
        });

        jTextFieldIPSPBeasiswa.setText(org.openide.util.NbBundle.getMessage(InputTransactionIPSP.class, "InputTransactionIPSP.jTextFieldIPSPBeasiswa.text")); // NOI18N
        jTextFieldIPSPBeasiswa.setName(org.openide.util.NbBundle.getMessage(InputTransactionIPSP.class, "InputTransactionIPSP.jTextFieldIPSPBeasiswa.name")); // NOI18N
        jTextFieldIPSPBeasiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIPSPBeasiswaActionPerformed(evt);
            }
        });
        jTextFieldIPSPBeasiswa.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldIPSPBeasiswaFocusLost(evt);
            }
        });
        jTextFieldIPSPBeasiswa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldIPSPBeasiswaKeyTyped(evt);
            }
        });

        jLabel6.setText(org.openide.util.NbBundle.getMessage(InputTransactionIPSP.class, "InputTransactionIPSP.jLabel6.text")); // NOI18N

        jTextFieldIPSPBeasiswaCost.setText(org.openide.util.NbBundle.getMessage(InputTransactionIPSP.class, "InputTransactionIPSP.jTextFieldIPSPBeasiswaCost.text")); // NOI18N
        jTextFieldIPSPBeasiswaCost.setName(org.openide.util.NbBundle.getMessage(InputTransactionIPSP.class, "InputTransactionIPSP.jTextFieldIPSPBeasiswaCost.name")); // NOI18N
        jTextFieldIPSPBeasiswaCost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIPSPBeasiswaCostActionPerformed(evt);
            }
        });
        jTextFieldIPSPBeasiswaCost.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldIPSPBeasiswaCostFocusLost(evt);
            }
        });
        jTextFieldIPSPBeasiswaCost.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldIPSPBeasiswaCostKeyTyped(evt);
            }
        });

        jLabel7.setText(org.openide.util.NbBundle.getMessage(InputTransactionIPSP.class, "InputTransactionIPSP.jLabel7.text")); // NOI18N

        javax.swing.GroupLayout jPanelIPSPLayout = new javax.swing.GroupLayout(jPanelIPSP);
        jPanelIPSP.setLayout(jPanelIPSPLayout);
        jPanelIPSPLayout.setHorizontalGroup(
            jPanelIPSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelIPSPLayout.createSequentialGroup()
                .addGroup(jPanelIPSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelIPSPLayout.createSequentialGroup()
                        .addGroup(jPanelIPSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel13)
                            .addComponent(jLabel5))
                        .addGroup(jPanelIPSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelIPSPLayout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addGroup(jPanelIPSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelIPSPLayout.createSequentialGroup()
                                        .addComponent(jTextFieldIPSPNote, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(jPanelIPSPLayout.createSequentialGroup()
                                        .addGap(156, 156, 156)
                                        .addComponent(jLabel17)
                                        .addGap(12, 12, 12)
                                        .addComponent(jTextFieldIPSPSisaAmount, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE))))
                            .addGroup(jPanelIPSPLayout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(jPanelIPSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldIPSPIuranAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldIPSPAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanelIPSPLayout.createSequentialGroup()
                        .addGroup(jPanelIPSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPanelIPSPLayout.createSequentialGroup()
                                .addGap(163, 163, 163)
                                .addComponent(jButtonIPSPOK))
                            .addGroup(jPanelIPSPLayout.createSequentialGroup()
                                .addGroup(jPanelIPSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addGap(18, 18, 18)
                                .addGroup(jPanelIPSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldIPSPTunai, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                                    .addComponent(jTextFieldIPSPBeasiswa)
                                    .addComponent(jTextFieldIPSPBeasiswaCost))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelIPSPLayout.setVerticalGroup(
            jPanelIPSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelIPSPLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(4, 4, 4)
                .addGroup(jPanelIPSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jTextFieldIPSPIuranAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(jTextFieldIPSPSisaAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelIPSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldIPSPAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelIPSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldIPSPTunai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelIPSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldIPSPBeasiswa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGroup(jPanelIPSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelIPSPLayout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jLabel5))
                    .addGroup(jPanelIPSPLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelIPSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldIPSPBeasiswaCost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(24, 24, 24)
                        .addComponent(jTextFieldIPSPNote, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonIPSPOK)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 490, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(12, Short.MAX_VALUE)
                    .addComponent(jPanelIPSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 313, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanelIPSP, javax.swing.GroupLayout.PREFERRED_SIZE, 291, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldIPSPAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIPSPAmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIPSPAmountActionPerformed

    private void jTextFieldIPSPAmountFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldIPSPAmountFocusLost
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTextFieldIPSPAmountFocusLost

    private void jTextFieldIPSPAmountKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldIPSPAmountKeyTyped
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTextFieldIPSPAmountKeyTyped

    private void jTextFieldIPSPIuranAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIPSPIuranAmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIPSPIuranAmountActionPerformed

    private void jTextFieldIPSPSisaAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIPSPSisaAmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIPSPSisaAmountActionPerformed

    private void jButtonIPSPOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIPSPOKActionPerformed
        // TODO add your handling code here:
        itfs.jTextFieldIPSPAmountSimple.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0"))));

        try {
            itfs.jTextFieldIPSPAmountSimple.setValue(Float.valueOf(jTextFieldIPSPAmount.getText()));
            itfs.jTextFieldIPSPAmountSimple.commitEdit();
        } catch (ParseException ex) {
            Exceptions.printStackTrace(ex);
        }
        itfs.ipspFromDB = this.ipspFromDB;
        itfs.ipspStoreToDB = this.ipspStoreToDB;
        itfs.ipspCurrent = this.ipspCurrent;
//        try {
//            ipsp = Control.selectIuran(Iuran.Tipe.IPSP, IPSP.noIndukColName, false, profil.noInduk);
//            itfs.ipsp = ipsp;
//        } catch (SQLException ex) {
//            //idd = null;
//        } catch (KasirException ex) {
//            //idd = null;
//        }
        this.setVisible(false);
    }//GEN-LAST:event_jButtonIPSPOKActionPerformed

    private void jTextFieldIPSPTunaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIPSPTunaiActionPerformed
        // TODO add your handling code here:
        calculateIPSPAmount();
        
    }//GEN-LAST:event_jTextFieldIPSPTunaiActionPerformed

    private void jTextFieldIPSPTunaiFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldIPSPTunaiFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIPSPTunaiFocusLost

    private void jTextFieldIPSPTunaiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldIPSPTunaiKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIPSPTunaiKeyTyped

    private void jTextFieldIPSPBeasiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIPSPBeasiswaActionPerformed
        // TODO add your handling code here:
        calculateIPSPAmount();
    }//GEN-LAST:event_jTextFieldIPSPBeasiswaActionPerformed

    private void jTextFieldIPSPBeasiswaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldIPSPBeasiswaFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIPSPBeasiswaFocusLost

    private void jTextFieldIPSPBeasiswaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldIPSPBeasiswaKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIPSPBeasiswaKeyTyped

    private void jTextFieldIPSPBeasiswaCostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIPSPBeasiswaCostActionPerformed
        // TODO add your handling code here:
        calculateIPSPAmount();
    }//GEN-LAST:event_jTextFieldIPSPBeasiswaCostActionPerformed

    private void jTextFieldIPSPBeasiswaCostFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldIPSPBeasiswaCostFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIPSPBeasiswaCostFocusLost

    private void jTextFieldIPSPBeasiswaCostKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldIPSPBeasiswaCostKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIPSPBeasiswaCostKeyTyped
    
    private void calculateIPSPAmount(){
        float tunai = Float.valueOf(jTextFieldIPSPTunai.getText());
        float beasiswa = Float.valueOf(jTextFieldIPSPBeasiswa.getText());
        float beasiswaCost = Float.valueOf(jTextFieldIPSPBeasiswaCost.getText());
        ipspTunaiAmount = tunai;
        ipspBeasiswaAmount = beasiswa;
        ipspBeasiswaCostAmount = beasiswaCost;
        jTextFieldIPSPAmount.setText(String.valueOf(tunai+beasiswa+beasiswaCost));
    }
    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonIPSPOK;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanelIPSP;
    public javax.swing.JTextField jTextFieldIPSPAmount;
    public javax.swing.JTextField jTextFieldIPSPBeasiswa;
    public javax.swing.JTextField jTextFieldIPSPBeasiswaCost;
    private javax.swing.JTextField jTextFieldIPSPIuranAmount;
    public javax.swing.JTextField jTextFieldIPSPNote;
    private javax.swing.JTextField jTextFieldIPSPSisaAmount;
    public javax.swing.JTextField jTextFieldIPSPTunai;
    // End of variables declaration//GEN-END:variables
}
