/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import iuran.Iuran;
import iuran.Attribute;
import iuran.AttributeTransactionDetail;
import iuran.TransactionDetail;
import java.awt.Component;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumnModel;
import javax.swing.table.TableModel;
import kasir.Control;
import org.openide.util.Exceptions;
import pelajar.Profil;
import sak.Kalender;
import sak.KasirException;


/**
 *
 * @author Master
 */
public class InputTransactionAttribute extends javax.swing.JFrame {
    Profil profil;
    private Attribute attribute;
    private List<Attribute> attributeS;
    private List<Attribute> attributeSToDB;
    private float unpaidAttribute = 0f;
    private InputTransactionFrameSeparated itfs;
    private TableModel tableModelAttribute;
    /**
     * Creates new form InputTransactionAttribute
     */
    public InputTransactionAttribute(Profil profil, InputTransactionFrameSeparated itfs) {
        this.profil = profil;
        this.itfs = itfs;
        try{
            tableModelAttribute = buildAttributeTableModel(profil);
        }catch(SQLException ex){
            ex.printStackTrace();
        }catch(KasirException ex){
            ex.printStackTrace();
        }
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelSeragam = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableAttribute = new javax.swing.JTable();
        jLabel19 = new javax.swing.JLabel();
        jUnpaidAttribute = new javax.swing.JTextField();
        jButtonBayarSeragam = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jPanelSeragam.setMinimumSize(new java.awt.Dimension(440, 550));
        jPanelSeragam.setPreferredSize(new java.awt.Dimension(480, 302));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel10.setText(org.openide.util.NbBundle.getMessage(InputTransactionAttribute.class, "InputTransactionAttribute.jLabel10.text")); // NOI18N

        try{
            tableModelAttribute = buildAttributeTableModel(profil);
        }catch(Exception e){
            e.printStackTrace();
        }
        jTableAttribute.setModel(tableModelAttribute);
        jTableAttribute.getColumn("Detail / History").setCellRenderer(new AttributeButtonRenderer());
        jTableAttribute.getColumn("Detail / History").setCellEditor(
            new AttributeButtonEditor(new JCheckBox()));
        jTableAttribute.removeColumn(jTableAttribute.getColumn("IuranID"));
        jTableAttribute.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jTableAttributePropertyChange(evt);
            }
        });
        jScrollPane2.setViewportView(jTableAttribute);

        jLabel19.setText(org.openide.util.NbBundle.getMessage(InputTransactionAttribute.class, "InputTransactionAttribute.jLabel19.text")); // NOI18N

        jUnpaidAttribute.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jUnpaidAttribute.setText(String.valueOf(unpaidAttribute));
        jUnpaidAttribute.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jUnpaidAttribute.setEnabled(false);

        jButtonBayarSeragam.setText(org.openide.util.NbBundle.getMessage(InputTransactionAttribute.class, "InputTransactionAttribute.jButtonBayarSeragam.text")); // NOI18N
        jButtonBayarSeragam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBayarSeragamActionPerformed(evt);
            }
        });

        jLabel1.setText(profil.biodata.nama);

        javax.swing.GroupLayout jPanelSeragamLayout = new javax.swing.GroupLayout(jPanelSeragam);
        jPanelSeragam.setLayout(jPanelSeragamLayout);
        jPanelSeragamLayout.setHorizontalGroup(
            jPanelSeragamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSeragamLayout.createSequentialGroup()
                .addGroup(jPanelSeragamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanelSeragamLayout.createSequentialGroup()
                        .addGroup(jPanelSeragamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelSeragamLayout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(104, 104, 104)
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jUnpaidAttribute, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelSeragamLayout.createSequentialGroup()
                                .addGap(285, 285, 285)
                                .addComponent(jButtonBayarSeragam))
                            .addComponent(jLabel1))
                        .addGap(0, 16, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelSeragamLayout.setVerticalGroup(
            jPanelSeragamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSeragamLayout.createSequentialGroup()
                .addGroup(jPanelSeragamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel19)
                    .addComponent(jUnpaidAttribute, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonBayarSeragam)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelSeragam, javax.swing.GroupLayout.DEFAULT_SIZE, 619, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelSeragam, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTableAttributePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jTableAttributePropertyChange
        // TODO add your handling code here:
        attributeSToDB = new ArrayList<>();
        if (jTableAttribute.getRowCount() > 0) {
            for (int i = 0; i < jTableAttribute.getRowCount(); i++) {
//                if((Boolean)jTableAttribute.getValueAt(i,3) && (attributeS.get(i).transactDetailIDs.size() == 0)){
                if(jTableAttribute.getModel().getValueAt(i,5) != null){
                    if((Float)jTableAttribute.getModel().getValueAt(i,5) > 0){
                        attributeS.get(i).amount = (Float)jTableAttribute.getModel().getValueAt(i,5);
                        attributeSToDB.add(attributeS.get(i));
                    }
                }
                //                    try {
                //attribute = Control.selectIuran(Iuran.Tipe.Attribute, Attribute.noIndukColName, false , profil.noInduk);
                //attributeS.remove(i);
//                    } catch (SQLException ex) {
//                        Exceptions.printStackTrace(ex);
//                    } catch (KasirException ex) {
//                        Exceptions.printStackTrace(ex);
//                    }
//                }
            }
        }
    }//GEN-LAST:event_jTableAttributePropertyChange

    private void jButtonBayarSeragamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBayarSeragamActionPerformed
        // TODO add your handling code here:
        float attributeAmountTemp = 0f;

        for (int i = 0; i < attributeSToDB.size(); i++) {
            if (attributeSToDB.get(i) != null) {

                //attributeAmountTemp = attributeAmountTemp + (Float) jTableAttribute.getModel().getValueAt(i, 3);
                attributeAmountTemp = attributeAmountTemp + attributeSToDB.get(i).amount;

            }
        }
        itfs.jTextFieldAttributeAmountSimple.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0"))));
        itfs.jTextFieldAttributeAmountSimple.setValue(attributeAmountTemp);
        try {
            itfs.jTextFieldAttributeAmountSimple.commitEdit();
        } catch (ParseException ex) {
            Exceptions.printStackTrace(ex);
        }
        itfs.attributeSToDB = attributeSToDB;
        itfs.attributeS = attributeS;
        this.setVisible(false);
    }//GEN-LAST:event_jButtonBayarSeragamActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public TableModel buildAttributeTableModel(Profil profil) throws SQLException, KasirException{
       String columnNames[] = {"Kelas","Detail / History", "Transaksi Attribute", "Biaya", "Sisa", "Pembayaran", "IuranID"};
       Set<Attribute> attributeFilters = new HashSet<>();
       attributeFilters.add(new Attribute(profil.noInduk,null, null, 0F, null));
       Map<Long, Attribute> searchResultMap = new HashMap<>();
       searchResultMap = Control.exactFilterSelectIurans(Iuran.Tipe.Attribute, attributeFilters);
       
       Set<Long> transactDetailIDsTemp = new HashSet<Long>();
       int j = 0;
       attributeS = new ArrayList<>();
       ArrayList<Long> attributeSPaid = new ArrayList<Long>();
       ArrayList<String> attributeSTransactionDate = new ArrayList<String>();
       ArrayList<AttributeTransactionDetail> stds = new ArrayList<AttributeTransactionDetail>();
       if(searchResultMap.size() > 0){
        for(Map.Entry<Long, Attribute> entry: searchResultMap.entrySet()){
            transactDetailIDsTemp.clear();
            transactDetailIDsTemp = entry.getValue().transactDetailIDs;
            long paidAttribute = 0l;
            String lastTransactionDate = "";
            SimpleDateFormat formatIndo = new SimpleDateFormat("dd-MM-yyyy");
            AttributeTransactionDetail std = new AttributeTransactionDetail();
            stds.clear();
            for(Long l : transactDetailIDsTemp){
                std = Control.selectTDetail(TransactionDetail.Tipe.AttributeTransaction, l);
                paidAttribute += std.amount;
                lastTransactionDate = formatIndo.format(std.lastUpdateDate.toDate());
                attributeSTransactionDate.add(lastTransactionDate);
                stds.add(std);
            }
            
            if(entry.getValue().amount > paidAttribute){
                attributeS.add(entry.getValue());
                attributeSPaid.add(paidAttribute);
            }
            j++;
        }
       }
       Object[][] data = new Object[attributeS.size()][columnNames.length];
       for(int i =0; i < attributeS.size(); i++){
            
            data[i][0]= attributeS.get(i).chargedLevel;
            data[i][1]= "Detail";
            data[i][2]= attributeS.get(i).transactName;
            data[i][3]= attributeS.get(i).amount;
            data[i][4]= attributeS.get(i).amount-attributeSPaid.get(i);
            data[i][5]= 0f;
            data[i][6]= attributeS.get(i).id;
//            if(attributeS.get(i).transactDetailIDs.size()>0){
//                data[i][3] = new Boolean(true);
//            }else{
//                data[i][3] = new Boolean(false);
//            }
       }
       itfs.unpaidAttribute = calculateUnpaidAttribute(profil);
       if(data.length > 0){
       TableModel tm = new DefaultTableModel(data, columnNames){
           @Override
            public boolean isCellEditable(int row, int column) {
                //all cells false for editable
               if(itfs.jDialogTransactionSummary.isVisible()){
                    return false;
               }else{
                    return true;
               }
            }
            public Class getColumnClass(int c) {
                return getValueAt(0, c).getClass();
            }
       };
       
       return tm;
       }else{
           TableModel tm = new DefaultTableModel(columnNames, columnNames.length);
           return tm;
       }
   }
    
    public TableModel buildAttributeSubmitTableModel(Profil profil, List<Attribute> stdb) throws SQLException, KasirException{
       String columnNames[] = {"Kelas","Detail / History", "Transaksi Attribute", "Biaya", "Sisa", "Pembayaran", "IuranID"};
       
       Set<Attribute> attributeFilters = new HashSet<>();
       Set<Long> attributeIDs = new HashSet<>();
       for(int i = 0 ; i < stdb.size(); i++){
           attributeIDs.add(stdb.get(i).id);
       }
       attributeFilters.addAll(stdb);
       Map<Long, Attribute> searchResultMap = new HashMap<>();
       //searchResultMap = Control.exactFilterSelectIurans(Iuran.Tipe.Attribute, attributeFilters);
       searchResultMap = Control.selectIurans(Iuran.Tipe.Attribute, attributeIDs);
       Set<Long> transactDetailIDsTemp = new HashSet<Long>();
       int j = 0;
       long paidAttribute = 0l;
       attributeS = new ArrayList<>();  
       ArrayList<Long> attributeSPaid = new ArrayList<Long>();
       ArrayList<Kalender> attributeSTransactionDate = new ArrayList<Kalender>();
       if(searchResultMap.size() > 0){
        for(Map.Entry<Long, Attribute> entry: searchResultMap.entrySet()){
            transactDetailIDsTemp.clear();
            transactDetailIDsTemp = entry.getValue().transactDetailIDs;
            paidAttribute = 0l;
            Kalender lastTransactionDate = new Kalender();
            AttributeTransactionDetail std = new AttributeTransactionDetail();
            for(Long l : transactDetailIDsTemp){
                std = Control.selectTDetail(TransactionDetail.Tipe.AttributeTransaction, l);
                paidAttribute += std.amount;
                lastTransactionDate = std.lastUpdateDate;
                attributeSTransactionDate.add(lastTransactionDate);
            }
            if(transactDetailIDsTemp.isEmpty()){
                attributeSTransactionDate.add(new Kalender());
            }
            
            if(entry.getValue().amount > paidAttribute){
                attributeS.add(entry.getValue());
                attributeSPaid.add(paidAttribute);
                
            }
            j++;
        }
       }
       Object[][] data = new Object[attributeS.size()][columnNames.length];
       for(int i =0; i < attributeS.size(); i++){
            data[i][0]= attributeS.get(i).chargedLevel;
            data[i][1]= attributeSTransactionDate.get(i);
            data[i][2]= attributeS.get(i).transactName;
            data[i][3] = attributeS.get(i).amount;
            data[i][4] = attributeS.get(i).amount - stdb.get(i).amount - attributeSPaid.get(i);
            data[i][5] = stdb.get(i).amount;
            data[i][6] = attributeS.get(i).id;
            itfs.unpaidAttribute = itfs.unpaidAttribute - stdb.get(i).amount;
       }
       
      
       if(data.length > 0){
       TableModel tm = new DefaultTableModel(data, columnNames){
           @Override
            public boolean isCellEditable(int row, int column) {
                //all cells false for editable
               if(itfs.jDialogTransactionSummary.isVisible()){
                    return false;
               }else{
                    return true;
               }
            }
            public Class getColumnClass(int c) {
                return getValueAt(0, c).getClass();
            }
       };
       
       return tm;
       }else{
           TableModel tm = new DefaultTableModel(columnNames, columnNames.length);
           return tm;
       }
   }
    
    private float calculateUnpaidAttribute(Profil profil) throws SQLException, KasirException {
       float retVal = 0;
       Set<Attribute> attributeFilters = new HashSet<>();
       attributeFilters.add(new Attribute(profil.noInduk,null, null, 0F, null));
       Map<Long, Attribute> searchResultMap = new HashMap<>();
       Set<Long> transactDetailIDsTemp = new HashSet<Long>();
       searchResultMap = Control.exactFilterSelectIurans(Iuran.Tipe.Attribute, attributeFilters);
       attributeS = new ArrayList<>();
       
       if(searchResultMap.size() > 0){
        for(Map.Entry<Long, Attribute> entry: searchResultMap.entrySet()){
            transactDetailIDsTemp.clear();
            transactDetailIDsTemp = entry.getValue().transactDetailIDs;
            long paidAttribute = 0l;
            for(Long l : transactDetailIDsTemp){
                paidAttribute += Control.selectTDetail(TransactionDetail.Tipe.AttributeTransaction, l).amount;
            }
            
            if(entry.getValue().amount > paidAttribute){
                attributeS.add(entry.getValue());
            }
            retVal += entry.getValue().amount - paidAttribute;
        }
       }
       unpaidAttribute = retVal;
       System.out.println("unpaid Attribute");
       System.out.println(unpaidAttribute);
       return retVal;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBayarSeragam;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JPanel jPanelSeragam;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JTable jTableAttribute;
    private javax.swing.JTextField jUnpaidAttribute;
    // End of variables declaration//GEN-END:variables
}


class AttributeButtonRenderer extends JButton implements TableCellRenderer {

  public AttributeButtonRenderer() {
    setOpaque(true);
  }

  public Component getTableCellRendererComponent(JTable table, Object value,
      boolean isSelected, boolean hasFocus, int row, int column) {
    if (isSelected) {
      setForeground(table.getSelectionForeground());
      setBackground(table.getSelectionBackground());
    } else {
      setForeground(table.getForeground());
      setBackground(UIManager.getColor("Button.background"));
    }
    setText((value == null) ? "" : value.toString());
    return this;
  }
}

/**
 * @version 1.0 11/09/98
 */

class AttributeButtonEditor extends DefaultCellEditor {
  protected JButton button;

  private String label;
  private String detail;
  private boolean isPushed;
  private JTable detailTable;
  private JScrollPane scrollPane;
  private ArrayList<AttributeTransactionDetail> stds;
  public AttributeButtonEditor(JCheckBox checkBox) {
    super(checkBox);
    button = new JButton();
    button.setOpaque(true);
    button.addActionListener(new ActionListener() {
      public void actionPerformed(ActionEvent e) {
        fireEditingStopped();
      }
    });
  }

  public Component getTableCellEditorComponent(JTable table, Object value,
      boolean isSelected, int row, int column) {
    if (isSelected) {
      button.setForeground(table.getSelectionForeground());
      button.setBackground(table.getSelectionBackground());
    } else {
      button.setForeground(table.getForeground());
      button.setBackground(table.getBackground());
    }
    SimpleDateFormat formatIndo = new SimpleDateFormat("dd-MM-yyyy hh:mm:ss");
    Set<Long> transactDetailIDsTemp = new HashSet<Long>();
    Attribute s;
    Long attributeID = (Long)table.getModel().getValueAt(row, 6);
    try {
        s = Control.selectIuran(Iuran.Tipe.Attribute, attributeID);
        transactDetailIDsTemp = s.transactDetailIDs;
    } catch (SQLException ex) {
        Exceptions.printStackTrace(ex);
    } catch (KasirException ex) {
        Exceptions.printStackTrace(ex);
    }
    AttributeTransactionDetail std = new AttributeTransactionDetail();
    detail = "";
    
    String columnNames[] = {"No", "Tanggal", "Pembayaran"};
    Object[][] data = new Object[transactDetailIDsTemp.size()][columnNames.length];
    int i = 0;
    for(Long l : transactDetailIDsTemp){
            try {
                std = Control.selectTDetail(TransactionDetail.Tipe.AttributeTransaction, l);
            } catch (SQLException ex) {
                Exceptions.printStackTrace(ex);
            } catch (KasirException ex) {
                Exceptions.printStackTrace(ex);
            }
            
            detail += String.valueOf(i);
            detail += ". Rp ";
            detail += String.valueOf(std.amount);
            detail += "\t";
            detail += formatIndo.format(std.lastUpdateDate.toDate());
            detail += "\r\n";
            
            data[i][0] = i+1;
            data[i][1] = formatIndo.format(std.lastUpdateDate.toDate());
            data[i][2] = "Rp ".concat(String.valueOf((Float)std.amount));
            i++;
    }
    
    TableModel tm = new DefaultTableModel(data, columnNames){
           @Override
            public boolean isCellEditable(int row, int column) {
                //all cells false for editable
               return false;
            }
            public Class getColumnClass(int c) {
                return getValueAt(0, c).getClass();
            }
       };
    
    detailTable = new JTable(tm){
        public Class getColumnClass(int c){
            return getValueAt(0, c).getClass();
        }
    };
    
    
    scrollPane = new JScrollPane(detailTable);
    
    
    label = (value == null) ? "" : value.toString();
    
    button.setText(label);
    isPushed = true;
    return button;
  }

  public Object getCellEditorValue() {
    if (isPushed) {
      // 
      // 
      JOptionPane.showMessageDialog(button, scrollPane, "Attribute", JOptionPane.INFORMATION_MESSAGE);
      
      // System.out.println(label + ": Ouch!");
    }
    isPushed = false;
    return new String(label);
  }

  public boolean stopCellEditing() {
    isPushed = false;
    return super.stopCellEditing();
  }

  protected void fireEditingStopped() {
    super.fireEditingStopped();
  }
}
