/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import iuran.*;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.*;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import kasir.Control;
import org.openide.util.Exceptions;
import pelajar.Level;
import pelajar.Profil;
import printout.TunggakanBean;
import sak.KasirException;

/**
 *
 * @author Master
 */
public class InputTransactionCicilanHutang extends javax.swing.JFrame {
    Profil profil;
    private TableModel tableModelCicilanHutang;
    private CicilanHutang cicilanHutangFromDB;
    private List<Integer> tahunCicilanHutang;
    private ArrayList<Float> iDDAmounts;
    public ArrayList<Float> beasiswaAmounts;
    public ArrayList<Float> beasiswaCostAmounts;
    public ArrayList<Float> cicilanHutangAmounts;
    private CicilanHutang cicilanHutangCurrent;
    private CicilanHutang cicilanHutangStoreToDB;
    private float cicilanHutangDebt;
    private IDD idd;
    private InputTransactionFrameSeparated itfs;
    private final String[] namaBulan = {"JULI", "AGUSTUS", "SEPTEMBER", "OKTOBER", "NOPEMBER", "DESEMBER", "JANUARI", "PEBRUARI", "MARET", "APRIL", "MEI", "JUNI"};
    private float unpaidCicilanHutang;
    private ComboBoxModel tahunComboBoxModel;
    private String tunggakanCicilanHutangString = new String("");
    private String tunggakanCicilanHutangEachAmountString = new String("");
    /**
     * Creates new form InputTransactionCicilanHutang
     */
    
    public InputTransactionCicilanHutang(Profil profil, InputTransactionFrameSeparated itfs) {
        this.profil = profil;
        this.itfs = itfs;
        try {
            tableModelCicilanHutang = buildCicilanHutangTableModel(profil, profil.currentLevel.tahun);
        } catch (SQLException ex) {
            Exceptions.printStackTrace(ex);
        } catch (KasirException ex) {
            Exceptions.printStackTrace(ex);
        }
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelCicilanHutang = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabelTahun = new javax.swing.JLabel();
        jComboBoxTahun = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jUnpaidCicilanHutang = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTableCicilanHutang = new javax.swing.JTable();
        jButtonBayarCicilanHutang = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jFormattedTextFieldIDDSaldo = new javax.swing.JFormattedTextField();
        jTextFieldCicilanHutangDebt = new javax.swing.JFormattedTextField();

        setTitle(org.openide.util.NbBundle.getMessage(InputTransactionCicilanHutang.class, "InputTransactionCicilanHutang.title")); // NOI18N

        jPanelCicilanHutang.setMinimumSize(new java.awt.Dimension(570, 380));
        jPanelCicilanHutang.setPreferredSize(new java.awt.Dimension(680, 450));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText(org.openide.util.NbBundle.getMessage(InputTransactionCicilanHutang.class, "InputTransactionCicilanHutang.jLabel1.text")); // NOI18N

        jLabelTahun.setText(org.openide.util.NbBundle.getMessage(InputTransactionCicilanHutang.class, "InputTransactionCicilanHutang.jLabelTahun.text")); // NOI18N

        try{
            tahunComboBoxModel = buildCicilanHutangtahunComboBoxModel(profil);
        }catch(SQLException ex){
            ex.printStackTrace();
        }catch(KasirException ex){
            ex.printStackTrace();
        }
        jComboBoxTahun.setModel(tahunComboBoxModel);
        jComboBoxTahun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTahunActionPerformed(evt);
            }
        });
        jComboBoxTahun.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jComboBoxTahunPropertyChange(evt);
            }
        });

        jLabel2.setText(org.openide.util.NbBundle.getMessage(InputTransactionCicilanHutang.class, "InputTransactionCicilanHutang.jLabel2.text")); // NOI18N

        jUnpaidCicilanHutang.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jUnpaidCicilanHutang.setText(String.valueOf(unpaidCicilanHutang));
        jUnpaidCicilanHutang.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jUnpaidCicilanHutang.setEnabled(false);

        jTableCicilanHutang.setModel(tableModelCicilanHutang);
        jTableCicilanHutang.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jTableCicilanHutang.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTableCicilanHutangFocusLost(evt);
            }
        });
        jTableCicilanHutang.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jTableCicilanHutangPropertyChange(evt);
            }
        });
        jScrollPane5.setViewportView(jTableCicilanHutang);

        jButtonBayarCicilanHutang.setText(org.openide.util.NbBundle.getMessage(InputTransactionCicilanHutang.class, "InputTransactionCicilanHutang.jButtonBayarCicilanHutang.text")); // NOI18N
        jButtonBayarCicilanHutang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBayarCicilanHutangActionPerformed(evt);
            }
        });

        jLabel3.setText(org.openide.util.NbBundle.getMessage(InputTransactionCicilanHutang.class, "InputTransactionCicilanHutang.jLabel3.text")); // NOI18N

        jFormattedTextFieldIDDSaldo.setText(org.openide.util.NbBundle.getMessage(InputTransactionCicilanHutang.class, "InputTransactionCicilanHutang.jFormattedTextFieldIDDSaldo.text")); // NOI18N
        jFormattedTextFieldIDDSaldo.setEnabled(false);

        jTextFieldCicilanHutangDebt.setEditable(false);
        jTextFieldCicilanHutangDebt.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0"))));

        javax.swing.GroupLayout jPanelCicilanHutangLayout = new javax.swing.GroupLayout(jPanelCicilanHutang);
        jPanelCicilanHutang.setLayout(jPanelCicilanHutangLayout);
        jPanelCicilanHutangLayout.setHorizontalGroup(
            jPanelCicilanHutangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCicilanHutangLayout.createSequentialGroup()
                .addGroup(jPanelCicilanHutangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCicilanHutangLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane5))
                    .addGroup(jPanelCicilanHutangLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(29, 29, 29)
                        .addComponent(jLabelTahun)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelCicilanHutangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBoxTahun, 0, 101, Short.MAX_VALUE)
                            .addComponent(jTextFieldCicilanHutangDebt))
                        .addGap(33, 33, 33)
                        .addGroup(jPanelCicilanHutangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGroup(jPanelCicilanHutangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelCicilanHutangLayout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(jUnpaidCicilanHutang, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelCicilanHutangLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jFormattedTextFieldIDDSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 16, Short.MAX_VALUE))))
                    .addGroup(jPanelCicilanHutangLayout.createSequentialGroup()
                        .addGap(248, 248, 248)
                        .addComponent(jButtonBayarCicilanHutang)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelCicilanHutangLayout.setVerticalGroup(
            jPanelCicilanHutangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCicilanHutangLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanelCicilanHutangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxTahun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTahun)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jUnpaidCicilanHutang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCicilanHutangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jFormattedTextFieldIDDSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldCicilanHutangDebt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonBayarCicilanHutang)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelCicilanHutang, javax.swing.GroupLayout.DEFAULT_SIZE, 570, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelCicilanHutang, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxTahunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTahunActionPerformed
        // TODO add your handling code here:
        try {
            this.tableModelCicilanHutang = (DefaultTableModel) buildCicilanHutangTableModel(this.profil, this.tahunCicilanHutang.get(jComboBoxTahun.getSelectedIndex()));
            jTableCicilanHutang.setModel(this.tableModelCicilanHutang);
            jTextFieldCicilanHutangDebt.setValue(cicilanHutangDebt);
        } catch (SQLException ex) {
            ex.printStackTrace();
        } catch (KasirException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jComboBoxTahunActionPerformed

    private void jComboBoxTahunPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jComboBoxTahunPropertyChange
        // TODO add your handling code here:
        try {
            if (this.jComboBoxTahun.getSelectedItem() != null) {
                this.tableModelCicilanHutang = (DefaultTableModel) buildCicilanHutangTableModel(this.profil, this.tahunCicilanHutang.get(jComboBoxTahun.getSelectedIndex()));
                jTableCicilanHutang.setModel(this.tableModelCicilanHutang);
                jTextFieldCicilanHutangDebt.setValue(cicilanHutangDebt);
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(rootPane, "Koneksi Error!\r\n".concat(ex.toString()));
        } catch (KasirException ex) {
            JOptionPane.showMessageDialog(rootPane, "CicilanHutang Belum Di Setting!\r\n".concat(ex.toString()));
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jComboBoxTahunPropertyChange

    private void jTableCicilanHutangFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTableCicilanHutangFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTableCicilanHutangFocusLost

    private void jTableCicilanHutangPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jTableCicilanHutangPropertyChange
        // TODO add your handling code here:
        //IDD, Beasiswa, Beasiswa Cost
        cicilanHutangAmounts = new ArrayList();
        iDDAmounts = new ArrayList();
        beasiswaAmounts = new ArrayList();
        beasiswaCostAmounts = new ArrayList();
        /////BLOOOOOOOOOOM SELESAIIIIIIIIIIIIIIIIIIII
        int i = 0;
        cicilanHutangCurrent = new CicilanHutang();
        cicilanHutangStoreToDB = new CicilanHutang();
        ArrayList<Entry> entry = new ArrayList<>();
        if (cicilanHutangFromDB.entries.size() != 0) {
            for (i = 0; i < jTableCicilanHutang.getRowCount(); i++) {
                cicilanHutangCurrent.entries.add((Boolean) jTableCicilanHutang.getValueAt(i, 2) ? ((cicilanHutangFromDB.entries.get(i).transactDetailIDs.size() > 0) ? new Entry(i, cicilanHutangFromDB.entries.get(i).amount, cicilanHutangFromDB.entries.get(i).debt, cicilanHutangFromDB.entries.get(i).transactDetailIDs) : new Entry(i, cicilanHutangFromDB.entries.get(i).amount)) : null);
                //below condition is when jTableCicilanHutang checkBox is UNCHECK ????
                if (cicilanHutangCurrent.entries.get(i) == null) {
                    cicilanHutangStoreToDB.entries.add(null);
                    jTableCicilanHutang.setValueAt(0f, i, 3);
                    jTableCicilanHutang.setValueAt(0f, i, 4);
                    jTableCicilanHutang.setValueAt(0f, i, 5);
                    jTableCicilanHutang.setValueAt(0f, i, 6);
                    cicilanHutangAmounts.add(0f);
                    iDDAmounts.add(0f);
                    beasiswaAmounts.add(0f);
                    beasiswaCostAmounts.add(0f);
                    //below is when jTableCicilanHutang property changed, especially check box is Changed or Editing IDD, Beasiswa, Beasiswa Cost 
                } else if ((cicilanHutangCurrent.entries.get(i) != null) ^ (cicilanHutangFromDB.entries.get(i).transactDetailIDs.size() > 0)) {
                    System.out.println("IDD dari db ");
                    if (idd != null) {
                        System.out.println(idd.amount);
                    }
                    cicilanHutangAmounts.add((Float) jTableCicilanHutang.getModel().getValueAt(i,3));
                    iDDAmounts.add((Float) jTableCicilanHutang.getValueAt(i, 4));
                    beasiswaAmounts.add((Float) jTableCicilanHutang.getValueAt(i, 5));
                    beasiswaCostAmounts.add((Float) jTableCicilanHutang.getValueAt(i, 6));
                    //jTableCicilanHutang.setValueAt(cicilanHutangFromDB.entries.get(i).amount - (iDDAmounts.get(i) + beasiswaAmounts.get(i) + beasiswaCostAmounts.get(i)), i, 3);
                    //cicilanHutangStoreToDB.entries.add(new Entry(i, cicilanHutangFromDB.entries.get(i).amount));
                    cicilanHutangStoreToDB.entries.add(new Entry(i, cicilanHutangAmounts.get(i)+iDDAmounts.get(i)+beasiswaAmounts.get(i)+beasiswaCostAmounts.get(i)));
                } else {
                    try {
                        if(isCicilanHutangEnough(cicilanHutangFromDB.entries.get(i).transactDetailIDs, cicilanHutangFromDB.entries.get(i).amount)){
                            cicilanHutangAmounts.add(0f);
                            iDDAmounts.add(0f);
                            beasiswaAmounts.add(0f);
                            beasiswaCostAmounts.add(0f);
                            cicilanHutangStoreToDB.entries.add(null);
                        }else{
                            cicilanHutangAmounts.add((Float) jTableCicilanHutang.getModel().getValueAt(i,3));
                            iDDAmounts.add((Float) jTableCicilanHutang.getValueAt(i, 4));
                            beasiswaAmounts.add((Float) jTableCicilanHutang.getValueAt(i, 5));
                            beasiswaCostAmounts.add((Float) jTableCicilanHutang.getValueAt(i, 6));
                            cicilanHutangStoreToDB.entries.add(new Entry(i, cicilanHutangAmounts.get(i)+iDDAmounts.get(i)+beasiswaAmounts.get(i)+beasiswaCostAmounts.get(i)));
                        }
                    } catch (SQLException ex) {
                        Exceptions.printStackTrace(ex);
                    } catch (KasirException ex) {
                        Exceptions.printStackTrace(ex);
                    }
                    

                }
                //cicilanHutangCurrent.entries.add((Boolean)jTableCicilanHutang.getValueAt(i,2)? new CicilanHutang(profil.noInduk, new Level(null,null,null,(Integer)jComboBoxTahun.getSelectedItem()),entry).entries.get(i): null);
                //cicilanHutangStoreToDB.entries.add(cicilanHutangCurrent.entries.get(i)==null?null:(((cicilanHutangCurrent.entries.get(i)!=null)^(cicilanHutangFromDB.entries.get(i)!=null))? new CicilanHutang(profil.noInduk, new Level(null,null,null,(int)jComboBoxTahun.getSelectedItem()),entry).entries.get(i):cicilanHutangCurrent.entries.get(i)));
                //System.out.println("CicilanHutang Period: "+cicilanHutangCurrent.entries.get(i).period);
            }
        }
    }//GEN-LAST:event_jTableCicilanHutangPropertyChange

    private void jButtonBayarCicilanHutangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBayarCicilanHutangActionPerformed
        // TODO add your handling code here:
        float cicilanHutangAmountTemp = 0f;
        for (int i = 0; i < 12; i++) {
            if (cicilanHutangStoreToDB.entries.get(i) != null) {
                //cicilanHutangAmountTemp = cicilanHutangAmountTemp + cicilanHutangFromDB.entries.get(i).amount;
                cicilanHutangAmountTemp = cicilanHutangAmountTemp + (Float)jTableCicilanHutang.getModel().getValueAt(i,3)
                                +(Float)jTableCicilanHutang.getModel().getValueAt(i,4)
                                +(Float)jTableCicilanHutang.getModel().getValueAt(i,5)
                                +(Float)jTableCicilanHutang.getModel().getValueAt(i,6);
            }
        }
        itfs.jTextFieldCicilanHutangAmountSimple.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0"))));
        itfs.jTextFieldCicilanHutangAmountSimple.setValue(cicilanHutangAmountTemp);
        try {
            itfs.jTextFieldCicilanHutangAmountSimple.commitEdit();
        } catch (ParseException ex) {
            Exceptions.printStackTrace(ex);
        }
        itfs.cicilanHutangCurrent = cicilanHutangCurrent;
        itfs.cicilanHutangFromDB = cicilanHutangFromDB;
        itfs.cicilanHutangStoreToDB = cicilanHutangStoreToDB;
        this.setVisible(false);

    }//GEN-LAST:event_jButtonBayarCicilanHutangActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InputTransactionFrameSeparated.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InputTransactionFrameSeparated.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InputTransactionFrameSeparated.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InputTransactionFrameSeparated.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                //new InputTransactionCicilanHutang().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBayarCicilanHutang;
    private javax.swing.JComboBox jComboBoxTahun;
    private javax.swing.JFormattedTextField jFormattedTextFieldIDDSaldo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelTahun;
    private javax.swing.JPanel jPanelCicilanHutang;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTableCicilanHutang;
    private javax.swing.JFormattedTextField jTextFieldCicilanHutangDebt;
    private javax.swing.JTextField jUnpaidCicilanHutang;
    // End of variables declaration//GEN-END:variables

    public TableModel buildCicilanHutangTableModel(Profil profil, int tahun) throws SQLException, KasirException {
       String columnNames[] = {"Bulan", "Biaya CicilanHutang", "Check Box", "Tunai", "Iuran Dibayar Dimuka", "Beasiswa", "Beasiswa Yayasan"};
       Set<CicilanHutang> cicilanHutangFilters = new HashSet<>();
       ArrayList<Entry> entries = new ArrayList<>();
       cicilanHutangFilters.clear();
       cicilanHutangFilters.add(new CicilanHutang(profil.noInduk, new Level(null,null,null,tahun), entries));
       Map<Long, CicilanHutang> searchResultMap = Control.exactFilterSelectIurans(Iuran.Tipe.CicilanHutang, cicilanHutangFilters);
       Object[][] data = new Object[12][7];
       int i = 0;
       final boolean[] canEdit = new boolean [12];
       cicilanHutangFromDB = new CicilanHutang();
       float amountCicilanHutanginTable;
       float amountCicilanHutanginTDetail;
       cicilanHutangDebt = 0f;
       
       //Get Month and Year for calculate IuranPeriodic 12 times a year (Monthly)
       Calendar calendarRunning = Calendar.getInstance();
       int targetMonth = calendarRunning.get(Calendar.MONTH);
       int targetYear = calendarRunning.get(Calendar.YEAR);
       if(targetMonth>5){//JULY - DECEMBER
           targetMonth = targetMonth - 5;
       }else{//JANUARY - JUNE
           targetMonth = targetMonth + 7;
           targetYear = targetYear - 1;
       }
       
       if(searchResultMap.size() > 0){
        for(Map.Entry<Long, CicilanHutang> entry: searchResultMap.entrySet()){
            for(int j =0 ; j< entry.getValue().entries.size(); j++){
                data[j][0]= namaBulan[j];//entry.getValue().entries.get(j).period;
                data[j][1]= entry.getValue().entries.get(j).amount - calculatePaidCicilanHutang(entry.getValue().entries.get(j).transactDetailIDs); // ANEH NIH MASA BEGINI, DI KALI DUA SIH?
                amountCicilanHutanginTable = entry.getValue().entries.get(j).amount;
                if(entry.getValue().chargedLevel.tahun < targetYear){
                    cicilanHutangDebt += entry.getValue().entries.get(j).debt;
                }else if(entry.getValue().chargedLevel.tahun == targetYear && j < targetMonth){
                    cicilanHutangDebt += entry.getValue().entries.get(j).debt;
                }
                
                //if(jTable2 != null){data[j][2]= jTable2.getModel().getValueAt(j,2);}else{data[j][2]= new Boolean(false);}
                //if(entry.getValue().entries.get(j).transactDetailIDs.size() > 0){
                if(isCicilanHutangEnough(entry.getValue().entries.get(j).transactDetailIDs, amountCicilanHutanginTable)){        
//                    
                    data[j][2] = new Boolean(true);
                    Float data3 = 0f;
                    Float data4 = 0f;
                    Float data5 = 0f;
                    Float data6 = 0f;
                    
                    for(Long setTDetailIds:entry.getValue().entries.get(j).transactDetailIDs){
                        System.out.println(setTDetailIds + " Set TDetailsID");
                        if(Control.selectTDetail(TransactionDetail.Tipe.CicilanHutangTransaction, setTDetailIds).paymentMethod == TransactionDetail.PaymentMethod.CASH){
                            data3 += Control.selectTDetail(TransactionDetail.Tipe.CicilanHutangTransaction, setTDetailIds).amount;
                            data[j][3] = data3;
                        }
                        if(Control.selectTDetail(TransactionDetail.Tipe.CicilanHutangTransaction, setTDetailIds).paymentMethod == TransactionDetail.PaymentMethod.IDD){
                            data4 += Control.selectTDetail(TransactionDetail.Tipe.CicilanHutangTransaction, setTDetailIds).amount;
                            data[j][4] = data4;
                        }
                        if(Control.selectTDetail(TransactionDetail.Tipe.CicilanHutangTransaction, setTDetailIds).paymentMethod == TransactionDetail.PaymentMethod.BEASISWA){
                            data5 += Control.selectTDetail(TransactionDetail.Tipe.CicilanHutangTransaction, setTDetailIds).amount;
                            data[j][5] = data5;
                        }
                        if(Control.selectTDetail(TransactionDetail.Tipe.CicilanHutangTransaction, setTDetailIds).paymentMethod == TransactionDetail.PaymentMethod.BEASISWA_COST){
                            data6 += Control.selectTDetail(TransactionDetail.Tipe.CicilanHutangTransaction, setTDetailIds).amount;
                            data[j][6] = data6;
                        }
                    }
                    if(data[j][3] == null){
                        data[j][3] = 0f;
                    }
                    if(data[j][4] == null){
                        data[j][4] = 0f;
                    }
                    if(data[j][5] == null){
                        data[j][5] = 0f;
                    }
                    if(data[j][6] == null){
                        data[j][6] = 0f;
                    }
                            
                }else{
                    data[j][2] = new Boolean(false);
                    if(entry.getValue().entries.get(j).transactDetailIDs.size() > 0){
                        for(Long setTDetailIds:entry.getValue().entries.get(j).transactDetailIDs){
                            System.out.println(setTDetailIds + " Set TDetailsID");
                            if(Control.selectTDetail(TransactionDetail.Tipe.CicilanHutangTransaction, setTDetailIds).paymentMethod == TransactionDetail.PaymentMethod.CASH){
                                data[j][3] = Control.selectTDetail(TransactionDetail.Tipe.CicilanHutangTransaction, setTDetailIds).amount;
                            }
                            if(Control.selectTDetail(TransactionDetail.Tipe.CicilanHutangTransaction, setTDetailIds).paymentMethod == TransactionDetail.PaymentMethod.IDD){
                                data[j][4] = Control.selectTDetail(TransactionDetail.Tipe.CicilanHutangTransaction, setTDetailIds).amount;
                            }
                            if(Control.selectTDetail(TransactionDetail.Tipe.CicilanHutangTransaction, setTDetailIds).paymentMethod == TransactionDetail.PaymentMethod.BEASISWA){
                                data[j][5] = Control.selectTDetail(TransactionDetail.Tipe.CicilanHutangTransaction, setTDetailIds).amount;
                            }
                            if(Control.selectTDetail(TransactionDetail.Tipe.CicilanHutangTransaction, setTDetailIds).paymentMethod == TransactionDetail.PaymentMethod.BEASISWA_COST){
                                data[j][6] = Control.selectTDetail(TransactionDetail.Tipe.CicilanHutangTransaction, setTDetailIds).amount;
                            }
                        }
                        if(data[j][3] == null){
                        data[j][3] = 0f;
                        }
                        if(data[j][4] == null){
                            data[j][4] = 0f;
                        }
                        if(data[j][5] == null){
                            data[j][5] = 0f;
                        }
                        if(data[j][6] == null){
                            data[j][6] = 0f;
                        }
                    }else{
                        data[j][3]=0f;
                        data[j][4]=0f;
                        data[j][5]=0f;
                        data[j][6]=0f;
                    }
                }
                
                cicilanHutangFromDB.entries.add(entry.getValue().entries.get(j));
                //canEdit[j] = (entry.getValue().entries.get(j).transactDetailIDs.size() > 0);
                
                for(Long id : entry.getValue().entries.get(j).transactDetailIDs){
                    canEdit[j] = Control.selectTDetail(TransactionDetail.Tipe.CicilanHutangTransaction, id).settled;
                }
                
                
            }
            cicilanHutangFromDB.id = entry.getValue().id;
            cicilanHutangFromDB.noInduk = entry.getValue().noInduk;
            cicilanHutangFromDB.chargedLevel = entry.getValue().chargedLevel;
            i++;
            System.out.println("cicilanHutang debt "+String.valueOf(cicilanHutangDebt));
        }
        TableModel tm = new DefaultTableModel(data, columnNames){
            boolean[] chooseEdit = new boolean[]{false,false,true,true,true,true,true};
            
           @Override
            public boolean isCellEditable(int row, int column) {
                //all cells false for editable
                if(!itfs.jDialogTransactionSummary.isVisible()){
                    if((Boolean)getValueAt(row, 2)){
                    //if((Float)getValueAt(row,1) == 0f){
                        if((column == 0 || column ==1)){
                            return column == 2;
                        //return false;
                        }
                        return !canEdit[row];
                    }
                    if((column == 0 && column ==1)|| column == 2){
                            //return column == 2;
                        return chooseEdit[column];
                    }

                    return false;
               }else{
                    return false;
                }
            }
            public Class getColumnClass(int c) {
                return getValueAt(0, c).getClass();
            }
       };
       
       return tm;
       }else{
           TableModel tm = new DefaultTableModel(data, columnNames);
           JOptionPane.showMessageDialog(rootPane, "CicilanHutang Belum Di Setting!\r\n");
           this.dispose();
           return null;
       }
       
       
    }
    public TableModel buildCicilanHutangSubmitTableModel(Profil profil, int tahun) throws SQLException, KasirException {
       String columnNames[] = {"Bulan", "Biaya CicilanHutang", "Check Box", "Tunai", "Iuran Dibayar Dimuka", "Beasiswa", "Beasiswa Yayasan"};
       Object[][] data = new Object[12][7];
       
       final boolean[] canEdit = new boolean [12];
         
        for(int i = 0 ; i < cicilanHutangCurrent.entries.size(); i++){
                data[i][0]= namaBulan[i];//entry.getValue().entries.get(j).period;
                data[i][1]= cicilanHutangFromDB.entries.get(i).amount; // ANEH NIH MASA BEGINI, DI KALI DUA SIH?
                if(cicilanHutangCurrent.entries.get(i) != null){
//                    if(jTableCicilanHutang != null){
//                        data[j][2]=jTableCicilanHutang.getValueAt(j,2);
//                    }else{
                        data[i][2] = new Boolean(true);
//                        data[i][3] = cicilanHutangFromDB.entries.get(i).amount-(iDDAmounts.get(i)+beasiswaAmounts.get(i)+beasiswaCostAmounts.get(i));
                        data[i][3] = cicilanHutangAmounts.get(i);
                        data[i][4] = iDDAmounts.get(i);
                        data[i][5] = beasiswaAmounts.get(i);
                        data[i][6] = beasiswaCostAmounts.get(i);
//                    }
                }else{
//                    if(jTableCicilanHutang !=null){
//                        data[j][2]=jTableCicilanHutang.getValueAt(j,2);
//                    }else{
                        data[i][2] = new Boolean(false);
//                        data[i][3] = cicilanHutangFromDB.entries.get(i).amount-(iDDAmounts.get(i)+beasiswaAmounts.get(i)+beasiswaCostAmounts.get(i));
                        data[i][3] = cicilanHutangAmounts.get(i);
                        data[i][4] = iDDAmounts.get(i);
                        data[i][5] = beasiswaAmounts.get(i);
                        data[i][6] = beasiswaCostAmounts.get(i);
//                    }
                }
       }
       
       TableModel tm = new DefaultTableModel(data, columnNames){
            boolean[] chooseEdit = new boolean[]{false,false,true};
            
           @Override
            public boolean isCellEditable(int row, int column) {
                //all cells false for editable
                if(!itfs.jDialogTransactionSummary.isVisible()){
                    if((Boolean)getValueAt(row, 2)){
                        if((column == 0 || column ==1)){
                            return column == 2;
                        //return false;
                        }
                        return !canEdit[row];
                    }
                    if((column == 0 && column ==1)|| column == 2){
                            //return column == 2;
                        return chooseEdit[column];
                    }

                    return false;
               }else{
                    return false;
                }
            }
            public Class getColumnClass(int c) {
                return getValueAt(0, c).getClass();
            }
       };
       
       return tm;
    }
    
private ComboBoxModel buildCicilanHutangtahunComboBoxModel(Profil profil) throws SQLException, KasirException {
       Set<CicilanHutang> cicilanHutangFilters = new HashSet<>();
       ArrayList<Entry> entries = new ArrayList();
       cicilanHutangFilters.add(new CicilanHutang(profil.noInduk, null, entries));
       Map<Long, CicilanHutang> searchResultMap = Control.exactFilterSelectIurans(Iuran.Tipe.CicilanHutang, cicilanHutangFilters);
       this.tahunCicilanHutang = new ArrayList<>();
       List<String> tahunAjaran = new ArrayList<>();
       Object[][] data = new Object[searchResultMap.size()][12];
       int i = 0;
       if(searchResultMap.size() > 0){
        for(Map.Entry<Long, CicilanHutang> entry: searchResultMap.entrySet()){
            data[i][0]= entry.getValue().entries.get(i);
            data[i][1]= entry.getValue().entries.get(i).amount;
            this.tahunCicilanHutang.add(entry.getValue().chargedLevel.tahun);
            tahunAjaran.add(String.valueOf(entry.getValue().chargedLevel.tahun).concat(" - ").concat(String.valueOf(entry.getValue().chargedLevel.tahun+1)));
            i++;
        }
       }
       calculateUnpaidCicilanHutang(profil, tahunCicilanHutang);
       //== bikin tunggakan beans ===
       
       
       //== end bikin tunggakan beans ===
       
       tahunComboBoxModel = new DefaultComboBoxModel(tahunAjaran.toArray());
       return tahunComboBoxModel;
    }

private float calculateUnpaidCicilanHutang(Profil profil, List<Integer> tahuns) throws SQLException, KasirException {
       Set<CicilanHutang> cicilanHutangFilters = new HashSet<>();
       float retVal = 0;
       ArrayList<Entry> entries = new ArrayList<>();
       cicilanHutangFilters.clear();
       int targetMonth = Calendar.getInstance().get(Calendar.MONTH);
       int targetYear = Calendar.getInstance().get(Calendar.YEAR);
       if(targetMonth>5){//JULY - DECEMBER
           targetMonth = targetMonth - 5;
       }else{//JANUARY - JUNE
           targetMonth = targetMonth + 7;
           targetYear = targetYear - 1;
       }
       System.out.println("Month INT: "+Calendar.getInstance().get(Calendar.MONTH));
       for(int i = 0; i< tahuns.size(); i++){
           cicilanHutangFilters.add(new CicilanHutang(profil.noInduk, new Level(null,null,null,tahuns.get(i)), entries));
           
        }
       Map<Long, CicilanHutang> searchResultMap = Control.exactFilterSelectIurans(Iuran.Tipe.CicilanHutang, cicilanHutangFilters);
        if(searchResultMap.size() > 0){
            for(Map.Entry<Long, CicilanHutang> entry: searchResultMap.entrySet()){
                for(int j =0 ; j< entry.getValue().entries.size(); j++){
                    if((entry.getValue().entries.get(j).transactDetailIDs.isEmpty()) 
                            && ((entry.getValue().chargedLevel.tahun < targetYear)? true:(entry.getValue().entries.get(j).period <= targetMonth))){
                        retVal += entry.getValue().entries.get(j).amount;
                    }else if(entry.getValue().entries.get(j).transactDetailIDs.size() > 0){
                        Float temp = 0f;
                        for(Long l : entry.getValue().entries.get(j).transactDetailIDs){
                            temp += Control.selectTDetail(TransactionDetail.Tipe.CicilanHutangTransaction, l).amount;
                        }
                        if(temp < entry.getValue().entries.get(j).amount){
                            retVal += entry.getValue().entries.get(j).amount-temp;
                        } 
                    }
                }
            }
        }
       unpaidCicilanHutang = retVal;
       return retVal;
    }
    
    public ArrayList<TunggakanBean> calculateUnpaidCicilanHutangs(ArrayList<Profil> profils, List<Integer> tahuns) throws SQLException, KasirException {
       Set<CicilanHutang> cicilanHutangFilters = new HashSet<>();
       ArrayList<TunggakanBean> retVals = new ArrayList<>();
       float retVal = 0;
       ArrayList<Entry> entries = new ArrayList<>();
       cicilanHutangFilters.clear();
       int targetMonth = Calendar.getInstance().get(Calendar.MONTH);
       int targetYear = Calendar.getInstance().get(Calendar.YEAR);
       if(targetMonth>5){//JULY - DECEMBER
           targetMonth = targetMonth - 5;
       }else{//JANUARY - JUNE
           targetMonth = targetMonth + 7;
           targetYear = targetYear - 1;
       }
       System.out.println("Month INT: "+Calendar.getInstance().get(Calendar.MONTH));
       ArrayList<String> noInduks = new ArrayList<>();
       for(int i = 0; i< profils.size() ; i++){
           noInduks.add(profils.get(i).noInduk);
            for(int j = 0; j< tahuns.size(); j++){
                cicilanHutangFilters.add(new CicilanHutang(profils.get(i).noInduk, new Level(null,null,null,tahuns.get(j)), entries));

            }
       }
       List<CicilanHutang> test = Control.selectIurans(Iuran.Tipe.CicilanHutang, CicilanHutang.noIndukColName, false, noInduks.toArray(new String[0]));
       
       for(int i = 0 ; i< test.size(); i++){
           TunggakanBean tb = new TunggakanBean();
           for(int j = 0 ; j < test.get(i).entries.size(); j++){
               if(j==0) retVal=0;
               Float totalAmountCicilanHutangTDetails = 0f;
               for(Long l : test.get(i).entries.get(j).transactDetailIDs){
                   totalAmountCicilanHutangTDetails += Control.selectTDetail(TransactionDetail.Tipe.CicilanHutangTransaction, l).amount;
               }
               if((totalAmountCicilanHutangTDetails < test.get(i).entries.get(j).amount)
                   && ((test.get(i).chargedLevel.tahun < targetYear? true: (test.get(i).entries.get(j).period <= targetMonth)))){
                    
                            
                            retVal += test.get(i).entries.get(j).amount-totalAmountCicilanHutangTDetails;
                            tunggakanCicilanHutangString = tunggakanCicilanHutangString.concat("CicilanHutang Bulan ");
                            tunggakanCicilanHutangString = tunggakanCicilanHutangString.concat(getMonthName(test.get(i).entries.get(j).period));
                            tunggakanCicilanHutangString = tunggakanCicilanHutangString.concat(" "+String.valueOf(test.get(i).chargedLevel.tahun)+"/"+String.valueOf(1+test.get(i).chargedLevel.tahun));
                            tunggakanCicilanHutangString = tunggakanCicilanHutangString.concat("\r\n");
                            
                            tunggakanCicilanHutangEachAmountString = tunggakanCicilanHutangEachAmountString.concat("Rp. ");
                            tunggakanCicilanHutangEachAmountString = tunggakanCicilanHutangEachAmountString.concat(String.valueOf(Math.round(test.get(i).entries.get(j).amount-totalAmountCicilanHutangTDetails)));
                            tunggakanCicilanHutangEachAmountString = tunggakanCicilanHutangEachAmountString.concat("\r\n");
               }
               
                
               
               
           }
           tb.setProfil(profils.get(i));
           tb.setTunggakanCicilanHutang(retVal);
           retVals.add(tb);
           System.out.println(test.get(i).noInduk);
       }
       unpaidCicilanHutang = retVal;
       return retVals;
    }
   
    private String getMonthName(int p){
        String ret;
        switch(p){
            case 1: ret = "JULI";
                break;
            case 2: ret = "AGUSTUS";
                break;
            case 3: ret = "SEPTEMBER";
                break;
            case 4: ret = "OKTOBER";
                break;
            case 5: ret = "NOPEMBER";
                break;
            case 6: ret = "DESEMBER";
                break;
            case 7: ret = "JANUARI";
                break;
            case 8: ret = "FEBRUARI";
                break;
            case 9: ret = "MARET";
                break;
            case 10: ret = "APRIL";
                break;
            case 11: ret = "MEI";
                break;
            case 12: ret = "JUNI";
                break;
            default: ret = "Invalid";
                break;
        }
        return ret;
        
    }

    public boolean isCicilanHutangEnough(Set<Long> transactDetailIDs, float amountCicilanHutanginTable) throws SQLException, KasirException {
        Float totalAmountTDetail = 0f;
        for(Long l : transactDetailIDs){
            totalAmountTDetail += Control.selectTDetail(TransactionDetail.Tipe.CicilanHutangTransaction, l).amount;
        }
        if(totalAmountTDetail < amountCicilanHutanginTable){
            return false;
        }else{
            return true;
        }
    }
    
    
    public float calculatePaidCicilanHutang(Set<Long> transactDetailIDs) throws SQLException, KasirException{
        Float retVal = 0f;
        for(Long l: transactDetailIDs){
            retVal += Control.selectTDetail(TransactionDetail.Tipe.CicilanHutangTransaction, l).amount;
        }
        return retVal;
    }
    
}
