/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import iuran.Iuran;
import iuran.Buku;
import iuran.BukuTransactionDetail;
import iuran.TransactionDetail;
import java.awt.Component;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumnModel;
import javax.swing.table.TableModel;
import kasir.Control;
import org.openide.util.Exceptions;
import pelajar.Profil;
import sak.Kalender;
import sak.KasirException;




/**
 *
 * @author Master
 */
public class InputTransactionBuku extends javax.swing.JFrame {
    Profil profil;
    private Buku buku;
    private List<Buku> bukuS;
    private List<Buku> bukuSToDB;
    private float unpaidBuku = 0f;
    private InputTransactionFrameSeparated itfs;
    private TableModel tableModelBuku;
    /**
     * Creates new form InputTransactionBuku
     */
    public InputTransactionBuku(Profil profil, InputTransactionFrameSeparated itfs) {
        this.profil = profil;
        this.itfs = itfs;
        try{
            tableModelBuku = buildBukuTableModel(profil);
        }catch(SQLException ex){
            ex.printStackTrace();
        }catch(KasirException ex){
            ex.printStackTrace();
        }
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelSeragam = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableBuku = new javax.swing.JTable();
        jLabel19 = new javax.swing.JLabel();
        jUnpaidBuku = new javax.swing.JTextField();
        jButtonBayarSeragam = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jPanelSeragam.setMinimumSize(new java.awt.Dimension(440, 550));
        jPanelSeragam.setPreferredSize(new java.awt.Dimension(480, 302));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel10.setText(org.openide.util.NbBundle.getMessage(InputTransactionBuku.class, "InputTransactionBuku.jLabel10.text")); // NOI18N

        try{
            tableModelBuku = buildBukuTableModel(profil);
        }catch(Exception e){
            e.printStackTrace();
        }
        jTableBuku.setModel(tableModelBuku);
        jTableBuku.getColumn("Detail / History").setCellRenderer(new BukuButtonRenderer());
        jTableBuku.getColumn("Detail / History").setCellEditor(
            new BukuButtonEditor(new JCheckBox()));
        jTableBuku.removeColumn(jTableBuku.getColumn("IuranID"));
        jTableBuku.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jTableBukuPropertyChange(evt);
            }
        });
        jScrollPane2.setViewportView(jTableBuku);

        jLabel19.setText(org.openide.util.NbBundle.getMessage(InputTransactionBuku.class, "InputTransactionBuku.jLabel19.text")); // NOI18N

        jUnpaidBuku.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jUnpaidBuku.setText(String.valueOf(unpaidBuku));
        jUnpaidBuku.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jUnpaidBuku.setEnabled(false);

        jButtonBayarSeragam.setText(org.openide.util.NbBundle.getMessage(InputTransactionBuku.class, "InputTransactionBuku.jButtonBayarSeragam.text")); // NOI18N
        jButtonBayarSeragam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBayarSeragamActionPerformed(evt);
            }
        });

        jLabel1.setText(profil.biodata.nama);

        javax.swing.GroupLayout jPanelSeragamLayout = new javax.swing.GroupLayout(jPanelSeragam);
        jPanelSeragam.setLayout(jPanelSeragamLayout);
        jPanelSeragamLayout.setHorizontalGroup(
            jPanelSeragamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSeragamLayout.createSequentialGroup()
                .addGroup(jPanelSeragamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 609, Short.MAX_VALUE)
                    .addGroup(jPanelSeragamLayout.createSequentialGroup()
                        .addGroup(jPanelSeragamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelSeragamLayout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(104, 104, 104)
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jUnpaidBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelSeragamLayout.createSequentialGroup()
                                .addGap(285, 285, 285)
                                .addComponent(jButtonBayarSeragam))
                            .addComponent(jLabel1))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelSeragamLayout.setVerticalGroup(
            jPanelSeragamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSeragamLayout.createSequentialGroup()
                .addGroup(jPanelSeragamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel19)
                    .addComponent(jUnpaidBuku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonBayarSeragam)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelSeragam, javax.swing.GroupLayout.DEFAULT_SIZE, 619, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelSeragam, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTableBukuPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jTableBukuPropertyChange
        // TODO add your handling code here:
        bukuSToDB = new ArrayList<>();
        if (jTableBuku.getRowCount() > 0) {
            for (int i = 0; i < jTableBuku.getRowCount(); i++) {
//                if((Boolean)jTableBuku.getValueAt(i,3) && (bukuS.get(i).transactDetailIDs.size() == 0)){
                if(jTableBuku.getModel().getValueAt(i,5) != null){
                    if((Float)jTableBuku.getModel().getValueAt(i,5) > 0){
                        bukuS.get(i).amount = (Float)jTableBuku.getModel().getValueAt(i,5);
                        bukuSToDB.add(bukuS.get(i));
                    }
                }
                //                    try {
                //buku = Control.selectIuran(Iuran.Tipe.Buku, Buku.noIndukColName, false , profil.noInduk);
                //bukuS.remove(i);
//                    } catch (SQLException ex) {
//                        Exceptions.printStackTrace(ex);
//                    } catch (KasirException ex) {
//                        Exceptions.printStackTrace(ex);
//                    }
//                }
            }
        }
    }//GEN-LAST:event_jTableBukuPropertyChange

    private void jButtonBayarSeragamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBayarSeragamActionPerformed
        // TODO add your handling code here:
        float bukuAmountTemp = 0f;

        for (int i = 0; i < bukuSToDB.size(); i++) {
            if (bukuSToDB.get(i) != null) {

                //bukuAmountTemp = bukuAmountTemp + (Float) jTableBuku.getModel().getValueAt(i, 3);
                bukuAmountTemp = bukuAmountTemp + bukuSToDB.get(i).amount;

            }
        }
        itfs.jTextFieldBukuAmountSimple.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0"))));
        itfs.jTextFieldBukuAmountSimple.setValue(bukuAmountTemp);
        try {
            itfs.jTextFieldBukuAmountSimple.commitEdit();
        } catch (ParseException ex) {
            Exceptions.printStackTrace(ex);
        }
        itfs.bukuSToDB = bukuSToDB;
        itfs.bukuS = bukuS;
        this.setVisible(false);
    }//GEN-LAST:event_jButtonBayarSeragamActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public TableModel buildBukuTableModel(Profil profil) throws SQLException, KasirException{
       String columnNames[] = {"Kelas","Detail / History", "Transaksi Buku", "Biaya", "Sisa", "Pembayaran", "IuranID"};
       Set<Buku> bukuFilters = new HashSet<>();
       bukuFilters.add(new Buku(profil.noInduk,null, null, 0F, null));
       Map<Long, Buku> searchResultMap = new HashMap<>();
       searchResultMap = Control.exactFilterSelectIurans(Iuran.Tipe.Buku, bukuFilters);
       
       Set<Long> transactDetailIDsTemp = new HashSet<Long>();
       int j = 0;
       bukuS = new ArrayList<>();
       ArrayList<Long> bukuSPaid = new ArrayList<Long>();
       ArrayList<String> bukuSTransactionDate = new ArrayList<String>();
       ArrayList<BukuTransactionDetail> stds = new ArrayList<BukuTransactionDetail>();
       if(searchResultMap.size() > 0){
        for(Map.Entry<Long, Buku> entry: searchResultMap.entrySet()){
            transactDetailIDsTemp.clear();
            transactDetailIDsTemp = entry.getValue().transactDetailIDs;
            long paidBuku = 0l;
            String lastTransactionDate = "";
            SimpleDateFormat formatIndo = new SimpleDateFormat("dd-MM-yyyy");
            BukuTransactionDetail std = new BukuTransactionDetail();
            stds.clear();
            for(Long l : transactDetailIDsTemp){
                std = Control.selectTDetail(TransactionDetail.Tipe.BukuTransaction, l);
                paidBuku += std.amount;
                lastTransactionDate = formatIndo.format(std.lastUpdateDate.toDate());
                bukuSTransactionDate.add(lastTransactionDate);
                stds.add(std);
            }
            
            if(entry.getValue().amount > paidBuku){
                bukuS.add(entry.getValue());
                bukuSPaid.add(paidBuku);
            }
            j++;
        }
       }
       Object[][] data = new Object[bukuS.size()][columnNames.length];
       for(int i =0; i < bukuS.size(); i++){
            
            data[i][0]= bukuS.get(i).chargedLevel;
            data[i][1]= "Detail";
            data[i][2]= bukuS.get(i).transactName;
            data[i][3]= bukuS.get(i).amount;
            data[i][4]= bukuS.get(i).amount-bukuSPaid.get(i);
            data[i][5]= 0f;
            data[i][6]= bukuS.get(i).id;
//            if(bukuS.get(i).transactDetailIDs.size()>0){
//                data[i][3] = new Boolean(true);
//            }else{
//                data[i][3] = new Boolean(false);
//            }
       }
       itfs.unpaidBuku = calculateUnpaidBuku(profil);
       if(data.length > 0){
       TableModel tm = new DefaultTableModel(data, columnNames){
           @Override
            public boolean isCellEditable(int row, int column) {
                //all cells false for editable
               if(itfs.jDialogTransactionSummary.isVisible()){
                    return false;
               }else{
                    return true;
               }
            }
            public Class getColumnClass(int c) {
                return getValueAt(0, c).getClass();
            }
       };
       
       return tm;
       }else{
           TableModel tm = new DefaultTableModel(columnNames, columnNames.length);
           return tm;
       }
   }
    
    public TableModel buildBukuSubmitTableModel(Profil profil, List<Buku> stdb) throws SQLException, KasirException{
       String columnNames[] = {"Kelas","Detail / History", "Transaksi Buku", "Biaya", "Sisa", "Pembayaran", "IuranID"};
       
       Set<Buku> bukuFilters = new HashSet<>();
       Set<Long> bukuIDs = new HashSet<>();
       for(int i = 0 ; i < stdb.size(); i++){
           bukuIDs.add(stdb.get(i).id);
       }
       bukuFilters.addAll(stdb);
       Map<Long, Buku> searchResultMap = new HashMap<>();
       //searchResultMap = Control.exactFilterSelectIurans(Iuran.Tipe.Buku, bukuFilters);
       searchResultMap = Control.selectIurans(Iuran.Tipe.Buku, bukuIDs);
       Set<Long> transactDetailIDsTemp = new HashSet<Long>();
       int j = 0;
       long paidBuku = 0l;
       bukuS = new ArrayList<>();  
       ArrayList<Long> bukuSPaid = new ArrayList<Long>();
       ArrayList<Kalender> bukuSTransactionDate = new ArrayList<Kalender>();
       if(searchResultMap.size() > 0){
        for(Map.Entry<Long, Buku> entry: searchResultMap.entrySet()){
            transactDetailIDsTemp.clear();
            transactDetailIDsTemp = entry.getValue().transactDetailIDs;
            paidBuku = 0l;
            Kalender lastTransactionDate = new Kalender();
            BukuTransactionDetail std = new BukuTransactionDetail();
            for(Long l : transactDetailIDsTemp){
                std = Control.selectTDetail(TransactionDetail.Tipe.BukuTransaction, l);
                paidBuku += std.amount;
                lastTransactionDate = std.lastUpdateDate;
                bukuSTransactionDate.add(lastTransactionDate);
            }
            if(transactDetailIDsTemp.isEmpty()){
                bukuSTransactionDate.add(new Kalender());
            }
            
            if(entry.getValue().amount > paidBuku){
                bukuS.add(entry.getValue());
                bukuSPaid.add(paidBuku);
                
            }
            j++;
        }
       }
       Object[][] data = new Object[bukuS.size()][columnNames.length];
       for(int i =0; i < bukuS.size(); i++){
            data[i][0]= bukuS.get(i).chargedLevel;
            data[i][1]= bukuSTransactionDate.get(i);
            data[i][2]= bukuS.get(i).transactName;
            data[i][3] = bukuS.get(i).amount;
            data[i][4] = bukuS.get(i).amount - stdb.get(i).amount - bukuSPaid.get(i);
            data[i][5] = stdb.get(i).amount;
            data[i][6] = bukuS.get(i).id;
            itfs.unpaidBuku = itfs.unpaidBuku - stdb.get(i).amount;
       }
       
      
       if(data.length > 0){
       TableModel tm = new DefaultTableModel(data, columnNames){
           @Override
            public boolean isCellEditable(int row, int column) {
                //all cells false for editable
               if(itfs.jDialogTransactionSummary.isVisible()){
                    return false;
               }else{
                    return true;
               }
            }
            public Class getColumnClass(int c) {
                return getValueAt(0, c).getClass();
            }
       };
       
       return tm;
       }else{
           TableModel tm = new DefaultTableModel(columnNames, columnNames.length);
           return tm;
       }
   }
    
    private float calculateUnpaidBuku(Profil profil) throws SQLException, KasirException {
       float retVal = 0;
       Set<Buku> bukuFilters = new HashSet<>();
       bukuFilters.add(new Buku(profil.noInduk,null, null, 0F, null));
       Map<Long, Buku> searchResultMap = new HashMap<>();
       Set<Long> transactDetailIDsTemp = new HashSet<Long>();
       searchResultMap = Control.exactFilterSelectIurans(Iuran.Tipe.Buku, bukuFilters);
       bukuS = new ArrayList<>();
       
       if(searchResultMap.size() > 0){
        for(Map.Entry<Long, Buku> entry: searchResultMap.entrySet()){
            transactDetailIDsTemp.clear();
            transactDetailIDsTemp = entry.getValue().transactDetailIDs;
            long paidBuku = 0l;
            for(Long l : transactDetailIDsTemp){
                paidBuku += Control.selectTDetail(TransactionDetail.Tipe.BukuTransaction, l).amount;
            }
            
            if(entry.getValue().amount > paidBuku){
                bukuS.add(entry.getValue());
            }
            retVal += entry.getValue().amount - paidBuku;
        }
       }
       unpaidBuku = retVal;
       System.out.println("unpaid Buku");
       System.out.println(unpaidBuku);
       return retVal;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBayarSeragam;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JPanel jPanelSeragam;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableBuku;
    private javax.swing.JTextField jUnpaidBuku;
    // End of variables declaration//GEN-END:variables
}

class BukuButtonRenderer extends JButton implements TableCellRenderer {

  public BukuButtonRenderer() {
    setOpaque(true);
  }

  public Component getTableCellRendererComponent(JTable table, Object value,
      boolean isSelected, boolean hasFocus, int row, int column) {
    if (isSelected) {
      setForeground(table.getSelectionForeground());
      setBackground(table.getSelectionBackground());
    } else {
      setForeground(table.getForeground());
      setBackground(UIManager.getColor("Button.background"));
    }
    setText((value == null) ? "" : value.toString());
    return this;
  }
}

/**
 * @version 1.0 11/09/98
 */

class BukuButtonEditor extends DefaultCellEditor {
  protected JButton button;

  private String label;
  private String detail;
  private boolean isPushed;
  private JTable detailTable;
  private JScrollPane scrollPane;
  private ArrayList<BukuTransactionDetail> stds;
  public BukuButtonEditor(JCheckBox checkBox) {
    super(checkBox);
    button = new JButton();
    button.setOpaque(true);
    button.addActionListener(new ActionListener() {
      public void actionPerformed(ActionEvent e) {
        fireEditingStopped();
      }
    });
  }

  public Component getTableCellEditorComponent(JTable table, Object value,
      boolean isSelected, int row, int column) {
    if (isSelected) {
      button.setForeground(table.getSelectionForeground());
      button.setBackground(table.getSelectionBackground());
    } else {
      button.setForeground(table.getForeground());
      button.setBackground(table.getBackground());
    }
    SimpleDateFormat formatIndo = new SimpleDateFormat("dd-MM-yyyy hh:mm:ss");
    Set<Long> transactDetailIDsTemp = new HashSet<Long>();
    Buku s;
    Long bukuID = (Long)table.getModel().getValueAt(row, 6);
    try {
        s = Control.selectIuran(Iuran.Tipe.Buku, bukuID);
        transactDetailIDsTemp = s.transactDetailIDs;
    } catch (SQLException ex) {
        Exceptions.printStackTrace(ex);
    } catch (KasirException ex) {
        Exceptions.printStackTrace(ex);
    }
    BukuTransactionDetail std = new BukuTransactionDetail();
    detail = "";
    
    String columnNames[] = {"No", "Tanggal", "Pembayaran"};
    Object[][] data = new Object[transactDetailIDsTemp.size()][columnNames.length];
    int i = 0;
    for(Long l : transactDetailIDsTemp){
            try {
                std = Control.selectTDetail(TransactionDetail.Tipe.BukuTransaction, l);
            } catch (SQLException ex) {
                Exceptions.printStackTrace(ex);
            } catch (KasirException ex) {
                Exceptions.printStackTrace(ex);
            }
            
            detail += String.valueOf(i);
            detail += ". Rp ";
            detail += String.valueOf(std.amount);
            detail += "\t";
            detail += formatIndo.format(std.lastUpdateDate.toDate());
            detail += "\r\n";
            
            data[i][0] = i+1;
            data[i][1] = formatIndo.format(std.lastUpdateDate.toDate());
            data[i][2] = "Rp ".concat(String.valueOf((Float)std.amount));
            i++;
    }
    
    TableModel tm = new DefaultTableModel(data, columnNames){
           @Override
            public boolean isCellEditable(int row, int column) {
                //all cells false for editable
               return false;
            }
            public Class getColumnClass(int c) {
                return getValueAt(0, c).getClass();
            }
       };
    
    detailTable = new JTable(tm){
        public Class getColumnClass(int c){
            return getValueAt(0, c).getClass();
        }
    };
    
    
    scrollPane = new JScrollPane(detailTable);
    
    
    label = (value == null) ? "" : value.toString();
    
    button.setText(label);
    isPushed = true;
    return button;
  }

  public Object getCellEditorValue() {
    if (isPushed) {
      // 
      // 
      JOptionPane.showMessageDialog(button, scrollPane, "Buku", JOptionPane.INFORMATION_MESSAGE);
      
      // System.out.println(label + ": Ouch!");
    }
    isPushed = false;
    return new String(label);
  }

  public boolean stopCellEditing() {
    isPushed = false;
    return super.stopCellEditing();
  }

  protected void fireEditingStopped() {
    super.fireEditingStopped();
  }
}
