/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import com.lowagie.rups.view.models.JTableAutoModel;
import iuran.*;
import iuran.Iuran;
import iuran.Seragam;
import java.awt.Component;
import java.sql.SQLException;
import java.util.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.text.BadLocationException;
import kasir.Clerk;
import kasir.Control;
import org.netbeans.validation.api.Validator;
import org.netbeans.validation.api.ValidatorUtils;
import org.netbeans.validation.api.ui.swing.ValidationPanel;
import org.netbeans.validation.api.builtin.stringvalidation.StringValidators;
import org.openide.util.Exceptions;
import pelajar.Biodata;
import pelajar.Level;
import pelajar.Profil;
import sak.KasirException;

/**
 *
 * @author Master
 */
public class InputProfilFrame extends javax.swing.JFrame {
    private final ValidationPanel panelPrivate = new ValidationPanel();
    private Clerk clerk;
    private Profil profil;
    private ArrayList<Profil> profilList;
    private TableModel profilsTableModel = new DefaultTableModel();
    /**
     * Creates new form UpdateProfilFrame
     */
    public InputProfilFrame() {
        initComponents();
    }
    
    public InputProfilFrame(Clerk clerk){
        this.clerk = clerk;
        this.profil = null;
        initComponents();
    }
    
    public InputProfilFrame(Clerk clerk, Profil profil){
        this.clerk = clerk;
        this.profil = profil;
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jDialogInputSiswa = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        jNomorIndukTextField1 = new javax.swing.JTextField();
        jNomorIndukLabel1 = new javax.swing.JLabel();
        jNamaLabel1 = new javax.swing.JLabel();
        jNamaTextField1 = new javax.swing.JTextField();
        jJenisKelaminLabel1 = new javax.swing.JLabel();
        jJenisKelaminComboBox1 = new javax.swing.JComboBox();
        jTanggalLahirLabel1 = new javax.swing.JLabel();
        jTempatLahirLabel1 = new javax.swing.JLabel();
        jAlamatLabel1 = new javax.swing.JLabel();
        jTempatLahirTextField1 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jAlamatTextArea1 = new javax.swing.JTextArea();
        jNamaAyahLabel1 = new javax.swing.JLabel();
        jNamaAyahTextField1 = new javax.swing.JTextField();
        jNamaIbuLabel1 = new javax.swing.JLabel();
        jNamaIbuTextField1 = new javax.swing.JTextField();
        jTelepon1Label1 = new javax.swing.JLabel();
        jTelepon1TextField1 = new javax.swing.JTextField();
        jTelepon2Label1 = new javax.swing.JLabel();
        jTelepon2TextField1 = new javax.swing.JTextField();
        jTanggalMasuk1 = new javax.swing.JLabel();
        dateChooserComboTanggalMasuk1 = new datechooser.beans.DateChooserCombo();
        jButtonSave1 = new javax.swing.JButton();
        jButtonCancel1 = new javax.swing.JButton();
        dateChooserComboTanggalLahir1 = new datechooser.beans.DateChooserCombo();
        jTingkatSekolah1 = new javax.swing.JLabel();
        jComboBoxTingkatSekolah1 = new javax.swing.JComboBox();
        jTingkatKelas1 = new javax.swing.JLabel();
        jTingkatSubKelas1 = new javax.swing.JLabel();
        jComboBoxTingkatKelas1 = new javax.swing.JComboBox();
        jComboBoxTingkatSubKelas1 = new javax.swing.JComboBox();
        jAgamaLabel1 = new javax.swing.JLabel();
        jAgamaComboBox1 = new javax.swing.JComboBox();
        jAsalSekolahTextField1 = new javax.swing.JTextField();
        jAsalSekolahLabel1 = new javax.swing.JLabel();
        jTitleLabel1 = new javax.swing.JLabel();
        jDialogListInputSiswa = new javax.swing.JFrame();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButtonSaveProfils = new javax.swing.JButton();
        jButtonClearProfils = new javax.swing.JButton();
        Level level = new Level();
        Biodata biodata = new Biodata();
        DefaultComboBoxModel kelaminComboBoxModel = new DefaultComboBoxModel(biodata.kelamin.values());
        DefaultComboBoxModel agamaComboBoxModel = new DefaultComboBoxModel(biodata.agama.values());
        DefaultComboBoxModel level1ComboBoxModel = new DefaultComboBoxModel(level.level1.values());
        DefaultComboBoxModel level2ComboBoxModel = new DefaultComboBoxModel(level.level2.values());
        DefaultComboBoxModel level3ComboBoxModel = new DefaultComboBoxModel(level.level3.values());
        profilList= new ArrayList<>();
        jPanel2 = new javax.swing.JPanel();
        jNomorIndukTextField = new javax.swing.JTextField();
        jNomorIndukLabel = new javax.swing.JLabel();
        jNamaLabel = new javax.swing.JLabel();
        jNamaTextField = new javax.swing.JTextField();
        jJenisKelaminLabel = new javax.swing.JLabel();
        jJenisKelaminComboBox = new javax.swing.JComboBox();
        jTanggalLahirLabel = new javax.swing.JLabel();
        jTempatLahirLabel = new javax.swing.JLabel();
        jAlamatLabel = new javax.swing.JLabel();
        jTempatLahirTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jAlamatTextArea = new javax.swing.JTextArea();
        jNamaAyahLabel = new javax.swing.JLabel();
        jNamaAyahTextField = new javax.swing.JTextField();
        jNamaIbuLabel = new javax.swing.JLabel();
        jNamaIbuTextField = new javax.swing.JTextField();
        jTelepon1Label = new javax.swing.JLabel();
        jTelepon1TextField = new javax.swing.JTextField();
        jTelepon2Label = new javax.swing.JLabel();
        jTelepon2TextField = new javax.swing.JTextField();
        jTanggalMasuk = new javax.swing.JLabel();
        dateChooserComboTanggalMasuk = new datechooser.beans.DateChooserCombo();
        dateChooserComboTanggalLahir = new datechooser.beans.DateChooserCombo();
        jButtonSave = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();
        jTanggalMasuk2 = new javax.swing.JLabel();
        jTanggalMasuk3 = new javax.swing.JLabel();
        jComboBoxTingkatSekolah = new javax.swing.JComboBox();
        jComboBoxTingkatKelas = new javax.swing.JComboBox();
        jTanggalMasuk4 = new javax.swing.JLabel();
        jComboBoxTingkatSubKelas = new javax.swing.JComboBox();
        jTitleLabel = new javax.swing.JLabel();
        jCheckBoxInsertProfils = new javax.swing.JCheckBox();
        jAgamaLabel = new javax.swing.JLabel();
        jAgamaComboBox = new javax.swing.JComboBox();
        jAsalSekolahLabel = new javax.swing.JLabel();
        jAsalSekolahTextField = new javax.swing.JTextField();

        jDialogInputSiswa.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jDialogInputSiswa.setTitle("Konfirmasi Input Siswa");
        jDialogInputSiswa.setMinimumSize(new java.awt.Dimension(437, 800));

        jPanel3.setMaximumSize(new java.awt.Dimension(700, 800));
        jPanel3.setMinimumSize(new java.awt.Dimension(447, 530));
        jPanel3.setName("Konfirmasi Input Siswa"); // NOI18N
        jPanel3.setPreferredSize(new java.awt.Dimension(447, 580));
        jPanel3.setRequestFocusEnabled(false);

        jNomorIndukTextField1.setEditable(false);
        jNomorIndukTextField1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jNomorIndukTextField, org.jdesktop.beansbinding.ELProperty.create("${text}"), jNomorIndukTextField1, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        jNomorIndukTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNomorIndukTextField1ActionPerformed(evt);
            }
        });

        jNomorIndukLabel1.setText("Nomor Induk");

        jNamaLabel1.setText("Nama");

        jNamaTextField1.setEditable(false);
        jNamaTextField1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jNamaTextField, org.jdesktop.beansbinding.ELProperty.create("${text}"), jNamaTextField1, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        jNamaTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNamaTextField1ActionPerformed(evt);
            }
        });

        jJenisKelaminLabel1.setText("Jenis Kelamin");

        jJenisKelaminComboBox1.setModel(kelaminComboBoxModel);
        jJenisKelaminComboBox1.setEnabled(false);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jJenisKelaminComboBox, org.jdesktop.beansbinding.ELProperty.create("${selectedItem}"), jJenisKelaminComboBox1, org.jdesktop.beansbinding.BeanProperty.create("selectedItem"));
        bindingGroup.addBinding(binding);

        jJenisKelaminComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jJenisKelaminComboBox1ActionPerformed(evt);
            }
        });

        jTanggalLahirLabel1.setText("Tanggal Lahir");

        jTempatLahirLabel1.setText("Tempat Lahir");

        jAlamatLabel1.setText("Alamat");

        jTempatLahirTextField1.setEditable(false);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jTempatLahirTextField, org.jdesktop.beansbinding.ELProperty.create("${text}"), jTempatLahirTextField1, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        jAlamatTextArea1.setEditable(false);
        jAlamatTextArea1.setColumns(20);
        jAlamatTextArea1.setRows(5);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jAlamatTextArea, org.jdesktop.beansbinding.ELProperty.create("${text}"), jAlamatTextArea1, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        jScrollPane2.setViewportView(jAlamatTextArea1);

        jNamaAyahLabel1.setText("Nama Ayah");

        jNamaAyahTextField1.setEditable(false);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jNamaAyahTextField, org.jdesktop.beansbinding.ELProperty.create("${text}"), jNamaAyahTextField1, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        jNamaIbuLabel1.setText("Nama Ibu");

        jNamaIbuTextField1.setEditable(false);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jNamaIbuTextField, org.jdesktop.beansbinding.ELProperty.create("${text}"), jNamaIbuTextField1, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        jNamaIbuTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNamaIbuTextField1ActionPerformed(evt);
            }
        });

        jTelepon1Label1.setText("Telepon 1");

        jTelepon1TextField1.setEditable(false);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jTelepon1TextField, org.jdesktop.beansbinding.ELProperty.create("${text}"), jTelepon1TextField1, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        jTelepon1TextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTelepon1TextField1ActionPerformed(evt);
            }
        });

        jTelepon2Label1.setText("Telepon 2");

        jTelepon2TextField1.setEditable(false);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jTelepon2TextField, org.jdesktop.beansbinding.ELProperty.create("${text}"), jTelepon2TextField1, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        jTelepon2TextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTelepon2TextField1ActionPerformed(evt);
            }
        });

        jTanggalMasuk1.setText("Tanggal Masuk");

        dateChooserComboTanggalMasuk1.setNothingAllowed(false);

        jButtonSave1.setText("Save");
        jButtonSave1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSave1ActionPerformed(evt);
            }
        });

        jButtonCancel1.setText("Back");
        jButtonCancel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancel1ActionPerformed(evt);
            }
        });

        dateChooserComboTanggalLahir1.setNothingAllowed(false);

        jTingkatSekolah1.setText("Tingkat Sekolah");

        jComboBoxTingkatSekolah1.setModel(level1ComboBoxModel);
        jComboBoxTingkatSekolah1.setEnabled(false);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jComboBoxTingkatSekolah, org.jdesktop.beansbinding.ELProperty.create("${selectedItem}"), jComboBoxTingkatSekolah1, org.jdesktop.beansbinding.BeanProperty.create("selectedItem"));
        bindingGroup.addBinding(binding);

        jTingkatKelas1.setText("Tingkat Kelas");

        jTingkatSubKelas1.setText("Tingkat Sub Kelas");

        jComboBoxTingkatKelas1.setModel(level2ComboBoxModel);
        jComboBoxTingkatKelas1.setEnabled(false);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jComboBoxTingkatKelas, org.jdesktop.beansbinding.ELProperty.create("${selectedItem}"), jComboBoxTingkatKelas1, org.jdesktop.beansbinding.BeanProperty.create("selectedItem"));
        bindingGroup.addBinding(binding);

        jComboBoxTingkatSubKelas1.setModel(level3ComboBoxModel);
        jComboBoxTingkatSubKelas1.setEnabled(false);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jComboBoxTingkatSubKelas, org.jdesktop.beansbinding.ELProperty.create("${selectedItem}"), jComboBoxTingkatSubKelas1, org.jdesktop.beansbinding.BeanProperty.create("selectedItem"));
        bindingGroup.addBinding(binding);

        jAgamaLabel1.setText("Agama");

        jAgamaComboBox1.setModel(agamaComboBoxModel);
        jAgamaComboBox1.setEnabled(false);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jAgamaComboBox, org.jdesktop.beansbinding.ELProperty.create("${selectedItem}"), jAgamaComboBox1, org.jdesktop.beansbinding.BeanProperty.create("selectedItem"));
        bindingGroup.addBinding(binding);

        jAgamaComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAgamaComboBox1ActionPerformed(evt);
            }
        });

        jAsalSekolahTextField1.setEditable(false);
        jAsalSekolahTextField1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jAsalSekolahTextField, org.jdesktop.beansbinding.ELProperty.create("${text}"), jAsalSekolahTextField1, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        jAsalSekolahTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAsalSekolahTextField1ActionPerformed(evt);
            }
        });

        jAsalSekolahLabel1.setText("Asal Sekolah");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jNomorIndukLabel1)
                            .addComponent(jNamaLabel1)
                            .addComponent(jJenisKelaminLabel1))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addComponent(jButtonSave1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonCancel1))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jNamaTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jNomorIndukTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jJenisKelaminComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jAgamaComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTanggalLahirLabel1)
                            .addComponent(jTempatLahirLabel1)
                            .addComponent(jAlamatLabel1)
                            .addComponent(jNamaAyahLabel1)
                            .addComponent(jNamaIbuLabel1)
                            .addComponent(jTelepon1Label1)
                            .addComponent(jTelepon2Label1)
                            .addComponent(jTanggalMasuk1)
                            .addComponent(jTingkatSekolah1)
                            .addComponent(jTingkatKelas1)
                            .addComponent(jTingkatSubKelas1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBoxTingkatSekolah1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBoxTingkatKelas1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dateChooserComboTanggalMasuk1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTelepon2TextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTelepon1TextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTempatLahirTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jNamaAyahTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jNamaIbuTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dateChooserComboTanggalLahir1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBoxTingkatSubKelas1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jAsalSekolahTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(jAgamaLabel1)
                    .addComponent(jAsalSekolahLabel1))
                .addContainerGap(128, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jNomorIndukTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jNomorIndukLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jNamaLabel1)
                    .addComponent(jNamaTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jJenisKelaminLabel1)
                    .addComponent(jJenisKelaminComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jAgamaLabel1)
                    .addComponent(jAgamaComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jAsalSekolahLabel1)
                    .addComponent(jAsalSekolahTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTanggalLahirLabel1)
                    .addComponent(dateChooserComboTanggalLahir1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTempatLahirLabel1)
                    .addComponent(jTempatLahirTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jAlamatLabel1)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jNamaAyahLabel1)
                    .addComponent(jNamaAyahTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jNamaIbuLabel1)
                    .addComponent(jNamaIbuTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTelepon1Label1)
                    .addComponent(jTelepon1TextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTelepon2Label1)
                    .addComponent(jTelepon2TextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTanggalMasuk1)
                    .addComponent(dateChooserComboTanggalMasuk1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTingkatSekolah1)
                    .addComponent(jComboBoxTingkatSekolah1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTingkatKelas1)
                    .addComponent(jComboBoxTingkatKelas1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTingkatSubKelas1)
                    .addComponent(jComboBoxTingkatSubKelas1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSave1)
                    .addComponent(jButtonCancel1))
                .addGap(20, 20, 20))
        );

        dateChooserComboTanggalMasuk1.setSelectedDate(dateChooserComboTanggalMasuk.getSelectedDate());
        dateChooserComboTanggalMasuk1.setCurrent(dateChooserComboTanggalMasuk.getSelectedDate());
        dateChooserComboTanggalLahir1.setSelectedDate(dateChooserComboTanggalLahir.getSelectedDate());
        dateChooserComboTanggalLahir1.setCurrent(dateChooserComboTanggalLahir.getSelectedDate());

        jTitleLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTitleLabel1.setText("Konfirmasi Input Siswa");

        javax.swing.GroupLayout jDialogInputSiswaLayout = new javax.swing.GroupLayout(jDialogInputSiswa.getContentPane());
        jDialogInputSiswa.getContentPane().setLayout(jDialogInputSiswaLayout);
        jDialogInputSiswaLayout.setHorizontalGroup(
            jDialogInputSiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogInputSiswaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDialogInputSiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTitleLabel1)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jDialogInputSiswaLayout.setVerticalGroup(
            jDialogInputSiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogInputSiswaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTitleLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jDialogListInputSiswa.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jDialogListInputSiswa.setMinimumSize(new java.awt.Dimension(1024, 768));

        jScrollPane3.setPreferredSize(new java.awt.Dimension(1024, 275));

        jTable1.setModel(profilsTableModel);
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jTable1.setDoubleBuffered(true);
        jScrollPane3.setViewportView(jTable1);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Daftar Siswa (Multiple)");

        jButtonSaveProfils.setText("Save All");
        jButtonSaveProfils.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveProfilsActionPerformed(evt);
            }
        });

        jButtonClearProfils.setText("Clear All");
        jButtonClearProfils.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClearProfilsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDialogListInputSiswaLayout = new javax.swing.GroupLayout(jDialogListInputSiswa.getContentPane());
        jDialogListInputSiswa.getContentPane().setLayout(jDialogListInputSiswaLayout);
        jDialogListInputSiswaLayout.setHorizontalGroup(
            jDialogListInputSiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogListInputSiswaLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jDialogListInputSiswaLayout.createSequentialGroup()
                .addGap(176, 176, 176)
                .addComponent(jButtonSaveProfils)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonClearProfils)
                .addContainerGap(700, Short.MAX_VALUE))
            .addGroup(jDialogListInputSiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jDialogListInputSiswaLayout.setVerticalGroup(
            jDialogListInputSiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogListInputSiswaLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 667, Short.MAX_VALUE)
                .addGroup(jDialogListInputSiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSaveProfils)
                    .addComponent(jButtonClearProfils))
                .addGap(32, 32, 32))
            .addGroup(jDialogListInputSiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jDialogListInputSiswaLayout.createSequentialGroup()
                    .addGap(63, 63, 63)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(441, Short.MAX_VALUE)))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Input Siswa");

        jNomorIndukTextField.setName("Nomor Induk"); // NOI18N
        jNomorIndukTextField.setText(profil!= null ? profil.noInduk:"");
        jNomorIndukTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNomorIndukTextFieldActionPerformed(evt);
            }
        });
        jNomorIndukTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jNomorIndukTextFieldKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jNomorIndukTextFieldKeyTyped(evt);
            }
        });

        jNomorIndukLabel.setText("Nomor Induk");

        jNamaLabel.setText("Nama");

        jNamaTextField.setName("Nama"); // NOI18N
        jNamaTextField.setText(profil!=null?profil.biodata.nama:"");
        jNamaTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNamaTextFieldActionPerformed(evt);
            }
        });
        jNamaTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jNamaTextFieldKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jNamaTextFieldKeyTyped(evt);
            }
        });

        jJenisKelaminLabel.setText("Jenis Kelamin");

        jJenisKelaminComboBox.setModel(kelaminComboBoxModel);
        jJenisKelaminComboBox.setSelectedItem(profil!=null?profil.biodata.kelamin: Biodata.Kelamin.L);
        jJenisKelaminComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jJenisKelaminComboBoxActionPerformed(evt);
            }
        });

        jTanggalLahirLabel.setText("Tanggal Lahir");

        jTempatLahirLabel.setText("Tempat Lahir");

        jAlamatLabel.setText("Alamat");

        jTempatLahirTextField.setName("Tempat Lahir"); // NOI18N
        jTempatLahirTextField.setText(profil!=null?profil.biodata.tempatLahir:"");
        jTempatLahirTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTempatLahirTextFieldKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTempatLahirTextFieldKeyTyped(evt);
            }
        });

        jAlamatTextArea.setColumns(20);
        jAlamatTextArea.setRows(5);
        jAlamatTextArea.setName("Alamat"); // NOI18N
        jAlamatTextArea.setText(profil!=null?profil.biodata.alamat:"");
        jAlamatTextArea.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jAlamatTextAreaKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jAlamatTextAreaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jAlamatTextAreaKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(jAlamatTextArea);

        jNamaAyahLabel.setText("Nama Ayah");

        jNamaAyahTextField.setName("Nama Ayah"); // NOI18N
        jNamaAyahTextField.setText(profil!=null?profil.biodata.namaAyah:"");
        jNamaAyahTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNamaAyahTextFieldActionPerformed(evt);
            }
        });

        jNamaIbuLabel.setText("Nama Ibu");

        jNamaIbuTextField.setName("Nama Ibu\n"); // NOI18N
        jNamaIbuTextField.setText(profil!=null?profil.biodata.namaIbu:"");
        jNamaIbuTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNamaIbuTextFieldActionPerformed(evt);
            }
        });

        jTelepon1Label.setText("Telepon 1");

        jTelepon1TextField.setName("Telepon 1"); // NOI18N
        jTelepon1TextField.setText(profil!=null?profil.biodata.telpon1:"");
        jTelepon1TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTelepon1TextFieldActionPerformed(evt);
            }
        });
        jTelepon1TextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTelepon1TextFieldKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTelepon1TextFieldKeyTyped(evt);
            }
        });

        jTelepon2Label.setText("Telepon 2");

        jTelepon2TextField.setName("Telepon 2"); // NOI18N
        jTelepon2TextField.setText(profil!=null?profil.biodata.telpon2:"");
        jTelepon2TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTelepon2TextFieldActionPerformed(evt);
            }
        });

        jTanggalMasuk.setText("Tanggal Masuk");

        dateChooserComboTanggalMasuk.setNothingAllowed(false);
        try {
            dateChooserComboTanggalMasuk.setDefaultPeriods(new datechooser.model.multiple.PeriodSet(new datechooser.model.multiple.Period(new java.util.GregorianCalendar(2013, 9, 25),
                new java.util.GregorianCalendar(2013, 9, 25))));
    } catch (datechooser.model.exeptions.IncompatibleDataExeption e1) {
        e1.printStackTrace();
    }
    dateChooserComboTanggalMasuk.setLocale(new java.util.Locale("en", "GB", ""));
    dateChooserComboTanggalMasuk.setBehavior(datechooser.model.multiple.MultyModelBehavior.SELECT_SINGLE);
    dateChooserComboTanggalMasuk.setSelectedDate(profil!=null?profil.tanggalMasuk:Calendar.getInstance());
    dateChooserComboTanggalMasuk.addCommitListener(new datechooser.events.CommitListener() {
        public void onCommit(datechooser.events.CommitEvent evt) {
            dateChooserComboTanggalMasukOnCommit(evt);
        }
    });
    dateChooserComboTanggalMasuk.addSelectionChangedListener(new datechooser.events.SelectionChangedListener() {
        public void onSelectionChange(datechooser.events.SelectionChangedEvent evt) {
            dateChooserComboTanggalMasukOnSelectionChange(evt);
        }
    });

    dateChooserComboTanggalLahir.setNothingAllowed(false);
    try {
        dateChooserComboTanggalLahir.setDefaultPeriods(new datechooser.model.multiple.PeriodSet(new datechooser.model.multiple.Period(new java.util.GregorianCalendar(2013, 9, 25),
            new java.util.GregorianCalendar(2013, 9, 25))));
} catch (datechooser.model.exeptions.IncompatibleDataExeption e1) {
    e1.printStackTrace();
    }
    dateChooserComboTanggalLahir.setLocale(new java.util.Locale("en", "GB", ""));
    dateChooserComboTanggalLahir.setBehavior(datechooser.model.multiple.MultyModelBehavior.SELECT_SINGLE);
    dateChooserComboTanggalLahir.setSelectedDate(profil!=null?profil.biodata.tanggalLahir: Calendar.getInstance());
    dateChooserComboTanggalLahir.addCommitListener(new datechooser.events.CommitListener() {
        public void onCommit(datechooser.events.CommitEvent evt) {
            dateChooserComboTanggalLahirOnCommit(evt);
        }
    });
    dateChooserComboTanggalLahir.addSelectionChangedListener(new datechooser.events.SelectionChangedListener() {
        public void onSelectionChange(datechooser.events.SelectionChangedEvent evt) {
            dateChooserComboTanggalLahirOnSelectionChange(evt);
        }
    });

    jButtonSave.setText("Save");
    jButtonSave.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButtonSaveActionPerformed(evt);
        }
    });

    jButtonCancel.setText("Cancel");
    jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButtonCancelActionPerformed(evt);
        }
    });

    jTanggalMasuk2.setText("Tingkat Sekolah");

    jTanggalMasuk3.setText("Tingkat Kelas");

    jComboBoxTingkatSekolah.setModel(level1ComboBoxModel);
    jComboBoxTingkatSekolah.setSelectedItem(profil!=null?profil.currentLevel.level1:Level.Level1.SMP);
    jComboBoxTingkatSekolah.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jComboBoxTingkatSekolahActionPerformed(evt);
        }
    });

    jComboBoxTingkatKelas.setModel(level2ComboBoxModel);
    jComboBoxTingkatKelas.setSelectedItem(profil!=null?profil.currentLevel.level2:Level.Level2.TUJUH);

    jTanggalMasuk4.setText("Tingkat Sub Kelas");

    jComboBoxTingkatSubKelas.setModel(level3ComboBoxModel);
    jComboBoxTingkatSubKelas.setSelectedItem(profil!=null?profil.currentLevel.level3: Level.Level3.SATU);

    jTitleLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    jTitleLabel.setText("Input Siswa");

    jCheckBoxInsertProfils.setText("Multiple Insert");
    jCheckBoxInsertProfils.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jCheckBoxInsertProfilsActionPerformed(evt);
        }
    });

    jAgamaLabel.setText("Agama");

    jAgamaComboBox.setModel(agamaComboBoxModel);
    jAgamaComboBox.setSelectedItem(profil!=null?profil.biodata.agama: Biodata.Agama.ISLAM);
    jAgamaComboBox.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jAgamaComboBoxActionPerformed(evt);
        }
    });

    jAsalSekolahLabel.setText("Asal Sekolah");

    jAsalSekolahTextField.setName("AsalSekolah"); // NOI18N
    jAsalSekolahTextField.setText(profil!=null?profil.biodata.asalSekolah:"");
    jAsalSekolahTextField.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jAsalSekolahTextFieldActionPerformed(evt);
        }
    });
    jAsalSekolahTextField.addKeyListener(new java.awt.event.KeyAdapter() {
        public void keyReleased(java.awt.event.KeyEvent evt) {
            jAsalSekolahTextFieldKeyReleased(evt);
        }
        public void keyTyped(java.awt.event.KeyEvent evt) {
            jAsalSekolahTextFieldKeyTyped(evt);
        }
    });

    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
    jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(
        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel2Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jNomorIndukLabel)
                        .addComponent(jNamaLabel)
                        .addComponent(jJenisKelaminLabel))
                    .addGap(21, 21, 21)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(23, 23, 23)
                            .addComponent(jButtonSave)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButtonCancel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                            .addComponent(jCheckBoxInsertProfils))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(19, 19, 19)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jNamaTextField)
                                .addComponent(jNomorIndukTextField)
                                .addComponent(jJenisKelaminComboBox, 0, 215, Short.MAX_VALUE)
                                .addComponent(jAgamaComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(0, 0, Short.MAX_VALUE))))
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jTitleLabel)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTanggalLahirLabel)
                                .addComponent(jTempatLahirLabel)
                                .addComponent(jAlamatLabel)
                                .addComponent(jNamaAyahLabel)
                                .addComponent(jNamaIbuLabel)
                                .addComponent(jTelepon1Label)
                                .addComponent(jTelepon2Label)
                                .addComponent(jTanggalMasuk)
                                .addComponent(jTanggalMasuk4)
                                .addComponent(jTanggalMasuk2)
                                .addComponent(jTanggalMasuk3))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(1, 1, 1)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jTelepon2TextField)
                                        .addComponent(jTelepon1TextField)
                                        .addComponent(jTempatLahirTextField)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                                        .addComponent(jNamaAyahTextField)
                                        .addComponent(jNamaIbuTextField)
                                        .addComponent(dateChooserComboTanggalLahir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(dateChooserComboTanggalMasuk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addComponent(jComboBoxTingkatKelas, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jComboBoxTingkatSekolah, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jComboBoxTingkatSubKelas, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(jAgamaLabel)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jAsalSekolahLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                            .addComponent(jAsalSekolahTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addContainerGap())
    );
    jPanel2Layout.setVerticalGroup(
        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel2Layout.createSequentialGroup()
            .addComponent(jTitleLabel)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jNomorIndukTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jNomorIndukLabel))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jNamaLabel)
                .addComponent(jNamaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jJenisKelaminLabel)
                .addComponent(jJenisKelaminComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jAgamaLabel)
                .addComponent(jAgamaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(3, 3, 3)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jAsalSekolahLabel)
                .addComponent(jAsalSekolahTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addComponent(jTanggalLahirLabel)
                .addComponent(dateChooserComboTanggalLahir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jTempatLahirLabel)
                .addComponent(jTempatLahirTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jAlamatLabel)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(7, 7, 7)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jNamaAyahLabel)
                .addComponent(jNamaAyahTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jNamaIbuLabel)
                .addComponent(jNamaIbuTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jTelepon1Label)
                .addComponent(jTelepon1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jTelepon2Label)
                .addComponent(jTelepon2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addComponent(jTanggalMasuk)
                .addComponent(dateChooserComboTanggalMasuk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jTanggalMasuk2)
                .addComponent(jComboBoxTingkatSekolah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jTanggalMasuk3)
                .addComponent(jComboBoxTingkatKelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jTanggalMasuk4)
                .addComponent(jComboBoxTingkatSubKelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(37, 37, 37)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jButtonSave)
                .addComponent(jButtonCancel)
                .addComponent(jCheckBoxInsertProfils)))
    );

    dateChooserComboTanggalMasuk.setCurrent(Calendar.getInstance());
    dateChooserComboTanggalLahir.setCurrent(Calendar.getInstance());

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(20, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addContainerGap())
    );

    setContentPane(panelPrivate);
    panelPrivate.setInnerComponent(jPanel2);
    Validator<String> d = StringValidators.trimString(ValidatorUtils.merge(
        StringValidators.REQUIRE_NON_EMPTY_STRING,
        StringValidators.NO_WHITESPACE));
panelPrivate.getValidationGroup().add(jNomorIndukTextField, d);
d = StringValidators.trimString(ValidatorUtils.merge(
    StringValidators.REQUIRE_NON_EMPTY_STRING));
    panelPrivate.getValidationGroup().add(jNamaTextField, d);
    panelPrivate.getValidationGroup().add(jTempatLahirTextField, d);
    panelPrivate.getValidationGroup().add(jAlamatTextArea, d);

    d = StringValidators.trimString(ValidatorUtils.merge(StringValidators.validNumber(Locale.US)));
    panelPrivate.getValidationGroup().add(jTelepon1TextField, d);
    jButtonSave.setEnabled(validatePanel());

    bindingGroup.bind();

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jNomorIndukTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNomorIndukTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jNomorIndukTextFieldActionPerformed

    private void jNamaTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNamaTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jNamaTextFieldActionPerformed

    private void jJenisKelaminComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jJenisKelaminComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jJenisKelaminComboBoxActionPerformed

    private void jNamaIbuTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNamaIbuTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jNamaIbuTextFieldActionPerformed

    private void jTelepon1TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTelepon1TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTelepon1TextFieldActionPerformed

    private void jTelepon2TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTelepon2TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTelepon2TextFieldActionPerformed

    private void dateChooserComboTanggalLahirOnSelectionChange(datechooser.events.SelectionChangedEvent evt) {//GEN-FIRST:event_dateChooserComboTanggalLahirOnSelectionChange
        dateChooserComboTanggalLahir1.setSelectedDate(dateChooserComboTanggalLahir.getSelectedDate());
        
    }//GEN-LAST:event_dateChooserComboTanggalLahirOnSelectionChange

    private void dateChooserComboTanggalLahirOnCommit(datechooser.events.CommitEvent evt) {//GEN-FIRST:event_dateChooserComboTanggalLahirOnCommit
        // TODO add your handling code here:
    }//GEN-LAST:event_dateChooserComboTanggalLahirOnCommit

    private void dateChooserComboTanggalMasukOnSelectionChange(datechooser.events.SelectionChangedEvent evt) {//GEN-FIRST:event_dateChooserComboTanggalMasukOnSelectionChange
        // TODO add your handling code here:
        dateChooserComboTanggalMasuk1.setSelectedDate(dateChooserComboTanggalMasuk.getSelectedDate());
    }//GEN-LAST:event_dateChooserComboTanggalMasukOnSelectionChange

    private void dateChooserComboTanggalMasukOnCommit(datechooser.events.CommitEvent evt) {//GEN-FIRST:event_dateChooserComboTanggalMasukOnCommit
        // TODO add your handling code here:
    }//GEN-LAST:event_dateChooserComboTanggalMasukOnCommit

    private void jButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveActionPerformed
        // TODO add your handling code here:
        if(jCheckBoxInsertProfils.isSelected()){
            
            continueToListDisplayDialog();
        }else{
            continueToConfirmationDialog();
        }
    }//GEN-LAST:event_jButtonSaveActionPerformed

    private void jTelepon1TextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTelepon1TextFieldKeyTyped
        // TODO add your handling code here:
        jButtonSave.setEnabled(validatePanel());
    }//GEN-LAST:event_jTelepon1TextFieldKeyTyped

    private void jNomorIndukTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jNomorIndukTextFieldKeyTyped
        // TODO add your handling code here:
        jButtonSave.setEnabled(validatePanel());
    }//GEN-LAST:event_jNomorIndukTextFieldKeyTyped

    private void jNamaTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jNamaTextFieldKeyTyped
        // TODO add your handling code here:
        jButtonSave.setEnabled(validatePanel());
    }//GEN-LAST:event_jNamaTextFieldKeyTyped

    private void jTempatLahirTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTempatLahirTextFieldKeyTyped
        // TODO add your handling code here:
        jButtonSave.setEnabled(validatePanel());
    }//GEN-LAST:event_jTempatLahirTextFieldKeyTyped

    private void jAlamatTextAreaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jAlamatTextAreaKeyTyped
        // TODO add your handling code here:
        jButtonSave.setEnabled(validatePanel());
    }//GEN-LAST:event_jAlamatTextAreaKeyTyped

    private void jNomorIndukTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jNomorIndukTextFieldKeyReleased
        // TODO add your handling code here:
        checkNomorPendaftaran();
        jButtonSave.setEnabled(validatePanel());
    }//GEN-LAST:event_jNomorIndukTextFieldKeyReleased

    private void jNamaTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jNamaTextFieldKeyReleased
        // TODO add your handling code here:
        jButtonSave.setEnabled(validatePanel());
    }//GEN-LAST:event_jNamaTextFieldKeyReleased

    private void jTempatLahirTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTempatLahirTextFieldKeyReleased
        // TODO add your handling code here:
        jButtonSave.setEnabled(validatePanel());
    }//GEN-LAST:event_jTempatLahirTextFieldKeyReleased

    private void jAlamatTextAreaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jAlamatTextAreaKeyReleased
        // TODO add your handling code here:
        jButtonSave.setEnabled(validatePanel());
    }//GEN-LAST:event_jAlamatTextAreaKeyReleased

    private void jTelepon1TextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTelepon1TextFieldKeyReleased
        // TODO add your handling code here:
        jButtonSave.setEnabled(validatePanel());
    }//GEN-LAST:event_jTelepon1TextFieldKeyReleased

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCancelActionPerformed

    private void jNamaAyahTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNamaAyahTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jNamaAyahTextFieldActionPerformed

    private void jCheckBoxInsertProfilsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxInsertProfilsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxInsertProfilsActionPerformed

    private void jButtonCancel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancel1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(true);
        jDialogInputSiswa.setVisible(false);
    }//GEN-LAST:event_jButtonCancel1ActionPerformed

    private void jButtonSave1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSave1ActionPerformed
        jDialogInputSiswa.dispose();
        try {
            // TODO add your handling code here:
            if (profil != null) {
                updateProfil();
            } else {
                insertProfil();
            }
            JOptionPane.showMessageDialog(rootPane, "Input Siswa Berhasil");
        } catch (SQLException ex) {
            Exceptions.printStackTrace(ex);
            JOptionPane.showMessageDialog(rootPane, "Input Siswa Gagal!\r\n".concat(ex.toString()));
        } catch (KasirException ex) {
            Exceptions.printStackTrace(ex);
            JOptionPane.showMessageDialog(rootPane, "Input Siswa Gagal!\r\n".concat(ex.toString()));
        }

    }//GEN-LAST:event_jButtonSave1ActionPerformed

    private void jTelepon2TextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTelepon2TextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTelepon2TextField1ActionPerformed

    private void jTelepon1TextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTelepon1TextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTelepon1TextField1ActionPerformed

    private void jNamaIbuTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNamaIbuTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jNamaIbuTextField1ActionPerformed

    private void jJenisKelaminComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jJenisKelaminComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jJenisKelaminComboBox1ActionPerformed

    private void jNamaTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNamaTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jNamaTextField1ActionPerformed

    private void jNomorIndukTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNomorIndukTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jNomorIndukTextField1ActionPerformed

    private void jButtonSaveProfilsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveProfilsActionPerformed
        try {
            // TODO add your handling code here:
            Control.insertProfils(profilList);
            JOptionPane.showMessageDialog(rootPane, "Input (Multiple) Siswa Berhasil");
        } catch (SQLException ex) {
            Exceptions.printStackTrace(ex);
            JOptionPane.showMessageDialog(rootPane, "Input (Multiple) Siswa Gagal!\r\n".concat(ex.toString()));
        } catch (KasirException ex) {
            Exceptions.printStackTrace(ex);
            JOptionPane.showMessageDialog(rootPane, "Input (Multiple) Siswa Gagal!\r\n".concat(ex.toString()));
        }
    }//GEN-LAST:event_jButtonSaveProfilsActionPerformed

    private void jButtonClearProfilsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearProfilsActionPerformed
        // TODO add your handling code here:
        profilList.clear();
        jTable1.setModel(new DefaultTableModel());
        jDialogListInputSiswa.dispose();
    }//GEN-LAST:event_jButtonClearProfilsActionPerformed

    private void jAgamaComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAgamaComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jAgamaComboBoxActionPerformed

    private void jAgamaComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAgamaComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jAgamaComboBox1ActionPerformed

    private void jComboBoxTingkatSekolahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTingkatSekolahActionPerformed
        // TODO add your handling code here:
        autoUpdateLevel2Level3();
    }//GEN-LAST:event_jComboBoxTingkatSekolahActionPerformed

    private void jAsalSekolahTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAsalSekolahTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jAsalSekolahTextFieldActionPerformed

    private void jAsalSekolahTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jAsalSekolahTextFieldKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jAsalSekolahTextFieldKeyReleased

    private void jAsalSekolahTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jAsalSekolahTextFieldKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jAsalSekolahTextFieldKeyTyped

    private void jAsalSekolahTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAsalSekolahTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jAsalSekolahTextField1ActionPerformed

    private void jAlamatTextAreaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jAlamatTextAreaKeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jAlamatTextAreaKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InputProfilFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InputProfilFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InputProfilFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InputProfilFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
//                new InputProfilFrame().setVisible(true);
            }
        });
    }
    
    private void continueToConfirmationDialog(){
        this.setVisible(false);
        jDialogInputSiswa.setVisible(true);
        dateChooserComboTanggalLahir1.setLocked(true);
        dateChooserComboTanggalMasuk1.setLocked(true);
    }
    
    private boolean validatePanel(){
        return !panelPrivate.isFatalProblem();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private datechooser.beans.DateChooserCombo dateChooserComboTanggalLahir;
    private datechooser.beans.DateChooserCombo dateChooserComboTanggalLahir1;
    private datechooser.beans.DateChooserCombo dateChooserComboTanggalMasuk;
    private datechooser.beans.DateChooserCombo dateChooserComboTanggalMasuk1;
    private javax.swing.JComboBox jAgamaComboBox;
    private javax.swing.JComboBox jAgamaComboBox1;
    private javax.swing.JLabel jAgamaLabel;
    private javax.swing.JLabel jAgamaLabel1;
    private javax.swing.JLabel jAlamatLabel;
    private javax.swing.JLabel jAlamatLabel1;
    private javax.swing.JTextArea jAlamatTextArea;
    private javax.swing.JTextArea jAlamatTextArea1;
    private javax.swing.JLabel jAsalSekolahLabel;
    private javax.swing.JLabel jAsalSekolahLabel1;
    private javax.swing.JTextField jAsalSekolahTextField;
    private javax.swing.JTextField jAsalSekolahTextField1;
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonCancel1;
    private javax.swing.JButton jButtonClearProfils;
    private javax.swing.JButton jButtonSave;
    private javax.swing.JButton jButtonSave1;
    private javax.swing.JButton jButtonSaveProfils;
    private javax.swing.JCheckBox jCheckBoxInsertProfils;
    private javax.swing.JComboBox jComboBoxTingkatKelas;
    private javax.swing.JComboBox jComboBoxTingkatKelas1;
    private javax.swing.JComboBox jComboBoxTingkatSekolah;
    private javax.swing.JComboBox jComboBoxTingkatSekolah1;
    private javax.swing.JComboBox jComboBoxTingkatSubKelas;
    private javax.swing.JComboBox jComboBoxTingkatSubKelas1;
    private javax.swing.JDialog jDialogInputSiswa;
    private javax.swing.JFrame jDialogListInputSiswa;
    private javax.swing.JComboBox jJenisKelaminComboBox;
    private javax.swing.JComboBox jJenisKelaminComboBox1;
    private javax.swing.JLabel jJenisKelaminLabel;
    private javax.swing.JLabel jJenisKelaminLabel1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jNamaAyahLabel;
    private javax.swing.JLabel jNamaAyahLabel1;
    private javax.swing.JTextField jNamaAyahTextField;
    private javax.swing.JTextField jNamaAyahTextField1;
    private javax.swing.JLabel jNamaIbuLabel;
    private javax.swing.JLabel jNamaIbuLabel1;
    private javax.swing.JTextField jNamaIbuTextField;
    private javax.swing.JTextField jNamaIbuTextField1;
    private javax.swing.JLabel jNamaLabel;
    private javax.swing.JLabel jNamaLabel1;
    private javax.swing.JTextField jNamaTextField;
    private javax.swing.JTextField jNamaTextField1;
    private javax.swing.JLabel jNomorIndukLabel;
    private javax.swing.JLabel jNomorIndukLabel1;
    private javax.swing.JTextField jNomorIndukTextField;
    private javax.swing.JTextField jNomorIndukTextField1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel jTanggalLahirLabel;
    private javax.swing.JLabel jTanggalLahirLabel1;
    private javax.swing.JLabel jTanggalMasuk;
    private javax.swing.JLabel jTanggalMasuk1;
    private javax.swing.JLabel jTanggalMasuk2;
    private javax.swing.JLabel jTanggalMasuk3;
    private javax.swing.JLabel jTanggalMasuk4;
    private javax.swing.JLabel jTelepon1Label;
    private javax.swing.JLabel jTelepon1Label1;
    private javax.swing.JTextField jTelepon1TextField;
    private javax.swing.JTextField jTelepon1TextField1;
    private javax.swing.JLabel jTelepon2Label;
    private javax.swing.JLabel jTelepon2Label1;
    private javax.swing.JTextField jTelepon2TextField;
    private javax.swing.JTextField jTelepon2TextField1;
    private javax.swing.JLabel jTempatLahirLabel;
    private javax.swing.JLabel jTempatLahirLabel1;
    private javax.swing.JTextField jTempatLahirTextField;
    private javax.swing.JTextField jTempatLahirTextField1;
    private javax.swing.JLabel jTingkatKelas1;
    private javax.swing.JLabel jTingkatSekolah1;
    private javax.swing.JLabel jTingkatSubKelas1;
    private javax.swing.JLabel jTitleLabel;
    private javax.swing.JLabel jTitleLabel1;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

    private void insertProfil() throws SQLException, KasirException {
        Biodata biodata = new Biodata(jNamaTextField1.getText()
                , (pelajar.Biodata.Kelamin)jJenisKelaminComboBox1.getSelectedItem()
                , (pelajar.Biodata.Agama)jAgamaComboBox1.getSelectedItem()
                , jAsalSekolahTextField1.getText()
                , new sak.Kalender(dateChooserComboTanggalLahir1.getSelectedDate().getTime())
                , jTempatLahirTextField1.getText()
                , jAlamatTextArea1.getText()
                , jTelepon1TextField1.getText()
                , jTelepon2TextField1.getText()
                , jNamaAyahTextField1.getText()
                , jNamaIbuTextField1.getText());
        Level level = new Level((pelajar.Level.Level1)jComboBoxTingkatSekolah1.getSelectedItem()
                , (pelajar.Level.Level2)jComboBoxTingkatKelas1.getSelectedItem()
                , (pelajar.Level.Level3)jComboBoxTingkatSubKelas1.getSelectedItem()
                , dateChooserComboTanggalMasuk1.getSelectedDate().get(Calendar.YEAR));
        Profil profilData = new Profil(jNomorIndukTextField1.getText(), level, biodata, new sak.Kalender(dateChooserComboTanggalMasuk1.getSelectedDate().getTime()), null, new sak.Kalender(Calendar.getInstance().getTime()));
        Control.insertProfil(profilData);
        
        
        //auto target iuran
        if(clerk.jabatan.equals("pendaftaran")){
            IPSP ipsp = new IPSP(profilData.noInduk, profilData.currentLevel, 0f, "IPSP");
            PASB pasb = new PASB(profilData.noInduk, profilData.currentLevel, "Administrasi PASB", 0f, "PASB");
            Attribute attribute = new Attribute(profilData.noInduk, profilData.currentLevel, "MOPDB, Pas Photo, Kartu Pelajar, Sampul Laporan Pendidikan", 0f, "");
            Seragam seragam = new Seragam(profilData.noInduk, profilData.currentLevel, "SERAGAM", 0f, "SERAGAM");
            Almamater almamater = new Almamater(profilData.noInduk, profilData.currentLevel, "ALMAMATER", 0f, "ALMAMATER");
            ArrayList<Entry> entryIKS = new ArrayList<>();
            ArrayList<Entry> entryIPP = new ArrayList<>();
            ArrayList<Entry> entryOSIS = new ArrayList<>();
            ArrayList<Entry> entryPVT = new ArrayList<>();
            switch(profilData.currentLevel.level1){
                case SMA:
                    ipsp.amount = 3500000f;
                    pasb.amount = 200000f;
                    attribute.amount = 310000f;
                    seragam.amount = 400000f;
                    entryIKS.add(new Entry(0, 400000f));
                    entryOSIS.add(new Entry(0, 250000f));
                    for(int i = 0; i<12 ; i++){
                        entryIPP.add(new Entry(i,380000f));
                    }
                    break;
                case SMP:
                    ipsp.amount = 1500000f;
                    pasb.amount = 100000f;
                    attribute.amount = 100000f;
                    seragam.amount = 350000f;
                    entryIKS.add(new Entry(0, 200000f));
                    entryOSIS.add(new Entry(0, 150000f));
                    for(int i = 0; i<12 ; i++){
                        entryIPP.add(new Entry(i,225000f));
                    }

                    break;
                case SMK:
                    ipsp.amount = 2000000f;
                    pasb.amount = 150000f;
                    attribute.amount = 100000f;
                    seragam.amount = 360000f;
                    entryIKS.add(new Entry(0, 300000f));
                    entryOSIS.add(new Entry(0, 225000f));
                    entryPVT.add(new Entry(0, 720000f));
                    almamater.amount = 250000f;
                    PVT pvt = new PVT(profilData.noInduk, profilData.currentLevel, entryPVT);
                    pvt.entries.get(0).debt = pvt.entries.get(0).amount;
                    Control.insertIuran(Iuran.Tipe.PVT, pvt);
                    for(int i = 0; i<12 ; i++){
                        entryIPP.add(new Entry(i,275000f));
                    }
                    break;
                default:
                    
                    break;
            }
            IPP ipp = new IPP(profilData.noInduk, profilData.currentLevel,entryIPP);
            ipp.entries.get(0).debt = ipp.entries.get(0).amount;
            OSIS osis = new OSIS(profilData.noInduk, profilData.currentLevel, entryOSIS);
            osis.entries.get(0).debt = osis.entries.get(0).amount;
            IKS iks = new IKS(profilData.noInduk, profilData.currentLevel, entryIKS);
            iks.entries.get(0).debt = iks.entries.get(0).amount;
            ipsp.debt = ipsp.amount;
            pasb.debt = pasb.amount;
            attribute.debt = attribute.amount;
            seragam.debt = seragam.amount;
            almamater.debt = almamater.amount;
            attribute.note =attribute.transactName;
            
            Control.insertIuran(Iuran.Tipe.IPSP, ipsp);
            Control.insertIuran(Iuran.Tipe.PASB, pasb);
            Control.insertIuran(Iuran.Tipe.Attribute, attribute);
            Control.insertIuran(Iuran.Tipe.Seragam, seragam);
            Control.insertIuran(Iuran.Tipe.IKS, iks);
            Control.insertIuran(Iuran.Tipe.IPP, ipp);
            Control.insertIuran(Iuran.Tipe.OSIS, osis);
            Control.insertIuran(Iuran.Tipe.Almamater, almamater);
        }
        //end autotarget iuran
    }
    
    private void updateProfil() throws SQLException, KasirException {
        Biodata biodata = new Biodata(jNamaTextField1.getText()
                , (pelajar.Biodata.Kelamin)jJenisKelaminComboBox1.getSelectedItem()
                , (pelajar.Biodata.Agama)jAgamaComboBox1.getSelectedItem()
                , jAsalSekolahTextField1.getText()
                , new sak.Kalender(dateChooserComboTanggalLahir1.getSelectedDate().getTime())
                , jTempatLahirTextField1.getText()
                , jAlamatTextArea1.getText()
                , jTelepon1TextField1.getText()
                , jTelepon2TextField1.getText()
                , jNamaAyahTextField1.getText()
                , jNamaIbuTextField1.getText());
        Level level = new Level((pelajar.Level.Level1)jComboBoxTingkatSekolah1.getSelectedItem()
                , (pelajar.Level.Level2)jComboBoxTingkatKelas1.getSelectedItem()
                , (pelajar.Level.Level3)jComboBoxTingkatSubKelas1.getSelectedItem()
                , dateChooserComboTanggalMasuk1.getSelectedDate().get(Calendar.YEAR));
        Profil profilData = new Profil(jNomorIndukTextField1.getText(), level, biodata, new sak.Kalender(dateChooserComboTanggalMasuk1.getSelectedDate().getTime()), null, new sak.Kalender(Calendar.getInstance().getTime()));
        Control.updateProfil(profilData);
    }
    
    private boolean addProfil(){
        Biodata biodata = new Biodata(jNamaTextField1.getText()
                , (pelajar.Biodata.Kelamin)jJenisKelaminComboBox1.getSelectedItem()
                , (pelajar.Biodata.Agama)jAgamaComboBox1.getSelectedItem()
                , jAsalSekolahTextField1.getText()
                , new sak.Kalender(dateChooserComboTanggalLahir1.getSelectedDate().getTime())
                , jTempatLahirTextField1.getText()
                , jAlamatTextArea1.getText()
                , jTelepon1TextField1.getText()
                , jTelepon2TextField1.getText()
                , jNamaAyahTextField1.getText()
                , jNamaIbuTextField1.getText());
        Level level = new Level((pelajar.Level.Level1)jComboBoxTingkatSekolah1.getSelectedItem()
                , (pelajar.Level.Level2)jComboBoxTingkatKelas1.getSelectedItem()
                , (pelajar.Level.Level3)jComboBoxTingkatSubKelas1.getSelectedItem()
                , dateChooserComboTanggalMasuk1.getSelectedDate().get(Calendar.YEAR));
        Profil temp = new Profil(jNomorIndukTextField1.getText(), level, biodata, new sak.Kalender(dateChooserComboTanggalMasuk1.getSelectedDate().getTime()), null, new sak.Kalender(Calendar.getInstance().getTime()));
        profilList.add(temp);
        return true;
    }
    
    private Boolean insertProfils() throws SQLException, KasirException{
        
        Control.insertProfils(profilList);
        return true;
    }

    private void continueToListDisplayDialog() {
        addProfil();
        jDialogListInputSiswa.setVisible(true);
        profilsTableModel = buildInitialTableModel(profilList);
        jTable1.setModel(profilsTableModel);
//        "Nomor Induk"
//               , "Nama Siswa"
//               , "Jenis Kelamin"
//               , "Tanggal Lahir"
//               , "Tempat Lahir"
//               , "Alamat"
//               , "Nama Ayah"
//               , "Nama Ibu"
//               , "Telepon 1"
//               , "Telepon 2"
//               , "Tanggal Masuk"
//               , "Sekolah"
//               , "Kelas"
//               , "Sub Kelas"
        jTable1.getColumnModel().getColumn(0).setPreferredWidth(100);
        jTable1.getColumnModel().getColumn(1).setPreferredWidth(140);
        jTable1.getColumnModel().getColumn(2).setPreferredWidth(120);
        jTable1.getColumnModel().getColumn(3).setPreferredWidth(120);
        jTable1.getColumnModel().getColumn(4).setPreferredWidth(140);
        jTable1.getColumnModel().getColumn(5).setPreferredWidth(300);
        jTable1.getColumnModel().getColumn(6).setPreferredWidth(120);
        jTable1.getColumnModel().getColumn(7).setPreferredWidth(120);
        jTable1.getColumnModel().getColumn(8).setPreferredWidth(100);
        jTable1.getColumnModel().getColumn(9).setPreferredWidth(100);
        jTable1.getColumnModel().getColumn(10).setPreferredWidth(120);
        jTable1.getColumnModel().getColumn(11).setPreferredWidth(80);
        jTable1.getColumnModel().getColumn(12).setPreferredWidth(80);
        jTable1.getColumnModel().getColumn(13).setPreferredWidth(120);
        
        jTable1.getColumnModel().getColumn(2).setCellEditor(new DefaultCellEditor(new JComboBox(jJenisKelaminComboBox.getModel())));
        jTable1.setSize(3000, 5000);
        //updateRowHeights();
        
    }   
    
    private TableModel buildInitialTableModel(ArrayList<Profil> profils){
       String columnNames[] = {"Nomor Induk"
               , "Nama Siswa"
               , "Jenis Kelamin"
               , "Agama"
               , "Tanggal Lahir"
               , "Tempat Lahir"
               , "Alamat"
               , "Nama Ayah"
               , "Nama Ibu"
               , "Telepon 1"
               , "Telepon 2"
               , "Tanggal Masuk"
               , "Sekolah"
               , "Kelas"
               , "Sub Kelas"};
       Object[][] data = new Object[profils.size()][15];
       
       for(int i = 0 ; i< profils.size(); i++){
           data[i][0] = profils.get(i).noInduk;
           data[i][1] = profils.get(i).biodata.nama;
           data[i][2] = profils.get(i).biodata.kelamin;
           data[i][3] = profils.get(i).biodata.agama;
           data[i][4] = profils.get(i).biodata.tanggalLahir;
           data[i][5] = profils.get(i).biodata.tempatLahir;
           data[i][6] = profils.get(i).biodata.alamat;
           data[i][7] = profils.get(i).biodata.namaAyah;
           data[i][8] = profils.get(i).biodata.namaIbu;
           data[i][9] = profils.get(i).biodata.telpon1;
           data[i][10] = profils.get(i).biodata.telpon2;
           data[i][11]= profils.get(i).tanggalMasuk;
           data[i][12]= profils.get(i).currentLevel.level1;
           data[i][13]= profils.get(i).currentLevel.level2;
           data[i][14]= profils.get(i).currentLevel.level3;
       }    
       
       TableModel tm = new DefaultTableModel(data, columnNames){
           @Override
            public boolean isCellEditable(int row, int column) {
                //all cells false for editable
                return true;
            }
       };
       
       return tm;
       
   }
    
    private void autoUpdateLevel2Level3(){
        
    }

    private void checkNomorPendaftaran() {
        String prefixNomorInduk = "";
        try {
            prefixNomorInduk = jNomorIndukTextField.getText(0,1).toUpperCase();
        } catch (BadLocationException ex) {
            Exceptions.printStackTrace(ex);
        }
        switch(prefixNomorInduk){
            case "A":
                jComboBoxTingkatSekolah.setSelectedItem(Level.Level1.SMA);
                jComboBoxTingkatKelas.setSelectedItem(Level.Level2.SEPULUH);
                break;
            case "P":
                jComboBoxTingkatSekolah.setSelectedItem(Level.Level1.SMP);
                jComboBoxTingkatKelas.setSelectedItem(Level.Level2.TUJUH);
                break;
            case "K":
                jComboBoxTingkatSekolah.setSelectedItem(Level.Level1.SMK);
                jComboBoxTingkatKelas.setSelectedItem(Level.Level2.SEPULUH);
                break;
            default :
                jComboBoxTingkatSekolah.setSelectedItem(Level.Level1.SMA);
                jComboBoxTingkatKelas.setSelectedItem(Level.Level2.SEPULUH);
                break;
        }
    }
}
