/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import iuran.*;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.*;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import kasir.Control;
import org.openide.util.Exceptions;
import pelajar.Level;
import pelajar.Profil;
import printout.TunggakanBean;
import sak.KasirException;

/**
 *
 * @author Master
 */
public class InputTransactionIUS extends javax.swing.JFrame {
    Profil profil;
    private TableModel tableModelIUS;
    private IUS iusFromDB;
    public List<Integer> tahunIUS;
    public ArrayList<Float> iDDAmounts;
    public ArrayList<Float> beasiswaAmounts;
    public ArrayList<Float> beasiswaCostAmounts;
    public ArrayList<Float> iUSAmounts;
    private IUS iusCurrent;
    private IUS iusStoreToDB;
    private IDD idd;
    private InputTransactionFrameSeparated itfs;
    private final String[] namaBulan = {"MID SEMESTER 1", "UJIAN SEMESTER 1", "MID SEMESTER 2", "UJIAN SEMESTER 2"};
    private float unpaidIUS;
    private ComboBoxModel tahunComboBoxModel;
    private String tunggakanIUSString = new String("");
    private String tunggakanIUSEachAmountString = new String("");
    private float iusDebt;
    /**
     * Creates new form InputTransactionIUS
     */
    
    public InputTransactionIUS(Profil profil, InputTransactionFrameSeparated itfs) {
        this.profil = profil;
        this.itfs = itfs;
        try {
            tableModelIUS = buildIUSTableModel(profil, profil.currentLevel.tahun);
        } catch (SQLException ex) {
            Exceptions.printStackTrace(ex);
        } catch (KasirException ex) {
            Exceptions.printStackTrace(ex);
        }
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelIPP = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabelTahun = new javax.swing.JLabel();
        jComboBoxTahun = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jUnpaidSemester = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTableIUS = new javax.swing.JTable();
        jButtonBayarIUS = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jFormattedTextFieldIDDSaldo = new javax.swing.JFormattedTextField();
        jTextFieldIUSDebt = new javax.swing.JFormattedTextField();

        setTitle(org.openide.util.NbBundle.getMessage(InputTransactionIUS.class, "InputTransactionIUS.title")); // NOI18N

        jPanelIPP.setMinimumSize(new java.awt.Dimension(570, 380));
        jPanelIPP.setPreferredSize(new java.awt.Dimension(680, 450));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText(org.openide.util.NbBundle.getMessage(InputTransactionIUS.class, "InputTransactionIUS.jLabel1.text")); // NOI18N

        jLabelTahun.setText(org.openide.util.NbBundle.getMessage(InputTransactionIUS.class, "InputTransactionIUS.jLabelTahun.text")); // NOI18N

        try{
            tahunComboBoxModel = buildIUStahunComboBoxModel(profil);
        }catch(SQLException ex){
            ex.printStackTrace();
        }catch(KasirException ex){
            ex.printStackTrace();
        }
        jComboBoxTahun.setModel(tahunComboBoxModel);
        jComboBoxTahun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTahunActionPerformed(evt);
            }
        });
        jComboBoxTahun.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jComboBoxTahunPropertyChange(evt);
            }
        });

        jLabel2.setText(org.openide.util.NbBundle.getMessage(InputTransactionIUS.class, "InputTransactionIUS.jLabel2.text")); // NOI18N

        jUnpaidSemester.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jUnpaidSemester.setText(String.valueOf(unpaidIUS));
        jUnpaidSemester.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jUnpaidSemester.setEnabled(false);

        jTableIUS.setModel(tableModelIUS);
        jTableIUS.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jTableIUS.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTableIUSFocusLost(evt);
            }
        });
        jTableIUS.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jTableIUSPropertyChange(evt);
            }
        });
        jScrollPane5.setViewportView(jTableIUS);

        jButtonBayarIUS.setText(org.openide.util.NbBundle.getMessage(InputTransactionIUS.class, "InputTransactionIUS.jButtonBayarIUS.text")); // NOI18N
        jButtonBayarIUS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBayarIUSActionPerformed(evt);
            }
        });

        jLabel3.setText(org.openide.util.NbBundle.getMessage(InputTransactionIUS.class, "InputTransactionIUS.jLabel3.text")); // NOI18N

        jFormattedTextFieldIDDSaldo.setText(org.openide.util.NbBundle.getMessage(InputTransactionIUS.class, "InputTransactionIUS.jFormattedTextFieldIDDSaldo.text")); // NOI18N
        jFormattedTextFieldIDDSaldo.setEnabled(false);

        jTextFieldIUSDebt.setEditable(false);
        jTextFieldIUSDebt.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0"))));

        javax.swing.GroupLayout jPanelIPPLayout = new javax.swing.GroupLayout(jPanelIPP);
        jPanelIPP.setLayout(jPanelIPPLayout);
        jPanelIPPLayout.setHorizontalGroup(
            jPanelIPPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelIPPLayout.createSequentialGroup()
                .addGroup(jPanelIPPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelIPPLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane5))
                    .addGroup(jPanelIPPLayout.createSequentialGroup()
                        .addGroup(jPanelIPPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelIPPLayout.createSequentialGroup()
                                .addGap(248, 248, 248)
                                .addComponent(jButtonBayarIUS))
                            .addGroup(jPanelIPPLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1)
                                .addGap(29, 29, 29)
                                .addComponent(jLabelTahun)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanelIPPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jComboBoxTahun, 0, 101, Short.MAX_VALUE)
                                    .addComponent(jTextFieldIUSDebt))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanelIPPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelIPPLayout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jUnpaidSemester, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanelIPPLayout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jFormattedTextFieldIDDSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 9, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelIPPLayout.setVerticalGroup(
            jPanelIPPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelIPPLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanelIPPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxTahun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTahun)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jUnpaidSemester, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelIPPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jFormattedTextFieldIDDSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldIUSDebt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonBayarIUS)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelIPP, javax.swing.GroupLayout.DEFAULT_SIZE, 570, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelIPP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxTahunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTahunActionPerformed
        // TODO add your handling code here:
        try {
            this.tableModelIUS = (DefaultTableModel) buildIUSTableModel(this.profil, this.tahunIUS.get(jComboBoxTahun.getSelectedIndex()));
            jTableIUS.setModel(this.tableModelIUS);
            jTextFieldIUSDebt.setValue(iusDebt);
        } catch (SQLException ex) {
            ex.printStackTrace();
        } catch (KasirException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jComboBoxTahunActionPerformed

    private void jComboBoxTahunPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jComboBoxTahunPropertyChange
        // TODO add your handling code here:
        try {
            if (this.jComboBoxTahun.getSelectedItem() != null) {
                this.tableModelIUS = (DefaultTableModel) buildIUSTableModel(this.profil, this.tahunIUS.get(jComboBoxTahun.getSelectedIndex()));
                jTableIUS.setModel(this.tableModelIUS);
                jTextFieldIUSDebt.setValue(iusDebt);
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(rootPane, "Koneksi Error!\r\n".concat(ex.toString()));
        } catch (KasirException ex) {
            JOptionPane.showMessageDialog(rootPane, "IUS Belum Di Setting!\r\n".concat(ex.toString()));
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jComboBoxTahunPropertyChange

    private void jTableIUSFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTableIUSFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTableIUSFocusLost

    private void jTableIUSPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jTableIUSPropertyChange
        // TODO add your handling code here:
        //IDD, Beasiswa, Beasiswa Cost
        iUSAmounts = new ArrayList();
        iDDAmounts = new ArrayList();
        beasiswaAmounts = new ArrayList();
        beasiswaCostAmounts = new ArrayList();
        /////BLOOOOOOOOOOM SELESAIIIIIIIIIIIIIIIIIIII
        int i = 0;
        iusCurrent = new IUS();
        iusStoreToDB = new IUS();
        ArrayList<Entry> entry = new ArrayList<>();
        if (iusFromDB.entries.size() != 0) {
            for (i = 0; i < jTableIUS.getRowCount(); i++) {
                iusCurrent.entries.add((Boolean) jTableIUS.getValueAt(i, 2) ? ((iusFromDB.entries.get(i).transactDetailIDs.size() > 0) ? new Entry(i, iusFromDB.entries.get(i).amount, iusFromDB.entries.get(i).debt, iusFromDB.entries.get(i).transactDetailIDs) : new Entry(i, iusFromDB.entries.get(i).amount)) : null);
                //below condition is when jTableIUS checkBox is UNCHECK ????
                if (iusCurrent.entries.get(i) == null) {
                    iusStoreToDB.entries.add(null);
                    jTableIUS.setValueAt(0f, i, 3);
                    jTableIUS.setValueAt(0f, i, 4);
                    jTableIUS.setValueAt(0f, i, 5);
                    jTableIUS.setValueAt(0f, i, 6);
                    iUSAmounts.add(0f);
                    iDDAmounts.add(0f);
                    beasiswaAmounts.add(0f);
                    beasiswaCostAmounts.add(0f);
                    //below is when jTableIUS property changed, especially check box is Changed or Editing IDD, Beasiswa, Beasiswa Cost 
                } else if ((iusCurrent.entries.get(i) != null) ^ (iusFromDB.entries.get(i).transactDetailIDs.size() > 0)) {
                    System.out.println("IDD dari db ");
                    if (idd != null) {
                        System.out.println(idd.amount);
                    }
                    iUSAmounts.add((Float) jTableIUS.getModel().getValueAt(i,3));
                    iDDAmounts.add((Float) jTableIUS.getValueAt(i, 4));
                    beasiswaAmounts.add((Float) jTableIUS.getValueAt(i, 5));
                    beasiswaCostAmounts.add((Float) jTableIUS.getValueAt(i, 6));
                    //jTableIUS.setValueAt(iusFromDB.entries.get(i).amount - (iDDAmounts.get(i) + beasiswaAmounts.get(i) + beasiswaCostAmounts.get(i)), i, 3);
                    //iusStoreToDB.entries.add(new Entry(i, iusFromDB.entries.get(i).amount));
                    iusStoreToDB.entries.add(new Entry(i, iUSAmounts.get(i)+iDDAmounts.get(i)+beasiswaAmounts.get(i)+beasiswaCostAmounts.get(i)));
                } else {
                    try {
                        if(isIUSEnough(iusFromDB.entries.get(i).transactDetailIDs, iusFromDB.entries.get(i).amount)){
                            iUSAmounts.add(0f);
                            iDDAmounts.add(0f);
                            beasiswaAmounts.add(0f);
                            beasiswaCostAmounts.add(0f);
                            iusStoreToDB.entries.add(null);
                        }else{
                            iUSAmounts.add((Float) jTableIUS.getModel().getValueAt(i,3));
                            iDDAmounts.add((Float) jTableIUS.getValueAt(i, 4));
                            beasiswaAmounts.add((Float) jTableIUS.getValueAt(i, 5));
                            beasiswaCostAmounts.add((Float) jTableIUS.getValueAt(i, 6));
                            iusStoreToDB.entries.add(new Entry(i, iUSAmounts.get(i)+iDDAmounts.get(i)+beasiswaAmounts.get(i)+beasiswaCostAmounts.get(i)));
                        }
                    } catch (SQLException ex) {
                        Exceptions.printStackTrace(ex);
                    } catch (KasirException ex) {
                        Exceptions.printStackTrace(ex);
                    }
                    

                }
                //iusCurrent.entries.add((Boolean)jTableIUS.getValueAt(i,2)? new IUS(profil.noInduk, new Level(null,null,null,(Integer)jComboBoxTahun.getSelectedItem()),entry).entries.get(i): null);
                //iusStoreToDB.entries.add(iusCurrent.entries.get(i)==null?null:(((iusCurrent.entries.get(i)!=null)^(iusFromDB.entries.get(i)!=null))? new IUS(profil.noInduk, new Level(null,null,null,(int)jComboBoxTahun.getSelectedItem()),entry).entries.get(i):iusCurrent.entries.get(i)));
                //System.out.println("IUS Period: "+iusCurrent.entries.get(i).period);
            }
        }
    }//GEN-LAST:event_jTableIUSPropertyChange

    private void jButtonBayarIUSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBayarIUSActionPerformed
        // TODO add your handling code here:
        float iusAmountTemp = 0f;
        for (int i = 0; i < 2; i++) {
            if (iusStoreToDB.entries.get(i) != null) {
                //iusAmountTemp = iusAmountTemp + iusFromDB.entries.get(i).amount;
                iusAmountTemp = iusAmountTemp + (Float)jTableIUS.getModel().getValueAt(i,3)
                                +(Float)jTableIUS.getModel().getValueAt(i,4)
                                +(Float)jTableIUS.getModel().getValueAt(i,5)
                                +(Float)jTableIUS.getModel().getValueAt(i,6);
            }
        }
        itfs.jTextFieldIUSAmountSimple.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0"))));
        itfs.jTextFieldIUSAmountSimple.setValue(iusAmountTemp);
        try {
            itfs.jTextFieldIUSAmountSimple.commitEdit();
        } catch (ParseException ex) {
            Exceptions.printStackTrace(ex);
        }
        itfs.iusCurrent = iusCurrent;
        itfs.iusFromDB = iusFromDB;
        itfs.iusStoreToDB = iusStoreToDB;
        this.setVisible(false);

    }//GEN-LAST:event_jButtonBayarIUSActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InputTransactionFrameSeparated.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InputTransactionFrameSeparated.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InputTransactionFrameSeparated.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InputTransactionFrameSeparated.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                //new InputTransactionIUS().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBayarIUS;
    public javax.swing.JComboBox jComboBoxTahun;
    private javax.swing.JFormattedTextField jFormattedTextFieldIDDSaldo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelTahun;
    private javax.swing.JPanel jPanelIPP;
    private javax.swing.JScrollPane jScrollPane5;
    public javax.swing.JTable jTableIUS;
    private javax.swing.JFormattedTextField jTextFieldIUSDebt;
    private javax.swing.JTextField jUnpaidSemester;
    // End of variables declaration//GEN-END:variables

    public TableModel buildIUSTableModel(Profil profil, int tahun) throws SQLException, KasirException {
       String columnNames[] = {"Semester", "Biaya IUS", "Check Box", "Tunai", "Iuran Dibayar Dimuka", "Beasiswa", "Beasiswa Yayasan"};
       Set<IUS> iusFilters = new HashSet<>();
       ArrayList<Entry> entries = new ArrayList<>();
       iusFilters.clear();
       iusFilters.add(new IUS(profil.noInduk, new Level(null,null,null,tahun), entries));
       Map<Long, IUS> searchResultMap = Control.exactFilterSelectIurans(Iuran.Tipe.IUS, iusFilters);
       Object[][] data = new Object[4][7];
       int i = 0;
       final boolean[] canEdit = new boolean [4];
       iusFromDB = new IUS();
       float amountIUSinTable;
       float amountIUSinTDetail;
       iusDebt = 0f;
       if(searchResultMap.size() > 0){
        for(Map.Entry<Long, IUS> entry: searchResultMap.entrySet()){
            for(int j =0 ; j< entry.getValue().entries.size(); j++){
                data[j][0]= namaBulan[j];//entry.getValue().entries.get(j).period;
                data[j][1]= entry.getValue().entries.get(j).amount - calculatePaidIUS(entry.getValue().entries.get(j).transactDetailIDs); // ANEH NIH MASA BEGINI, DI KALI DUA SIH?
                amountIUSinTable = entry.getValue().entries.get(j).amount;
                iusDebt += entry.getValue().entries.get(j).debt;
                //if(jTable2 != null){data[j][2]= jTable2.getModel().getValueAt(j,2);}else{data[j][2]= new Boolean(false);}
                //if(entry.getValue().entries.get(j).transactDetailIDs.size() > 0){
                if(isIUSEnough(entry.getValue().entries.get(j).transactDetailIDs, amountIUSinTable)){        
//                    
                    data[j][2] = new Boolean(true);
                    Float data3 = 0f;
                    Float data4 = 0f;
                    Float data5 = 0f;
                    Float data6 = 0f;
                    
                    for(Long setTDetailIds:entry.getValue().entries.get(j).transactDetailIDs){
                        System.out.println(setTDetailIds + " Set TDetailsID");
                        if(Control.selectTDetail(TransactionDetail.Tipe.IUSTransaction, setTDetailIds).paymentMethod == TransactionDetail.PaymentMethod.CASH){
                            data3 += Control.selectTDetail(TransactionDetail.Tipe.IUSTransaction, setTDetailIds).amount;
                            data[j][3] = data3;
                        }
                        if(Control.selectTDetail(TransactionDetail.Tipe.IUSTransaction, setTDetailIds).paymentMethod == TransactionDetail.PaymentMethod.IDD){
                            data4 += Control.selectTDetail(TransactionDetail.Tipe.IUSTransaction, setTDetailIds).amount;
                            data[j][4] = data4;
                        }
                        if(Control.selectTDetail(TransactionDetail.Tipe.IUSTransaction, setTDetailIds).paymentMethod == TransactionDetail.PaymentMethod.BEASISWA){
                            data5 += Control.selectTDetail(TransactionDetail.Tipe.IUSTransaction, setTDetailIds).amount;
                            data[j][5] = data5;
                        }
                        if(Control.selectTDetail(TransactionDetail.Tipe.IUSTransaction, setTDetailIds).paymentMethod == TransactionDetail.PaymentMethod.BEASISWA_COST){
                            data6 += Control.selectTDetail(TransactionDetail.Tipe.IUSTransaction, setTDetailIds).amount;
                            data[j][6] = data6;
                        }
                    }
                    if(data[j][3] == null){
                        data[j][3] = 0f;
                    }
                    if(data[j][4] == null){
                        data[j][4] = 0f;
                    }
                    if(data[j][5] == null){
                        data[j][5] = 0f;
                    }
                    if(data[j][6] == null){
                        data[j][6] = 0f;
                    }
                            
                }else{
                    data[j][2] = new Boolean(false);
                    if(entry.getValue().entries.get(j).transactDetailIDs.size() > 0){
                        for(Long setTDetailIds:entry.getValue().entries.get(j).transactDetailIDs){
                            System.out.println(setTDetailIds + " Set TDetailsID");
                            if(Control.selectTDetail(TransactionDetail.Tipe.IUSTransaction, setTDetailIds).paymentMethod == TransactionDetail.PaymentMethod.CASH){
                                data[j][3] = Control.selectTDetail(TransactionDetail.Tipe.IUSTransaction, setTDetailIds).amount;
                            }
                            if(Control.selectTDetail(TransactionDetail.Tipe.IUSTransaction, setTDetailIds).paymentMethod == TransactionDetail.PaymentMethod.IDD){
                                data[j][4] = Control.selectTDetail(TransactionDetail.Tipe.IUSTransaction, setTDetailIds).amount;
                            }
                            if(Control.selectTDetail(TransactionDetail.Tipe.IUSTransaction, setTDetailIds).paymentMethod == TransactionDetail.PaymentMethod.BEASISWA){
                                data[j][5] = Control.selectTDetail(TransactionDetail.Tipe.IUSTransaction, setTDetailIds).amount;
                            }
                            if(Control.selectTDetail(TransactionDetail.Tipe.IUSTransaction, setTDetailIds).paymentMethod == TransactionDetail.PaymentMethod.BEASISWA_COST){
                                data[j][6] = Control.selectTDetail(TransactionDetail.Tipe.IUSTransaction, setTDetailIds).amount;
                            }
                        }
                        if(data[j][3] == null){
                        data[j][3] = 0f;
                        }
                        if(data[j][4] == null){
                            data[j][4] = 0f;
                        }
                        if(data[j][5] == null){
                            data[j][5] = 0f;
                        }
                        if(data[j][6] == null){
                            data[j][6] = 0f;
                        }
                    }else{
                        data[j][3]=0f;
                        data[j][4]=0f;
                        data[j][5]=0f;
                        data[j][6]=0f;
                    }
                }
                
                iusFromDB.entries.add(entry.getValue().entries.get(j));
                //canEdit[j] = (entry.getValue().entries.get(j).transactDetailIDs.size() > 0);
                
                for(Long id : entry.getValue().entries.get(j).transactDetailIDs){
                    canEdit[j] = Control.selectTDetail(TransactionDetail.Tipe.IUSTransaction, id).settled;
                }
                
                
            }
            iusFromDB.id = entry.getValue().id;
            iusFromDB.noInduk = entry.getValue().noInduk;
            iusFromDB.chargedLevel = entry.getValue().chargedLevel;
            i++;
        }
        TableModel tm = new DefaultTableModel(data, columnNames){
            boolean[] chooseEdit = new boolean[]{false,false,true,true,true,true,true};
            
           @Override
            public boolean isCellEditable(int row, int column) {
                //all cells false for editable
                if(!itfs.jDialogTransactionSummary.isVisible()){
                    if((Boolean)getValueAt(row, 2)){
                    //if((Float)getValueAt(row,1) == 0f){
                        if((column == 0 || column ==1)){
                            return column == 2;
                        //return false;
                        }
                        return !canEdit[row];
                    }
                    if((column == 0 && column ==1)|| column == 2){
                            //return column == 2;
                        return chooseEdit[column];
                    }

                    return false;
               }else{
                    return false;
                }
            }
            public Class getColumnClass(int c) {
                return getValueAt(0, c).getClass();
            }
       };
       
       return tm;
       }else{
           TableModel tm = new DefaultTableModel(data, columnNames);
           JOptionPane.showMessageDialog(rootPane, "IUS Belum Di Setting!\r\n");
           this.dispose();
           return null;
       }
       
       
    }
    public TableModel buildIUSSubmitTableModel(Profil profil, int tahun) throws SQLException, KasirException {
       String columnNames[] = {"Semester", "Biaya IUS", "Check Box", "Tunai", "Iuran Dibayar Dimuka", "Beasiswa", "Beasiswa Yayasan"};
       Object[][] data = new Object[4][7];
       
       final boolean[] canEdit = new boolean [4];
         
        for(int i = 0 ; i < iusCurrent.entries.size(); i++){
                data[i][0]= namaBulan[i];//entry.getValue().entries.get(j).period;
                data[i][1]= iusFromDB.entries.get(i).amount; // ANEH NIH MASA BEGINI, DI KALI DUA SIH?
                if(iusCurrent.entries.get(i) != null){
//                    if(jTableIUS != null){
//                        data[j][2]=jTableIUS.getValueAt(j,2);
//                    }else{
                        data[i][2] = new Boolean(true);
//                        data[i][3] = iusFromDB.entries.get(i).amount-(iDDAmounts.get(i)+beasiswaAmounts.get(i)+beasiswaCostAmounts.get(i));
                        data[i][3] = iUSAmounts.get(i);
                        data[i][4] = iDDAmounts.get(i);
                        data[i][5] = beasiswaAmounts.get(i);
                        data[i][6] = beasiswaCostAmounts.get(i);
//                    }
                }else{
//                    if(jTableIUS !=null){
//                        data[j][2]=jTableIUS.getValueAt(j,2);
//                    }else{
                        data[i][2] = new Boolean(false);
//                        data[i][3] = iusFromDB.entries.get(i).amount-(iDDAmounts.get(i)+beasiswaAmounts.get(i)+beasiswaCostAmounts.get(i));
                        data[i][3] = iUSAmounts.get(i);
                        data[i][4] = iDDAmounts.get(i);
                        data[i][5] = beasiswaAmounts.get(i);
                        data[i][6] = beasiswaCostAmounts.get(i);
//                    }
                }
       }
       
       TableModel tm = new DefaultTableModel(data, columnNames){
            boolean[] chooseEdit = new boolean[]{false,false,true};
            
           @Override
            public boolean isCellEditable(int row, int column) {
                //all cells false for editable
                if(!itfs.jDialogTransactionSummary.isVisible()){
                    if((Boolean)getValueAt(row, 2)){
                        if((column == 0 || column ==1)){
                            return column == 2;
                        //return false;
                        }
                        return !canEdit[row];
                    }
                    if((column == 0 && column ==1)|| column == 2){
                            //return column == 2;
                        return chooseEdit[column];
                    }

                    return false;
               }else{
                    return false;
                }
            }
            public Class getColumnClass(int c) {
                return getValueAt(0, c).getClass();
            }
       };
       
       return tm;
    }
    
private ComboBoxModel buildIUStahunComboBoxModel(Profil profil) throws SQLException, KasirException {
       Set<IUS> iusFilters = new HashSet<>();
       ArrayList<Entry> entries = new ArrayList();
       iusFilters.add(new IUS(profil.noInduk, null, entries));
       Map<Long, IUS> searchResultMap = Control.exactFilterSelectIurans(Iuran.Tipe.IUS, iusFilters);
       this.tahunIUS = new ArrayList<>();
       List<String> tahunAjaran = new ArrayList<>();
       Object[][] data = new Object[searchResultMap.size()][2];
       int i = 0;
       if(searchResultMap.size() > 0){
        for(Map.Entry<Long, IUS> entry: searchResultMap.entrySet()){
            data[i][0]= entry.getValue().entries.get(i);
            data[i][1]= entry.getValue().entries.get(i).amount;
            this.tahunIUS.add(entry.getValue().chargedLevel.tahun);
            tahunAjaran.add(String.valueOf(entry.getValue().chargedLevel.tahun).concat(" - ").concat(String.valueOf(entry.getValue().chargedLevel.tahun+1)));
            i++;
        }
       }
       calculateUnpaidIUS(profil, tahunIUS);
       //== bikin tunggakan beans ===
       
       
       //== end bikin tunggakan beans ===
       
       tahunComboBoxModel = new DefaultComboBoxModel(tahunAjaran.toArray());
       return tahunComboBoxModel;
    }

private float calculateUnpaidIUS(Profil profil, List<Integer> tahuns) throws SQLException, KasirException {
       Set<IUS> iusFilters = new HashSet<>();
       float retVal = 0;
       ArrayList<Entry> entries = new ArrayList<>();
       iusFilters.clear();
       int targetMonth = Calendar.getInstance().get(Calendar.MONTH);
       int targetYear = Calendar.getInstance().get(Calendar.YEAR);
       if(targetMonth>5){//JULY - DECEMBER
           targetMonth = targetMonth - 5;
       }else{//JANUARY - JUNE
           targetMonth = targetMonth + 7;
           targetYear = targetYear - 1;
       }
       System.out.println("Month INT: "+Calendar.getInstance().get(Calendar.MONTH));
       for(int i = 0; i< tahuns.size(); i++){
           iusFilters.add(new IUS(profil.noInduk, new Level(null,null,null,tahuns.get(i)), entries));
           
        }
       Map<Long, IUS> searchResultMap = Control.exactFilterSelectIurans(Iuran.Tipe.IUS, iusFilters);
        if(searchResultMap.size() > 0){
            for(Map.Entry<Long, IUS> entry: searchResultMap.entrySet()){
                for(int j =0 ; j< entry.getValue().entries.size(); j++){
                    if((entry.getValue().entries.get(j).transactDetailIDs.isEmpty()) 
                            && ((entry.getValue().chargedLevel.tahun < targetYear)? true:(entry.getValue().entries.get(j).period <= targetMonth))){
                        retVal += entry.getValue().entries.get(j).amount;
                    }else if(entry.getValue().entries.get(j).transactDetailIDs.size() > 0){
                        Float temp = 0f;
                        for(Long l : entry.getValue().entries.get(j).transactDetailIDs){
                            temp += Control.selectTDetail(TransactionDetail.Tipe.IUSTransaction, l).amount;
                        }
                        if(temp < entry.getValue().entries.get(j).amount){
                            retVal += entry.getValue().entries.get(j).amount-temp;
                        } 
                    }
                }
            }
        }
       unpaidIUS = retVal;
       return retVal;
    }
    
    public ArrayList<TunggakanBean> calculateUnpaidIUSs(ArrayList<Profil> profils, List<Integer> tahuns) throws SQLException, KasirException {
       Set<IUS> iusFilters = new HashSet<>();
       ArrayList<TunggakanBean> retVals = new ArrayList<>();
       float retVal = 0;
       ArrayList<Entry> entries = new ArrayList<>();
       iusFilters.clear();
       int targetMonth = Calendar.getInstance().get(Calendar.MONTH);
       int targetYear = Calendar.getInstance().get(Calendar.YEAR);
       if(targetMonth>5){//JULY - DECEMBER
           targetMonth = targetMonth - 5;
       }else{//JANUARY - JUNE
           targetMonth = targetMonth + 7;
           targetYear = targetYear - 1;
       }
       System.out.println("Month INT: "+Calendar.getInstance().get(Calendar.MONTH));
       ArrayList<String> noInduks = new ArrayList<>();
       for(int i = 0; i< profils.size() ; i++){
           noInduks.add(profils.get(i).noInduk);
            for(int j = 0; j< tahuns.size(); j++){
                iusFilters.add(new IUS(profils.get(i).noInduk, new Level(null,null,null,tahuns.get(j)), entries));

            }
       }
       List<IUS> test = Control.selectIurans(Iuran.Tipe.IUS, IUS.noIndukColName, false, noInduks.toArray(new String[0]));
       
       for(int i = 0 ; i< test.size(); i++){
           TunggakanBean tb = new TunggakanBean();
           for(int j = 0 ; j < test.get(i).entries.size(); j++){
               if(j==0) retVal=0;
               Float totalAmountIUSTDetails = 0f;
               for(Long l : test.get(i).entries.get(j).transactDetailIDs){
                   totalAmountIUSTDetails += Control.selectTDetail(TransactionDetail.Tipe.IUSTransaction, l).amount;
               }
               if((totalAmountIUSTDetails < test.get(i).entries.get(j).amount)
                   && ((test.get(i).chargedLevel.tahun < targetYear? true: (test.get(i).entries.get(j).period <= targetMonth)))){
                    
                            
                            retVal += test.get(i).entries.get(j).amount-totalAmountIUSTDetails;
                            tunggakanIUSString = tunggakanIUSString.concat("IUS Semester ");
                            tunggakanIUSString = tunggakanIUSString.concat(getMonthName(test.get(i).entries.get(j).period));
                            tunggakanIUSString = tunggakanIUSString.concat(" "+String.valueOf(test.get(i).chargedLevel.tahun)+"/"+String.valueOf(1+test.get(i).chargedLevel.tahun));
                            tunggakanIUSString = tunggakanIUSString.concat("\r\n");
                            
                            tunggakanIUSEachAmountString = tunggakanIUSEachAmountString.concat("Rp. ");
                            tunggakanIUSEachAmountString = tunggakanIUSEachAmountString.concat(String.valueOf(Math.round(test.get(i).entries.get(j).amount-totalAmountIUSTDetails)));
                            tunggakanIUSEachAmountString = tunggakanIUSEachAmountString.concat("\r\n");
               }
               
                
               
               
           }
           tb.setProfil(profils.get(i));
           tb.setTunggakanIUS(retVal);
           retVals.add(tb);
           System.out.println(test.get(i).noInduk);
       }
       unpaidIUS = retVal;
       return retVals;
    }
   
    private String getMonthName(int p){
        String ret;
        switch(p){
            case 1: ret = "MID SEMESTER 1";
                break;
            case 2: ret = "UJIAN SEMESTER 1";
                break;
            case 3: ret = "MID SEMESTER 2";
                break;
            case 4: ret = "UJIAN SEMESTER 2";
                break;
            default: ret = "Invalid";
                break;
        }
        return ret;
        
    }

    public boolean isIUSEnough(Set<Long> transactDetailIDs, float amountIUSinTable) throws SQLException, KasirException {
        Float totalAmountTDetail = 0f;
        for(Long l : transactDetailIDs){
            totalAmountTDetail += Control.selectTDetail(TransactionDetail.Tipe.IUSTransaction, l).amount;
        }
        if(totalAmountTDetail < amountIUSinTable){
            return false;
        }else{
            return true;
        }
    }
    
    
    public float calculatePaidIUS(Set<Long> transactDetailIDs) throws SQLException, KasirException{
        Float retVal = 0f;
        for(Long l: transactDetailIDs){
            retVal += Control.selectTDetail(TransactionDetail.Tipe.IUSTransaction, l).amount;
        }
        return retVal;
    }
    
}
