/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import iuran.IPSB;
import iuran.Iuran;
import java.sql.SQLException;
import java.text.ParseException;
import javax.swing.JOptionPane;
import kasir.Control;
import org.openide.util.Exceptions;
import pelajar.Profil;
import sak.KasirException;

/**
 *
 * @author Master
 */
public class InputTransactionIPSB extends javax.swing.JFrame {
    private IPSB ipsb;
    private float minIPSB;
    private float maxIPSB;
    private InputTransactionFrameSeparated itfs;
    private Profil profil;
    /**
     * Creates new form InputTransactionIPSB
     */
    public InputTransactionIPSB(Profil profil, InputTransactionFrameSeparated itfs) {
        try {
            this.ipsb = Control.selectIuran(Iuran.Tipe.IPSB, IPSB.noIndukColName, false, profil.noInduk);
            minIPSB = 0F;
            maxIPSB = this.ipsb.amount - this.ipsb.totalInstallment;
            this.itfs = itfs;
            this.profil = profil;
        } catch (SQLException ex) {
            Exceptions.printStackTrace(ex);
            JOptionPane.showMessageDialog(rootPane, "IPSB Belum Di Setting!\r\n".concat(profil.biodata.nama+"\r\n").concat(ex.toString()));
            this.dispose();
        } catch (KasirException ex) {
            Exceptions.printStackTrace(ex);
            JOptionPane.showMessageDialog(rootPane, "IPSB Belum Di Setting!\r\n".concat(profil.biodata.nama+"\r\n").concat(ex.toString()));
            this.dispose();
        }
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelIPSP = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldIPSBAmount = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldIPSBNote = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextFieldIPSBIuranAmount = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jTextFieldIPSBSisaAmount = new javax.swing.JTextField();
        jButtonIPSBOK = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(480, 500));

        jPanelIPSP.setMinimumSize(new java.awt.Dimension(440, 480));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText(org.openide.util.NbBundle.getMessage(InputTransactionIPSB.class, "InputTransactionIPSB.jLabel1.text")); // NOI18N

        jLabel3.setText(org.openide.util.NbBundle.getMessage(InputTransactionIPSB.class, "InputTransactionIPSB.jLabel3.text")); // NOI18N

        jTextFieldIPSBAmount.setText(org.openide.util.NbBundle.getMessage(InputTransactionIPSB.class, "InputTransactionIPSB.jTextFieldIPSBAmount.text")); // NOI18N
        jTextFieldIPSBAmount.setName(org.openide.util.NbBundle.getMessage(InputTransactionIPSB.class, "InputTransactionIPSB.jTextFieldIPSBAmount.name")); // NOI18N
        jTextFieldIPSBAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIPSBAmountActionPerformed(evt);
            }
        });
        jTextFieldIPSBAmount.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldIPSBAmountFocusLost(evt);
            }
        });
        jTextFieldIPSBAmount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldIPSBAmountKeyTyped(evt);
            }
        });

        jLabel5.setText(org.openide.util.NbBundle.getMessage(InputTransactionIPSB.class, "InputTransactionIPSB.jLabel5.text")); // NOI18N

        jTextFieldIPSBNote.setText(org.openide.util.NbBundle.getMessage(InputTransactionIPSB.class, "InputTransactionIPSB.jTextFieldIPSBNote.text")); // NOI18N

        jLabel13.setText(org.openide.util.NbBundle.getMessage(InputTransactionIPSB.class, "InputTransactionIPSB.jLabel13.text")); // NOI18N

        jTextFieldIPSBIuranAmount.setEditable(false);
        jTextFieldIPSBIuranAmount.setText(String.valueOf(ipsb.amount));
        jTextFieldIPSBIuranAmount.setFocusable(false);
        jTextFieldIPSBIuranAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIPSBIuranAmountActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel17.setText(org.openide.util.NbBundle.getMessage(InputTransactionIPSB.class, "InputTransactionIPSB.jLabel17.text")); // NOI18N

        jTextFieldIPSBSisaAmount.setEditable(false);
        jTextFieldIPSBSisaAmount.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jTextFieldIPSBSisaAmount.setText(String.valueOf(maxIPSB));
        jTextFieldIPSBSisaAmount.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldIPSBSisaAmount.setFocusable(false);
        jTextFieldIPSBSisaAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIPSBSisaAmountActionPerformed(evt);
            }
        });

        jButtonIPSBOK.setText(org.openide.util.NbBundle.getMessage(InputTransactionIPSB.class, "InputTransactionIPSB.jButtonIPSBOK.text")); // NOI18N
        jButtonIPSBOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIPSBOKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelIPSPLayout = new javax.swing.GroupLayout(jPanelIPSP);
        jPanelIPSP.setLayout(jPanelIPSPLayout);
        jPanelIPSPLayout.setHorizontalGroup(
            jPanelIPSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelIPSPLayout.createSequentialGroup()
                .addGroup(jPanelIPSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanelIPSPLayout.createSequentialGroup()
                        .addGroup(jPanelIPSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel13))
                        .addGap(11, 11, 11)
                        .addGroup(jPanelIPSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldIPSBNote, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelIPSPLayout.createSequentialGroup()
                                .addGroup(jPanelIPSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jTextFieldIPSBAmount, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldIPSBIuranAmount, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel17)
                                .addGap(12, 12, 12)
                                .addComponent(jTextFieldIPSBSisaAmount, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE))))
                    .addGroup(jPanelIPSPLayout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(jButtonIPSBOK)))
                .addContainerGap())
        );
        jPanelIPSPLayout.setVerticalGroup(
            jPanelIPSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelIPSPLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(4, 4, 4)
                .addGroup(jPanelIPSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jTextFieldIPSBIuranAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(jTextFieldIPSBSisaAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelIPSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldIPSBAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanelIPSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldIPSBNote, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonIPSBOK)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 495, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(33, Short.MAX_VALUE)
                    .addComponent(jPanelIPSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 313, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanelIPSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(72, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldIPSBAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIPSBAmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIPSBAmountActionPerformed

    private void jTextFieldIPSBAmountFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldIPSBAmountFocusLost
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTextFieldIPSBAmountFocusLost

    private void jTextFieldIPSBAmountKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldIPSBAmountKeyTyped
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTextFieldIPSBAmountKeyTyped

    private void jTextFieldIPSBIuranAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIPSBIuranAmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIPSBIuranAmountActionPerformed

    private void jTextFieldIPSBSisaAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIPSBSisaAmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIPSBSisaAmountActionPerformed

    private void jButtonIPSBOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIPSBOKActionPerformed
        // TODO add your handling code here:
        itfs.jTextFieldIPSBAmountSimple.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0"))));

        try {
            itfs.jTextFieldIPSBAmountSimple.setValue(Float.valueOf(jTextFieldIPSBAmount.getText()));
            itfs.jTextFieldIPSBAmountSimple.commitEdit();
        } catch (ParseException ex) {
            Exceptions.printStackTrace(ex);
        }
//        try {
//            ipsb = Control.selectIuran(Iuran.Tipe.IPSB, IPSB.noIndukColName, false, profil.noInduk);
//            itfs.ipsb = ipsb;
//        } catch (SQLException ex) {
//            //idd = null;
//        } catch (KasirException ex) {
//            //idd = null;
//        }
        this.setVisible(false);
    }//GEN-LAST:event_jButtonIPSBOKActionPerformed

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonIPSBOK;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanelIPSP;
    public javax.swing.JTextField jTextFieldIPSBAmount;
    private javax.swing.JTextField jTextFieldIPSBIuranAmount;
    public javax.swing.JTextField jTextFieldIPSBNote;
    private javax.swing.JTextField jTextFieldIPSBSisaAmount;
    // End of variables declaration//GEN-END:variables
}
