/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import iuran.*;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.*;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import kasir.Control;
import org.openide.util.Exceptions;
import pelajar.Level;
import pelajar.Profil;
import printout.TunggakanBean;
import sak.KasirException;

/**
 *
 * @author Master
 */
public class InputTransactionIUAP extends javax.swing.JFrame {
    Profil profil;
    private TableModel tableModelIUAP;
    private IUAP iuapFromDB;
    private List<Integer> tahunIUAP;
    private ArrayList<Float> iDDAmounts;
    public ArrayList<Float> beasiswaAmounts;
    public ArrayList<Float> beasiswaCostAmounts;
    public ArrayList<Float> iUAPAmounts;
    private IUAP iuapCurrent;
    private IUAP iuapStoreToDB;
    private float iuapDebt;
    private IDD idd;
    private InputTransactionFrameSeparated itfs;
    private final String[] namaBulan = {"JULI", "AGUSTUS", "SEPTEMBER", "OKTOBER", "NOPEMBER", "DESEMBER", "JANUARI", "PEBRUARI", "MARET", "APRIL", "MEI", "JUNI"};
    private float unpaidIUAP;
    private ComboBoxModel tahunComboBoxModel;
    private String tunggakanIUAPString = new String("");
    private String tunggakanIUAPEachAmountString = new String("");
    /**
     * Creates new form InputTransactionIUAP
     */
    
    public InputTransactionIUAP(Profil profil, InputTransactionFrameSeparated itfs) {
        this.profil = profil;
        this.itfs = itfs;
        try {
            tableModelIUAP = buildIUAPTableModel(profil, profil.currentLevel.tahun);
        } catch (SQLException ex) {
            Exceptions.printStackTrace(ex);
        } catch (KasirException ex) {
            Exceptions.printStackTrace(ex);
        }
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelIUAP = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabelTahun = new javax.swing.JLabel();
        jComboBoxTahun = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jUnpaidIUAP = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTableIUAP = new javax.swing.JTable();
        jButtonBayarIUAP = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jFormattedTextFieldIDDSaldo = new javax.swing.JFormattedTextField();
        jTextFieldIUAPDebt = new javax.swing.JFormattedTextField();

        setTitle(org.openide.util.NbBundle.getMessage(InputTransactionIUAP.class, "InputTransactionIUAP.title")); // NOI18N

        jPanelIUAP.setMinimumSize(new java.awt.Dimension(570, 380));
        jPanelIUAP.setPreferredSize(new java.awt.Dimension(680, 450));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText(org.openide.util.NbBundle.getMessage(InputTransactionIUAP.class, "InputTransactionIUAP.jLabel1.text")); // NOI18N

        jLabelTahun.setText(org.openide.util.NbBundle.getMessage(InputTransactionIUAP.class, "InputTransactionIUAP.jLabelTahun.text")); // NOI18N

        try{
            tahunComboBoxModel = buildIUAPtahunComboBoxModel(profil);
        }catch(SQLException ex){
            ex.printStackTrace();
        }catch(KasirException ex){
            ex.printStackTrace();
        }
        jComboBoxTahun.setModel(tahunComboBoxModel);
        jComboBoxTahun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTahunActionPerformed(evt);
            }
        });
        jComboBoxTahun.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jComboBoxTahunPropertyChange(evt);
            }
        });

        jLabel2.setText(org.openide.util.NbBundle.getMessage(InputTransactionIUAP.class, "InputTransactionIUAP.jLabel2.text")); // NOI18N

        jUnpaidIUAP.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jUnpaidIUAP.setText(String.valueOf(unpaidIUAP));
        jUnpaidIUAP.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jUnpaidIUAP.setEnabled(false);

        jTableIUAP.setModel(tableModelIUAP);
        jTableIUAP.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jTableIUAP.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTableIUAPFocusLost(evt);
            }
        });
        jTableIUAP.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jTableIUAPPropertyChange(evt);
            }
        });
        jScrollPane5.setViewportView(jTableIUAP);

        jButtonBayarIUAP.setText(org.openide.util.NbBundle.getMessage(InputTransactionIUAP.class, "InputTransactionIUAP.jButtonBayarIUAP.text")); // NOI18N
        jButtonBayarIUAP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBayarIUAPActionPerformed(evt);
            }
        });

        jLabel3.setText(org.openide.util.NbBundle.getMessage(InputTransactionIUAP.class, "InputTransactionIUAP.jLabel3.text")); // NOI18N

        jFormattedTextFieldIDDSaldo.setText(org.openide.util.NbBundle.getMessage(InputTransactionIUAP.class, "InputTransactionIUAP.jFormattedTextFieldIDDSaldo.text")); // NOI18N
        jFormattedTextFieldIDDSaldo.setEnabled(false);

        jTextFieldIUAPDebt.setEditable(false);
        jTextFieldIUAPDebt.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0"))));

        javax.swing.GroupLayout jPanelIUAPLayout = new javax.swing.GroupLayout(jPanelIUAP);
        jPanelIUAP.setLayout(jPanelIUAPLayout);
        jPanelIUAPLayout.setHorizontalGroup(
            jPanelIUAPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelIUAPLayout.createSequentialGroup()
                .addGroup(jPanelIUAPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelIUAPLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane5))
                    .addGroup(jPanelIUAPLayout.createSequentialGroup()
                        .addGroup(jPanelIUAPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelIUAPLayout.createSequentialGroup()
                                .addGap(248, 248, 248)
                                .addComponent(jButtonBayarIUAP))
                            .addGroup(jPanelIUAPLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1)
                                .addGap(29, 29, 29)
                                .addComponent(jLabelTahun)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanelIUAPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jComboBoxTahun, 0, 101, Short.MAX_VALUE)
                                    .addComponent(jTextFieldIUAPDebt))
                                .addGap(82, 82, 82)
                                .addGroup(jPanelIUAPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(jPanelIUAPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jUnpaidIUAP, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                                    .addComponent(jFormattedTextFieldIDDSaldo))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelIUAPLayout.setVerticalGroup(
            jPanelIUAPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelIUAPLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanelIUAPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxTahun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTahun)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jUnpaidIUAP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelIUAPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jFormattedTextFieldIDDSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldIUAPDebt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonBayarIUAP)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelIUAP, javax.swing.GroupLayout.DEFAULT_SIZE, 570, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelIUAP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxTahunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTahunActionPerformed
        // TODO add your handling code here:
        try {
            this.tableModelIUAP = (DefaultTableModel) buildIUAPTableModel(this.profil, this.tahunIUAP.get(jComboBoxTahun.getSelectedIndex()));
            jTableIUAP.setModel(this.tableModelIUAP);
            jTextFieldIUAPDebt.setValue(iuapDebt);
        } catch (SQLException ex) {
            ex.printStackTrace();
        } catch (KasirException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jComboBoxTahunActionPerformed

    private void jComboBoxTahunPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jComboBoxTahunPropertyChange
        // TODO add your handling code here:
        try {
            if (this.jComboBoxTahun.getSelectedItem() != null) {
                this.tableModelIUAP = (DefaultTableModel) buildIUAPTableModel(this.profil, this.tahunIUAP.get(jComboBoxTahun.getSelectedIndex()));
                jTableIUAP.setModel(this.tableModelIUAP);
                jTextFieldIUAPDebt.setValue(iuapDebt);
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(rootPane, "Koneksi Error!\r\n".concat(ex.toString()));
        } catch (KasirException ex) {
            JOptionPane.showMessageDialog(rootPane, "IUAP Belum Di Setting!\r\n".concat(ex.toString()));
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jComboBoxTahunPropertyChange

    private void jTableIUAPFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTableIUAPFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTableIUAPFocusLost

    private void jTableIUAPPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jTableIUAPPropertyChange
        // TODO add your handling code here:
        //IDD, Beasiswa, Beasiswa Cost
        iUAPAmounts = new ArrayList();
        iDDAmounts = new ArrayList();
        beasiswaAmounts = new ArrayList();
        beasiswaCostAmounts = new ArrayList();
        /////BLOOOOOOOOOOM SELESAIIIIIIIIIIIIIIIIIIII
        int i = 0;
        iuapCurrent = new IUAP();
        iuapStoreToDB = new IUAP();
        ArrayList<Entry> entry = new ArrayList<>();
        if (iuapFromDB.entries.size() != 0) {
            for (i = 0; i < jTableIUAP.getRowCount(); i++) {
                iuapCurrent.entries.add((Boolean) jTableIUAP.getValueAt(i, 2) ? ((iuapFromDB.entries.get(i).transactDetailIDs.size() > 0) ? new Entry(i, iuapFromDB.entries.get(i).amount, iuapFromDB.entries.get(i).debt, iuapFromDB.entries.get(i).transactDetailIDs) : new Entry(i, iuapFromDB.entries.get(i).amount)) : null);
                //below condition is when jTableIUAP checkBox is UNCHECK ????
                if (iuapCurrent.entries.get(i) == null) {
                    iuapStoreToDB.entries.add(null);
                    jTableIUAP.setValueAt(0f, i, 3);
                    jTableIUAP.setValueAt(0f, i, 4);
                    jTableIUAP.setValueAt(0f, i, 5);
                    jTableIUAP.setValueAt(0f, i, 6);
                    iUAPAmounts.add(0f);
                    iDDAmounts.add(0f);
                    beasiswaAmounts.add(0f);
                    beasiswaCostAmounts.add(0f);
                    //below is when jTableIUAP property changed, especially check box is Changed or Editing IDD, Beasiswa, Beasiswa Cost 
                } else if ((iuapCurrent.entries.get(i) != null) ^ (iuapFromDB.entries.get(i).transactDetailIDs.size() > 0)) {
                    System.out.println("IDD dari db ");
                    if (idd != null) {
                        System.out.println(idd.amount);
                    }
                    iUAPAmounts.add((Float) jTableIUAP.getModel().getValueAt(i,3));
                    iDDAmounts.add((Float) jTableIUAP.getValueAt(i, 4));
                    beasiswaAmounts.add((Float) jTableIUAP.getValueAt(i, 5));
                    beasiswaCostAmounts.add((Float) jTableIUAP.getValueAt(i, 6));
                    //jTableIUAP.setValueAt(iuapFromDB.entries.get(i).amount - (iDDAmounts.get(i) + beasiswaAmounts.get(i) + beasiswaCostAmounts.get(i)), i, 3);
                    //iuapStoreToDB.entries.add(new Entry(i, iuapFromDB.entries.get(i).amount));
                    iuapStoreToDB.entries.add(new Entry(i, iUAPAmounts.get(i)+iDDAmounts.get(i)+beasiswaAmounts.get(i)+beasiswaCostAmounts.get(i)));
                } else {
                    try {
                        if(isIUAPEnough(iuapFromDB.entries.get(i).transactDetailIDs, iuapFromDB.entries.get(i).amount)){
                            iUAPAmounts.add(0f);
                            iDDAmounts.add(0f);
                            beasiswaAmounts.add(0f);
                            beasiswaCostAmounts.add(0f);
                            iuapStoreToDB.entries.add(null);
                        }else{
                            iUAPAmounts.add((Float) jTableIUAP.getModel().getValueAt(i,3));
                            iDDAmounts.add((Float) jTableIUAP.getValueAt(i, 4));
                            beasiswaAmounts.add((Float) jTableIUAP.getValueAt(i, 5));
                            beasiswaCostAmounts.add((Float) jTableIUAP.getValueAt(i, 6));
                            iuapStoreToDB.entries.add(new Entry(i, iUAPAmounts.get(i)+iDDAmounts.get(i)+beasiswaAmounts.get(i)+beasiswaCostAmounts.get(i)));
                        }
                    } catch (SQLException ex) {
                        Exceptions.printStackTrace(ex);
                    } catch (KasirException ex) {
                        Exceptions.printStackTrace(ex);
                    }
                    

                }
                //iuapCurrent.entries.add((Boolean)jTableIUAP.getValueAt(i,2)? new IUAP(profil.noInduk, new Level(null,null,null,(Integer)jComboBoxTahun.getSelectedItem()),entry).entries.get(i): null);
                //iuapStoreToDB.entries.add(iuapCurrent.entries.get(i)==null?null:(((iuapCurrent.entries.get(i)!=null)^(iuapFromDB.entries.get(i)!=null))? new IUAP(profil.noInduk, new Level(null,null,null,(int)jComboBoxTahun.getSelectedItem()),entry).entries.get(i):iuapCurrent.entries.get(i)));
                //System.out.println("IUAP Period: "+iuapCurrent.entries.get(i).period);
            }
        }
    }//GEN-LAST:event_jTableIUAPPropertyChange

    private void jButtonBayarIUAPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBayarIUAPActionPerformed
        // TODO add your handling code here:
        float iuapAmountTemp = 0f;
        for (int i = 0; i < 12; i++) {
            if (iuapStoreToDB.entries.get(i) != null) {
                //iuapAmountTemp = iuapAmountTemp + iuapFromDB.entries.get(i).amount;
                iuapAmountTemp = iuapAmountTemp + (Float)jTableIUAP.getModel().getValueAt(i,3)
                                +(Float)jTableIUAP.getModel().getValueAt(i,4)
                                +(Float)jTableIUAP.getModel().getValueAt(i,5)
                                +(Float)jTableIUAP.getModel().getValueAt(i,6);
            }
        }
        itfs.jTextFieldIUAAmountSimple.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0"))));
        itfs.jTextFieldIUAAmountSimple.setValue(iuapAmountTemp);
        try {
            itfs.jTextFieldIUAAmountSimple.commitEdit();
        } catch (ParseException ex) {
            Exceptions.printStackTrace(ex);
        }
        itfs.iuapCurrent = iuapCurrent;
        itfs.iuapFromDB = iuapFromDB;
        itfs.iuapStoreToDB = iuapStoreToDB;
        this.setVisible(false);

    }//GEN-LAST:event_jButtonBayarIUAPActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InputTransactionFrameSeparated.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InputTransactionFrameSeparated.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InputTransactionFrameSeparated.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InputTransactionFrameSeparated.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                //new InputTransactionIUAP().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBayarIUAP;
    private javax.swing.JComboBox jComboBoxTahun;
    private javax.swing.JFormattedTextField jFormattedTextFieldIDDSaldo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelTahun;
    private javax.swing.JPanel jPanelIUAP;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTableIUAP;
    private javax.swing.JFormattedTextField jTextFieldIUAPDebt;
    private javax.swing.JTextField jUnpaidIUAP;
    // End of variables declaration//GEN-END:variables

    public TableModel buildIUAPTableModel(Profil profil, int tahun) throws SQLException, KasirException {
       String columnNames[] = {"Bulan", "Biaya IUAP", "Check Box", "Tunai", "Iuran Dibayar Dimuka", "Beasiswa", "Beasiswa Yayasan"};
       Set<IUAP> iuapFilters = new HashSet<>();
       ArrayList<Entry> entries = new ArrayList<>();
       iuapFilters.clear();
       iuapFilters.add(new IUAP(profil.noInduk, new Level(null,null,null,tahun), entries));
       Map<Long, IUAP> searchResultMap = Control.exactFilterSelectIurans(Iuran.Tipe.IUAP, iuapFilters);
       Object[][] data = new Object[12][7];
       int i = 0;
       final boolean[] canEdit = new boolean [12];
       iuapFromDB = new IUAP();
       float amountIUAPinTable;
       float amountIUAPinTDetail;
       iuapDebt = 0f;
       
       //Get Month and Year for calculate IuranPeriodic 12 times a year (Monthly)
       Calendar calendarRunning = Calendar.getInstance();
       int targetMonth = calendarRunning.get(Calendar.MONTH);
       int targetYear = calendarRunning.get(Calendar.YEAR);
       if(targetMonth>5){//JULY - DECEMBER
           targetMonth = targetMonth - 5;
       }else{//JANUARY - JUNE
           targetMonth = targetMonth + 7;
           targetYear = targetYear - 1;
       }
       
       if(searchResultMap.size() > 0){
        for(Map.Entry<Long, IUAP> entry: searchResultMap.entrySet()){
            for(int j =0 ; j< entry.getValue().entries.size(); j++){
                data[j][0]= namaBulan[j];//entry.getValue().entries.get(j).period;
                data[j][1]= entry.getValue().entries.get(j).amount - calculatePaidIUAP(entry.getValue().entries.get(j).transactDetailIDs); // ANEH NIH MASA BEGINI, DI KALI DUA SIH?
                amountIUAPinTable = entry.getValue().entries.get(j).amount;
                if(entry.getValue().chargedLevel.tahun < targetYear){
                    iuapDebt += entry.getValue().entries.get(j).debt;
                }else if(entry.getValue().chargedLevel.tahun == targetYear && j < targetMonth){
                    iuapDebt += entry.getValue().entries.get(j).debt;
                }
                
                //if(jTable2 != null){data[j][2]= jTable2.getModel().getValueAt(j,2);}else{data[j][2]= new Boolean(false);}
                //if(entry.getValue().entries.get(j).transactDetailIDs.size() > 0){
                if(isIUAPEnough(entry.getValue().entries.get(j).transactDetailIDs, amountIUAPinTable)){        
//                    
                    data[j][2] = new Boolean(true);
                    Float data3 = 0f;
                    Float data4 = 0f;
                    Float data5 = 0f;
                    Float data6 = 0f;
                    
                    for(Long setTDetailIds:entry.getValue().entries.get(j).transactDetailIDs){
                        System.out.println(setTDetailIds + " Set TDetailsID");
                        if(Control.selectTDetail(TransactionDetail.Tipe.IUAPTransaction, setTDetailIds).paymentMethod == TransactionDetail.PaymentMethod.CASH){
                            data3 += Control.selectTDetail(TransactionDetail.Tipe.IUAPTransaction, setTDetailIds).amount;
                            data[j][3] = data3;
                        }
                        if(Control.selectTDetail(TransactionDetail.Tipe.IUAPTransaction, setTDetailIds).paymentMethod == TransactionDetail.PaymentMethod.IDD){
                            data4 += Control.selectTDetail(TransactionDetail.Tipe.IUAPTransaction, setTDetailIds).amount;
                            data[j][4] = data4;
                        }
                        if(Control.selectTDetail(TransactionDetail.Tipe.IUAPTransaction, setTDetailIds).paymentMethod == TransactionDetail.PaymentMethod.BEASISWA){
                            data5 += Control.selectTDetail(TransactionDetail.Tipe.IUAPTransaction, setTDetailIds).amount;
                            data[j][5] = data5;
                        }
                        if(Control.selectTDetail(TransactionDetail.Tipe.IUAPTransaction, setTDetailIds).paymentMethod == TransactionDetail.PaymentMethod.BEASISWA_COST){
                            data6 += Control.selectTDetail(TransactionDetail.Tipe.IUAPTransaction, setTDetailIds).amount;
                            data[j][6] = data6;
                        }
                    }
                    if(data[j][3] == null){
                        data[j][3] = 0f;
                    }
                    if(data[j][4] == null){
                        data[j][4] = 0f;
                    }
                    if(data[j][5] == null){
                        data[j][5] = 0f;
                    }
                    if(data[j][6] == null){
                        data[j][6] = 0f;
                    }
                            
                }else{
                    data[j][2] = new Boolean(false);
                    if(entry.getValue().entries.get(j).transactDetailIDs.size() > 0){
                        for(Long setTDetailIds:entry.getValue().entries.get(j).transactDetailIDs){
                            System.out.println(setTDetailIds + " Set TDetailsID");
                            if(Control.selectTDetail(TransactionDetail.Tipe.IUAPTransaction, setTDetailIds).paymentMethod == TransactionDetail.PaymentMethod.CASH){
                                data[j][3] = Control.selectTDetail(TransactionDetail.Tipe.IUAPTransaction, setTDetailIds).amount;
                            }
                            if(Control.selectTDetail(TransactionDetail.Tipe.IUAPTransaction, setTDetailIds).paymentMethod == TransactionDetail.PaymentMethod.IDD){
                                data[j][4] = Control.selectTDetail(TransactionDetail.Tipe.IUAPTransaction, setTDetailIds).amount;
                            }
                            if(Control.selectTDetail(TransactionDetail.Tipe.IUAPTransaction, setTDetailIds).paymentMethod == TransactionDetail.PaymentMethod.BEASISWA){
                                data[j][5] = Control.selectTDetail(TransactionDetail.Tipe.IUAPTransaction, setTDetailIds).amount;
                            }
                            if(Control.selectTDetail(TransactionDetail.Tipe.IUAPTransaction, setTDetailIds).paymentMethod == TransactionDetail.PaymentMethod.BEASISWA_COST){
                                data[j][6] = Control.selectTDetail(TransactionDetail.Tipe.IUAPTransaction, setTDetailIds).amount;
                            }
                        }
                        if(data[j][3] == null){
                        data[j][3] = 0f;
                        }
                        if(data[j][4] == null){
                            data[j][4] = 0f;
                        }
                        if(data[j][5] == null){
                            data[j][5] = 0f;
                        }
                        if(data[j][6] == null){
                            data[j][6] = 0f;
                        }
                    }else{
                        data[j][3]=0f;
                        data[j][4]=0f;
                        data[j][5]=0f;
                        data[j][6]=0f;
                    }
                }
                
                iuapFromDB.entries.add(entry.getValue().entries.get(j));
                //canEdit[j] = (entry.getValue().entries.get(j).transactDetailIDs.size() > 0);
                
                for(Long id : entry.getValue().entries.get(j).transactDetailIDs){
                    canEdit[j] = Control.selectTDetail(TransactionDetail.Tipe.IUAPTransaction, id).settled;
                }
                
                
            }
            iuapFromDB.id = entry.getValue().id;
            iuapFromDB.noInduk = entry.getValue().noInduk;
            iuapFromDB.chargedLevel = entry.getValue().chargedLevel;
            i++;
            System.out.println("iuap debt "+String.valueOf(iuapDebt));
        }
        TableModel tm = new DefaultTableModel(data, columnNames){
            boolean[] chooseEdit = new boolean[]{false,false,true,true,true,true,true};
            
           @Override
            public boolean isCellEditable(int row, int column) {
                //all cells false for editable
                if(!itfs.jDialogTransactionSummary.isVisible()){
                    if((Boolean)getValueAt(row, 2)){
                    //if((Float)getValueAt(row,1) == 0f){
                        if((column == 0 || column ==1)){
                            return column == 2;
                        //return false;
                        }
                        return !canEdit[row];
                    }
                    if((column == 0 && column ==1)|| column == 2){
                            //return column == 2;
                        return chooseEdit[column];
                    }

                    return false;
               }else{
                    return false;
                }
            }
            public Class getColumnClass(int c) {
                return getValueAt(0, c).getClass();
            }
       };
       
       return tm;
       }else{
           TableModel tm = new DefaultTableModel(data, columnNames);
           JOptionPane.showMessageDialog(rootPane, "IUAP Belum Di Setting!\r\n");
           this.dispose();
           return null;
       }
       
       
    }
    public TableModel buildIUAPSubmitTableModel(Profil profil, int tahun) throws SQLException, KasirException {
       String columnNames[] = {"Bulan", "Biaya IUAP", "Check Box", "Tunai", "Iuran Dibayar Dimuka", "Beasiswa", "Beasiswa Yayasan"};
       Object[][] data = new Object[12][7];
       
       final boolean[] canEdit = new boolean [12];
         
        for(int i = 0 ; i < iuapCurrent.entries.size(); i++){
                data[i][0]= namaBulan[i];//entry.getValue().entries.get(j).period;
                data[i][1]= iuapFromDB.entries.get(i).amount; // ANEH NIH MASA BEGINI, DI KALI DUA SIH?
                if(iuapCurrent.entries.get(i) != null){
//                    if(jTableIUAP != null){
//                        data[j][2]=jTableIUAP.getValueAt(j,2);
//                    }else{
                        data[i][2] = new Boolean(true);
//                        data[i][3] = iuapFromDB.entries.get(i).amount-(iDDAmounts.get(i)+beasiswaAmounts.get(i)+beasiswaCostAmounts.get(i));
                        data[i][3] = iUAPAmounts.get(i);
                        data[i][4] = iDDAmounts.get(i);
                        data[i][5] = beasiswaAmounts.get(i);
                        data[i][6] = beasiswaCostAmounts.get(i);
//                    }
                }else{
//                    if(jTableIUAP !=null){
//                        data[j][2]=jTableIUAP.getValueAt(j,2);
//                    }else{
                        data[i][2] = new Boolean(false);
//                        data[i][3] = iuapFromDB.entries.get(i).amount-(iDDAmounts.get(i)+beasiswaAmounts.get(i)+beasiswaCostAmounts.get(i));
                        data[i][3] = iUAPAmounts.get(i);
                        data[i][4] = iDDAmounts.get(i);
                        data[i][5] = beasiswaAmounts.get(i);
                        data[i][6] = beasiswaCostAmounts.get(i);
//                    }
                }
       }
       
       TableModel tm = new DefaultTableModel(data, columnNames){
            boolean[] chooseEdit = new boolean[]{false,false,true};
            
           @Override
            public boolean isCellEditable(int row, int column) {
                //all cells false for editable
                if(!itfs.jDialogTransactionSummary.isVisible()){
                    if((Boolean)getValueAt(row, 2)){
                        if((column == 0 || column ==1)){
                            return column == 2;
                        //return false;
                        }
                        return !canEdit[row];
                    }
                    if((column == 0 && column ==1)|| column == 2){
                            //return column == 2;
                        return chooseEdit[column];
                    }

                    return false;
               }else{
                    return false;
                }
            }
            public Class getColumnClass(int c) {
                return getValueAt(0, c).getClass();
            }
       };
       
       return tm;
    }
    
private ComboBoxModel buildIUAPtahunComboBoxModel(Profil profil) throws SQLException, KasirException {
       Set<IUAP> iuapFilters = new HashSet<>();
       ArrayList<Entry> entries = new ArrayList();
       iuapFilters.add(new IUAP(profil.noInduk, null, entries));
       Map<Long, IUAP> searchResultMap = Control.exactFilterSelectIurans(Iuran.Tipe.IUAP, iuapFilters);
       this.tahunIUAP = new ArrayList<>();
       List<String> tahunAjaran = new ArrayList<>();
       Object[][] data = new Object[searchResultMap.size()][12];
       int i = 0;
       if(searchResultMap.size() > 0){
        for(Map.Entry<Long, IUAP> entry: searchResultMap.entrySet()){
            data[i][0]= entry.getValue().entries.get(i);
            data[i][1]= entry.getValue().entries.get(i).amount;
            this.tahunIUAP.add(entry.getValue().chargedLevel.tahun);
            tahunAjaran.add(String.valueOf(entry.getValue().chargedLevel.tahun).concat(" - ").concat(String.valueOf(entry.getValue().chargedLevel.tahun+1)));
            i++;
        }
       }
       calculateUnpaidIUAP(profil, tahunIUAP);
       //== bikin tunggakan beans ===
       
       
       //== end bikin tunggakan beans ===
       
       tahunComboBoxModel = new DefaultComboBoxModel(tahunAjaran.toArray());
       return tahunComboBoxModel;
    }

private float calculateUnpaidIUAP(Profil profil, List<Integer> tahuns) throws SQLException, KasirException {
       Set<IUAP> iuapFilters = new HashSet<>();
       float retVal = 0;
       ArrayList<Entry> entries = new ArrayList<>();
       iuapFilters.clear();
       int targetMonth = Calendar.getInstance().get(Calendar.MONTH);
       int targetYear = Calendar.getInstance().get(Calendar.YEAR);
       if(targetMonth>5){//JULY - DECEMBER
           targetMonth = targetMonth - 5;
       }else{//JANUARY - JUNE
           targetMonth = targetMonth + 7;
           targetYear = targetYear - 1;
       }
       System.out.println("Month INT: "+Calendar.getInstance().get(Calendar.MONTH));
       for(int i = 0; i< tahuns.size(); i++){
           iuapFilters.add(new IUAP(profil.noInduk, new Level(null,null,null,tahuns.get(i)), entries));
           
        }
       Map<Long, IUAP> searchResultMap = Control.exactFilterSelectIurans(Iuran.Tipe.IUAP, iuapFilters);
        if(searchResultMap.size() > 0){
            for(Map.Entry<Long, IUAP> entry: searchResultMap.entrySet()){
                for(int j =0 ; j< entry.getValue().entries.size(); j++){
                    if((entry.getValue().entries.get(j).transactDetailIDs.isEmpty()) 
                            && ((entry.getValue().chargedLevel.tahun < targetYear)? true:(entry.getValue().entries.get(j).period <= targetMonth))){
                        retVal += entry.getValue().entries.get(j).amount;
                    }else if(entry.getValue().entries.get(j).transactDetailIDs.size() > 0){
                        Float temp = 0f;
                        for(Long l : entry.getValue().entries.get(j).transactDetailIDs){
                            temp += Control.selectTDetail(TransactionDetail.Tipe.IUAPTransaction, l).amount;
                        }
                        if(temp < entry.getValue().entries.get(j).amount){
                            retVal += entry.getValue().entries.get(j).amount-temp;
                        } 
                    }
                }
            }
        }
       unpaidIUAP = retVal;
       return retVal;
    }
    
    public ArrayList<TunggakanBean> calculateUnpaidIUAPs(ArrayList<Profil> profils, List<Integer> tahuns) throws SQLException, KasirException {
       Set<IUAP> iuapFilters = new HashSet<>();
       ArrayList<TunggakanBean> retVals = new ArrayList<>();
       float retVal = 0;
       ArrayList<Entry> entries = new ArrayList<>();
       iuapFilters.clear();
       int targetMonth = Calendar.getInstance().get(Calendar.MONTH);
       int targetYear = Calendar.getInstance().get(Calendar.YEAR);
       if(targetMonth>5){//JULY - DECEMBER
           targetMonth = targetMonth - 5;
       }else{//JANUARY - JUNE
           targetMonth = targetMonth + 7;
           targetYear = targetYear - 1;
       }
       System.out.println("Month INT: "+Calendar.getInstance().get(Calendar.MONTH));
       ArrayList<String> noInduks = new ArrayList<>();
       for(int i = 0; i< profils.size() ; i++){
           noInduks.add(profils.get(i).noInduk);
            for(int j = 0; j< tahuns.size(); j++){
                iuapFilters.add(new IUAP(profils.get(i).noInduk, new Level(null,null,null,tahuns.get(j)), entries));

            }
       }
       List<IUAP> test = Control.selectIurans(Iuran.Tipe.IUAP, IUAP.noIndukColName, false, noInduks.toArray(new String[0]));
       
       for(int i = 0 ; i< test.size(); i++){
           TunggakanBean tb = new TunggakanBean();
           for(int j = 0 ; j < test.get(i).entries.size(); j++){
               if(j==0) retVal=0;
               Float totalAmountIUAPTDetails = 0f;
               for(Long l : test.get(i).entries.get(j).transactDetailIDs){
                   totalAmountIUAPTDetails += Control.selectTDetail(TransactionDetail.Tipe.IUAPTransaction, l).amount;
               }
               if((totalAmountIUAPTDetails < test.get(i).entries.get(j).amount)
                   && ((test.get(i).chargedLevel.tahun < targetYear? true: (test.get(i).entries.get(j).period <= targetMonth)))){
                    
                            
                            retVal += test.get(i).entries.get(j).amount-totalAmountIUAPTDetails;
                            tunggakanIUAPString = tunggakanIUAPString.concat("IUAP Bulan ");
                            tunggakanIUAPString = tunggakanIUAPString.concat(getMonthName(test.get(i).entries.get(j).period));
                            tunggakanIUAPString = tunggakanIUAPString.concat(" "+String.valueOf(test.get(i).chargedLevel.tahun)+"/"+String.valueOf(1+test.get(i).chargedLevel.tahun));
                            tunggakanIUAPString = tunggakanIUAPString.concat("\r\n");
                            
                            tunggakanIUAPEachAmountString = tunggakanIUAPEachAmountString.concat("Rp. ");
                            tunggakanIUAPEachAmountString = tunggakanIUAPEachAmountString.concat(String.valueOf(Math.round(test.get(i).entries.get(j).amount-totalAmountIUAPTDetails)));
                            tunggakanIUAPEachAmountString = tunggakanIUAPEachAmountString.concat("\r\n");
               }
               
                
               
               
           }
           tb.setProfil(profils.get(i));
           tb.setTunggakanIUAP(retVal);
           retVals.add(tb);
           System.out.println(test.get(i).noInduk);
       }
       unpaidIUAP = retVal;
       return retVals;
    }
   
    private String getMonthName(int p){
        String ret;
        switch(p){
            case 1: ret = "JULI";
                break;
            case 2: ret = "AGUSTUS";
                break;
            case 3: ret = "SEPTEMBER";
                break;
            case 4: ret = "OKTOBER";
                break;
            case 5: ret = "NOPEMBER";
                break;
            case 6: ret = "DESEMBER";
                break;
            case 7: ret = "JANUARI";
                break;
            case 8: ret = "FEBRUARI";
                break;
            case 9: ret = "MARET";
                break;
            case 10: ret = "APRIL";
                break;
            case 11: ret = "MEI";
                break;
            case 12: ret = "JUNI";
                break;
            default: ret = "Invalid";
                break;
        }
        return ret;
        
    }

    public boolean isIUAPEnough(Set<Long> transactDetailIDs, float amountIUAPinTable) throws SQLException, KasirException {
        Float totalAmountTDetail = 0f;
        for(Long l : transactDetailIDs){
            totalAmountTDetail += Control.selectTDetail(TransactionDetail.Tipe.IUAPTransaction, l).amount;
        }
        if(totalAmountTDetail < amountIUAPinTable){
            return false;
        }else{
            return true;
        }
    }
    
    
    public float calculatePaidIUAP(Set<Long> transactDetailIDs) throws SQLException, KasirException{
        Float retVal = 0f;
        for(Long l: transactDetailIDs){
            retVal += Control.selectTDetail(TransactionDetail.Tipe.IUAPTransaction, l).amount;
        }
        return retVal;
    }
    
}
