/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import iuran.IUA;
import iuran.Iuran;
import java.sql.SQLException;
import java.text.ParseException;
import javax.swing.JOptionPane;
import kasir.Control;
import org.openide.util.Exceptions;
import pelajar.Profil;
import sak.KasirException;

/**
 *
 * @author Master
 */
public class InputTransactionIUA extends javax.swing.JFrame {
    private IUA iua;
    private float minIUA;
    private float maxIUA;
    private InputTransactionFrameSeparated itfs;
    private Profil profil;
    /**
     * Creates new form InputTransactionIUA
     */
    public InputTransactionIUA(Profil profil, InputTransactionFrameSeparated itfs) {
        try {
            this.iua = Control.selectIuran(Iuran.Tipe.IUA, IUA.noIndukColName, false, profil.noInduk);
            minIUA = 0F;
            maxIUA = this.iua.amount - this.iua.totalInstallment;
            this.itfs = itfs;
            this.profil = profil;
        } catch (SQLException ex) {
            Exceptions.printStackTrace(ex);
            JOptionPane.showMessageDialog(rootPane, "IUA Belum Di Setting!\r\n".concat(profil.biodata.nama+"\r\n").concat(ex.toString()));
            this.dispose();
        } catch (KasirException ex) {
            Exceptions.printStackTrace(ex);
            JOptionPane.showMessageDialog(rootPane, "IUA Belum Di Setting!\r\n".concat(profil.biodata.nama+"\r\n").concat(ex.toString()));
            this.dispose();
        }
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelIPSP = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldIUAAmount = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldIUANote = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextFieldIUAIuranAmount = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jTextFieldIUASisaAmount = new javax.swing.JTextField();
        jButtonIUAOK = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(480, 500));

        jPanelIPSP.setMinimumSize(new java.awt.Dimension(440, 480));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText(org.openide.util.NbBundle.getMessage(InputTransactionIUA.class, "InputTransactionIUA.jLabel1.text")); // NOI18N

        jLabel3.setText(org.openide.util.NbBundle.getMessage(InputTransactionIUA.class, "InputTransactionIUA.jLabel3.text")); // NOI18N

        jTextFieldIUAAmount.setText(org.openide.util.NbBundle.getMessage(InputTransactionIUA.class, "InputTransactionIUA.jTextFieldIUAAmount.text")); // NOI18N
        jTextFieldIUAAmount.setName(org.openide.util.NbBundle.getMessage(InputTransactionIUA.class, "InputTransactionIUA.jTextFieldIUAAmount.name")); // NOI18N
        jTextFieldIUAAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIUAAmountActionPerformed(evt);
            }
        });
        jTextFieldIUAAmount.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldIUAAmountFocusLost(evt);
            }
        });
        jTextFieldIUAAmount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldIUAAmountKeyTyped(evt);
            }
        });

        jLabel5.setText(org.openide.util.NbBundle.getMessage(InputTransactionIUA.class, "InputTransactionIUA.jLabel5.text")); // NOI18N

        jTextFieldIUANote.setText(org.openide.util.NbBundle.getMessage(InputTransactionIUA.class, "InputTransactionIUA.jTextFieldIUANote.text")); // NOI18N

        jLabel13.setText(org.openide.util.NbBundle.getMessage(InputTransactionIUA.class, "InputTransactionIUA.jLabel13.text")); // NOI18N

        jTextFieldIUAIuranAmount.setEditable(false);
        jTextFieldIUAIuranAmount.setText(String.valueOf(iua.amount));
        jTextFieldIUAIuranAmount.setFocusable(false);
        jTextFieldIUAIuranAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIUAIuranAmountActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel17.setText(org.openide.util.NbBundle.getMessage(InputTransactionIUA.class, "InputTransactionIUA.jLabel17.text")); // NOI18N

        jTextFieldIUASisaAmount.setEditable(false);
        jTextFieldIUASisaAmount.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jTextFieldIUASisaAmount.setText(String.valueOf(maxIUA));
        jTextFieldIUASisaAmount.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldIUASisaAmount.setFocusable(false);
        jTextFieldIUASisaAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIUASisaAmountActionPerformed(evt);
            }
        });

        jButtonIUAOK.setText(org.openide.util.NbBundle.getMessage(InputTransactionIUA.class, "InputTransactionIUA.jButtonIUAOK.text")); // NOI18N
        jButtonIUAOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIUAOKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelIPSPLayout = new javax.swing.GroupLayout(jPanelIPSP);
        jPanelIPSP.setLayout(jPanelIPSPLayout);
        jPanelIPSPLayout.setHorizontalGroup(
            jPanelIPSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelIPSPLayout.createSequentialGroup()
                .addGroup(jPanelIPSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanelIPSPLayout.createSequentialGroup()
                        .addGroup(jPanelIPSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel13))
                        .addGap(11, 11, 11)
                        .addGroup(jPanelIPSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldIUANote, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelIPSPLayout.createSequentialGroup()
                                .addGroup(jPanelIPSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jTextFieldIUAAmount, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldIUAIuranAmount, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel17)
                                .addGap(12, 12, 12)
                                .addComponent(jTextFieldIUASisaAmount, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE))))
                    .addGroup(jPanelIPSPLayout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(jButtonIUAOK)))
                .addContainerGap())
        );
        jPanelIPSPLayout.setVerticalGroup(
            jPanelIPSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelIPSPLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(4, 4, 4)
                .addGroup(jPanelIPSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jTextFieldIUAIuranAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(jTextFieldIUASisaAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelIPSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldIUAAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanelIPSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldIUANote, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonIUAOK)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 495, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanelIPSP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 313, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanelIPSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(72, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldIUAAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIUAAmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIUAAmountActionPerformed

    private void jTextFieldIUAAmountFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldIUAAmountFocusLost
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTextFieldIUAAmountFocusLost

    private void jTextFieldIUAAmountKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldIUAAmountKeyTyped
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTextFieldIUAAmountKeyTyped

    private void jTextFieldIUAIuranAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIUAIuranAmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIUAIuranAmountActionPerformed

    private void jTextFieldIUASisaAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIUASisaAmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIUASisaAmountActionPerformed

    private void jButtonIUAOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIUAOKActionPerformed
        // TODO add your handling code here:
        itfs.jTextFieldIUAAmountSimple.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0"))));

        try {
            itfs.jTextFieldIUAAmountSimple.setValue(Float.valueOf(jTextFieldIUAAmount.getText()));
            itfs.jTextFieldIUAAmountSimple.commitEdit();
        } catch (ParseException ex) {
            Exceptions.printStackTrace(ex);
        }
//        try {
//            iua = Control.selectIuran(Iuran.Tipe.IUA, IUA.noIndukColName, false, profil.noInduk);
//            itfs.iua = iua;
//        } catch (SQLException ex) {
//            //idd = null;
//        } catch (KasirException ex) {
//            //idd = null;
//        }
        this.setVisible(false);
    }//GEN-LAST:event_jButtonIUAOKActionPerformed

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonIUAOK;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanelIPSP;
    public javax.swing.JTextField jTextFieldIUAAmount;
    private javax.swing.JTextField jTextFieldIUAIuranAmount;
    public javax.swing.JTextField jTextFieldIUANote;
    private javax.swing.JTextField jTextFieldIUASisaAmount;
    // End of variables declaration//GEN-END:variables
}
