/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import iuran.*;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.*;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import kasir.Control;
import org.openide.util.Exceptions;
import pelajar.Level;
import pelajar.Profil;
import printout.TunggakanBean;
import sak.KasirException;

/**
 *
 * @author Master
 */
public class InputTransactionOSIS extends javax.swing.JFrame {
    Profil profil;
    private TableModel tableModelOSIS;
    private OSIS osisFromDB;
    public List<Integer> tahunOSIS;
    public ArrayList<Float> iDDAmounts;
    public ArrayList<Float> beasiswaAmounts;
    public ArrayList<Float> beasiswaCostAmounts;
    public ArrayList<Float> oSISAmounts;
    private OSIS osisCurrent;
    private OSIS osisStoreToDB;
    private IDD idd;
    private InputTransactionFrameSeparated itfs;
    private final String[] namaBulan = {"OSIS"};
    private float unpaidOSIS;
    private ComboBoxModel tahunComboBoxModel;
    private String tunggakanOSISString = new String("");
    private String tunggakanOSISEachAmountString = new String("");
    private float osisDebt;
    /**
     * Creates new form InputTransactionOSIS
     */
    
    public InputTransactionOSIS(Profil profil, InputTransactionFrameSeparated itfs) {
        this.profil = profil;
        this.itfs = itfs;
        try {
            tableModelOSIS = buildOSISTableModel(profil, profil.currentLevel.tahun);
        } catch (SQLException ex) {
            Exceptions.printStackTrace(ex);
        } catch (KasirException ex) {
            Exceptions.printStackTrace(ex);
        }
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelIPP = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabelTahun = new javax.swing.JLabel();
        jComboBoxTahun = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jUnpaidOSIS = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTableOSIS = new javax.swing.JTable();
        jButtonBayarIUS = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jFormattedTextFieldIDDSaldo = new javax.swing.JFormattedTextField();
        jTextFieldOsisDebt = new javax.swing.JFormattedTextField();

        setTitle(org.openide.util.NbBundle.getMessage(InputTransactionOSIS.class, "InputTransactionOSIS.title_1")); // NOI18N

        jPanelIPP.setMinimumSize(new java.awt.Dimension(570, 380));
        jPanelIPP.setPreferredSize(new java.awt.Dimension(680, 450));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText(org.openide.util.NbBundle.getMessage(InputTransactionOSIS.class, "InputTransactionOSIS.jLabel1.text_1")); // NOI18N

        jLabelTahun.setText(org.openide.util.NbBundle.getMessage(InputTransactionOSIS.class, "InputTransactionOSIS.jLabelTahun.text_1")); // NOI18N

        try{
            tahunComboBoxModel = buildOSIStahunComboBoxModel(profil);
        }catch(SQLException ex){
            ex.printStackTrace();
        }catch(KasirException ex){
            ex.printStackTrace();
        }
        jComboBoxTahun.setModel(tahunComboBoxModel);
        jComboBoxTahun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTahunActionPerformed(evt);
            }
        });
        jComboBoxTahun.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jComboBoxTahunPropertyChange(evt);
            }
        });

        jLabel2.setText(org.openide.util.NbBundle.getMessage(InputTransactionOSIS.class, "InputTransactionOSIS.jLabel2.text_1")); // NOI18N

        jUnpaidOSIS.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jUnpaidOSIS.setText(String.valueOf(unpaidOSIS));
        jUnpaidOSIS.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jUnpaidOSIS.setEnabled(false);

        jTableOSIS.setModel(tableModelOSIS);
        jTableOSIS.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jTableOSIS.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTableOSISFocusLost(evt);
            }
        });
        jTableOSIS.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jTableOSISPropertyChange(evt);
            }
        });
        jScrollPane5.setViewportView(jTableOSIS);

        jButtonBayarIUS.setText(org.openide.util.NbBundle.getMessage(InputTransactionOSIS.class, "InputTransactionOSIS.jButtonBayarIUS.text")); // NOI18N
        jButtonBayarIUS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBayarIUSActionPerformed(evt);
            }
        });

        jLabel3.setText(org.openide.util.NbBundle.getMessage(InputTransactionOSIS.class, "InputTransactionOSIS.jLabel3.text_1")); // NOI18N

        jFormattedTextFieldIDDSaldo.setText(org.openide.util.NbBundle.getMessage(InputTransactionOSIS.class, "InputTransactionOSIS.jFormattedTextFieldIDDSaldo.text_1")); // NOI18N
        jFormattedTextFieldIDDSaldo.setEnabled(false);

        jTextFieldOsisDebt.setEditable(false);
        jTextFieldOsisDebt.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0"))));

        javax.swing.GroupLayout jPanelIPPLayout = new javax.swing.GroupLayout(jPanelIPP);
        jPanelIPP.setLayout(jPanelIPPLayout);
        jPanelIPPLayout.setHorizontalGroup(
            jPanelIPPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelIPPLayout.createSequentialGroup()
                .addGroup(jPanelIPPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelIPPLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE))
                    .addGroup(jPanelIPPLayout.createSequentialGroup()
                        .addGroup(jPanelIPPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelIPPLayout.createSequentialGroup()
                                .addGap(248, 248, 248)
                                .addComponent(jButtonBayarIUS))
                            .addGroup(jPanelIPPLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1)
                                .addGap(29, 29, 29)
                                .addComponent(jLabelTahun)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanelIPPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jComboBoxTahun, 0, 101, Short.MAX_VALUE)
                                    .addComponent(jTextFieldOsisDebt))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanelIPPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanelIPPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jUnpaidOSIS, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jFormattedTextFieldIDDSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 61, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelIPPLayout.setVerticalGroup(
            jPanelIPPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelIPPLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanelIPPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxTahun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTahun)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jUnpaidOSIS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelIPPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jFormattedTextFieldIDDSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldOsisDebt))
                .addGap(19, 19, 19)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonBayarIUS)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelIPP, javax.swing.GroupLayout.DEFAULT_SIZE, 570, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelIPP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxTahunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTahunActionPerformed
        // TODO add your handling code here:
        try {
            this.tableModelOSIS = (DefaultTableModel) buildOSISTableModel(this.profil, this.tahunOSIS.get(jComboBoxTahun.getSelectedIndex()));
            jTableOSIS.setModel(this.tableModelOSIS);
            jTextFieldOsisDebt.setValue(osisDebt);
        } catch (SQLException ex) {
            ex.printStackTrace();
        } catch (KasirException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jComboBoxTahunActionPerformed

    private void jComboBoxTahunPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jComboBoxTahunPropertyChange
        // TODO add your handling code here:
        try {
            if (this.jComboBoxTahun.getSelectedItem() != null) {
                this.tableModelOSIS = (DefaultTableModel) buildOSISTableModel(this.profil, this.tahunOSIS.get(jComboBoxTahun.getSelectedIndex()));
                jTableOSIS.setModel(this.tableModelOSIS);
                jTextFieldOsisDebt.setValue(osisDebt);
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(rootPane, "Koneksi Error!\r\n".concat(ex.toString()));
        } catch (KasirException ex) {
            JOptionPane.showMessageDialog(rootPane, "OSIS Belum Di Setting!\r\n".concat(ex.toString()));
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jComboBoxTahunPropertyChange

    private void jTableOSISFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTableOSISFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTableOSISFocusLost

    private void jTableOSISPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jTableOSISPropertyChange
        // TODO add your handling code here:
        //IDD, Beasiswa, Beasiswa Cost
        oSISAmounts = new ArrayList();
        iDDAmounts = new ArrayList();
        beasiswaAmounts = new ArrayList();
        beasiswaCostAmounts = new ArrayList();
        /////BLOOOOOOOOOOM SELESAIIIIIIIIIIIIIIIIIIII
        int i = 0;
        osisCurrent = new OSIS();
        osisStoreToDB = new OSIS();
        ArrayList<Entry> entry = new ArrayList<>();
        if (osisFromDB.entries.size() != 0) {
            for (i = 0; i < jTableOSIS.getRowCount(); i++) {
                osisCurrent.entries.add((Boolean) jTableOSIS.getValueAt(i, 2) ? ((osisFromDB.entries.get(i).transactDetailIDs.size() > 0) ? new Entry(i, osisFromDB.entries.get(i).amount, osisFromDB.entries.get(i).debt, osisFromDB.entries.get(i).transactDetailIDs) : new Entry(i, osisFromDB.entries.get(i).amount)) : null);
                //below condition is when jTableOSIS checkBox is UNCHECK ????
                if (osisCurrent.entries.get(i) == null) {
                    osisStoreToDB.entries.add(null);
                    jTableOSIS.setValueAt(0f, i, 3);
                    jTableOSIS.setValueAt(0f, i, 4);
                    jTableOSIS.setValueAt(0f, i, 5);
                    jTableOSIS.setValueAt(0f, i, 6);
                    oSISAmounts.add(0f);
                    iDDAmounts.add(0f);
                    beasiswaAmounts.add(0f);
                    beasiswaCostAmounts.add(0f);
                    //below is when jTableOSIS property changed, especially check box is Changed or Editing IDD, Beasiswa, Beasiswa Cost 
                } else if ((osisCurrent.entries.get(i) != null) ^ (osisFromDB.entries.get(i).transactDetailIDs.size() > 0)) {
                    System.out.println("IDD dari db ");
                    if (idd != null) {
                        System.out.println(idd.amount);
                    }
                    oSISAmounts.add((Float) jTableOSIS.getModel().getValueAt(i,3));
                    iDDAmounts.add((Float) jTableOSIS.getValueAt(i, 4));
                    beasiswaAmounts.add((Float) jTableOSIS.getValueAt(i, 5));
                    beasiswaCostAmounts.add((Float) jTableOSIS.getValueAt(i, 6));
                    //jTableOSIS.setValueAt(osisFromDB.entries.get(i).amount - (iDDAmounts.get(i) + beasiswaAmounts.get(i) + beasiswaCostAmounts.get(i)), i, 3);
                    //osisStoreToDB.entries.add(new Entry(i, osisFromDB.entries.get(i).amount));
                    osisStoreToDB.entries.add(new Entry(i, oSISAmounts.get(i)+iDDAmounts.get(i)+beasiswaAmounts.get(i)+beasiswaCostAmounts.get(i)));
                } else {
                    try {
                        if(isOSISEnough(osisFromDB.entries.get(i).transactDetailIDs, osisFromDB.entries.get(i).amount)){
                            oSISAmounts.add(0f);
                            iDDAmounts.add(0f);
                            beasiswaAmounts.add(0f);
                            beasiswaCostAmounts.add(0f);
                            osisStoreToDB.entries.add(null);
                        }else{
                            oSISAmounts.add((Float) jTableOSIS.getModel().getValueAt(i,3));
                            iDDAmounts.add((Float) jTableOSIS.getValueAt(i, 4));
                            beasiswaAmounts.add((Float) jTableOSIS.getValueAt(i, 5));
                            beasiswaCostAmounts.add((Float) jTableOSIS.getValueAt(i, 6));
                            osisStoreToDB.entries.add(new Entry(i, oSISAmounts.get(i)+iDDAmounts.get(i)+beasiswaAmounts.get(i)+beasiswaCostAmounts.get(i)));
                        }
                    } catch (SQLException ex) {
                        Exceptions.printStackTrace(ex);
                    } catch (KasirException ex) {
                        Exceptions.printStackTrace(ex);
                    }
                    

                }
                //osisCurrent.entries.add((Boolean)jTableOSIS.getValueAt(i,2)? new OSIS(profil.noInduk, new Level(null,null,null,(Integer)jComboBoxTahun.getSelectedItem()),entry).entries.get(i): null);
                //osisStoreToDB.entries.add(osisCurrent.entries.get(i)==null?null:(((osisCurrent.entries.get(i)!=null)^(osisFromDB.entries.get(i)!=null))? new OSIS(profil.noInduk, new Level(null,null,null,(int)jComboBoxTahun.getSelectedItem()),entry).entries.get(i):osisCurrent.entries.get(i)));
                //System.out.println("OSIS Period: "+osisCurrent.entries.get(i).period);
            }
        }
    }//GEN-LAST:event_jTableOSISPropertyChange

    private void jButtonBayarIUSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBayarIUSActionPerformed
        // TODO add your handling code here:
        float osisAmountTemp = 0f;
        for (int i = 0; i < 1; i++) {
            if (osisStoreToDB.entries.get(i) != null) {
                //osisAmountTemp = osisAmountTemp + osisFromDB.entries.get(i).amount;
                osisAmountTemp = osisAmountTemp + (Float)jTableOSIS.getModel().getValueAt(i,3)
                                +(Float)jTableOSIS.getModel().getValueAt(i,4)
                                +(Float)jTableOSIS.getModel().getValueAt(i,5)
                                +(Float)jTableOSIS.getModel().getValueAt(i,6);
            }
        }
        itfs.jTextFieldOSISAmountSimple.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0"))));
        itfs.jTextFieldOSISAmountSimple.setValue(osisAmountTemp);
        try {
            itfs.jTextFieldOSISAmountSimple.commitEdit();
        } catch (ParseException ex) {
            Exceptions.printStackTrace(ex);
        }
        itfs.osisCurrent = osisCurrent;
        itfs.osisFromDB = osisFromDB;
        itfs.osisStoreToDB = osisStoreToDB;
        this.setVisible(false);

    }//GEN-LAST:event_jButtonBayarIUSActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InputTransactionFrameSeparated.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InputTransactionFrameSeparated.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InputTransactionFrameSeparated.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InputTransactionFrameSeparated.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                //new InputTransactionOSIS().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBayarIUS;
    public javax.swing.JComboBox jComboBoxTahun;
    private javax.swing.JFormattedTextField jFormattedTextFieldIDDSaldo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelTahun;
    private javax.swing.JPanel jPanelIPP;
    private javax.swing.JScrollPane jScrollPane5;
    public javax.swing.JTable jTableOSIS;
    private javax.swing.JFormattedTextField jTextFieldOsisDebt;
    private javax.swing.JTextField jUnpaidOSIS;
    // End of variables declaration//GEN-END:variables

    public TableModel buildOSISTableModel(Profil profil, int tahun) throws SQLException, KasirException {
       String columnNames[] = {"Semester", "Biaya OSIS", "Check Box", "Tunai", "Iuran Dibayar Dimuka", "Beasiswa", "Beasiswa Yayasan"};
       Set<OSIS> osisFilters = new HashSet<>();
       ArrayList<Entry> entries = new ArrayList<>();
       osisFilters.clear();
       osisFilters.add(new OSIS(profil.noInduk, new Level(null,null,null,tahun), entries));
       Map<Long, OSIS> searchResultMap = Control.exactFilterSelectIurans(Iuran.Tipe.OSIS, osisFilters);
       Object[][] data = new Object[1][7];
       int i = 0;
       final boolean[] canEdit = new boolean [1];
       osisFromDB = new OSIS();
       float amountOSISinTable;
       float amountOSISinTDetail;
       osisDebt = 0f;
       if(searchResultMap.size() > 0){
        for(Map.Entry<Long, OSIS> entry: searchResultMap.entrySet()){
            for(int j =0 ; j< entry.getValue().entries.size(); j++){
                data[j][0]= namaBulan[j];//entry.getValue().entries.get(j).period;
                data[j][1]= entry.getValue().entries.get(j).amount - calculatePaidOSIS(entry.getValue().entries.get(j).transactDetailIDs); // ANEH NIH MASA BEGINI, DI KALI DUA SIH?
                amountOSISinTable = entry.getValue().entries.get(j).amount;
                osisDebt += entry.getValue().entries.get(j).debt;
                //if(jTable2 != null){data[j][2]= jTable2.getModel().getValueAt(j,2);}else{data[j][2]= new Boolean(false);}
                //if(entry.getValue().entries.get(j).transactDetailIDs.size() > 0){
                if(isOSISEnough(entry.getValue().entries.get(j).transactDetailIDs, amountOSISinTable)){        
//                    
                    data[j][2] = new Boolean(true);
                    Float data3 = 0f;
                    Float data4 = 0f;
                    Float data5 = 0f;
                    Float data6 = 0f;
                    
                    for(Long setTDetailIds:entry.getValue().entries.get(j).transactDetailIDs){
                        System.out.println(setTDetailIds + " Set TDetailsID");
                        if(Control.selectTDetail(TransactionDetail.Tipe.OSISTransaction, setTDetailIds).paymentMethod == TransactionDetail.PaymentMethod.CASH){
                            data3 += Control.selectTDetail(TransactionDetail.Tipe.OSISTransaction, setTDetailIds).amount;
                            data[j][3] = data3;
                        }
                        if(Control.selectTDetail(TransactionDetail.Tipe.OSISTransaction, setTDetailIds).paymentMethod == TransactionDetail.PaymentMethod.IDD){
                            data4 += Control.selectTDetail(TransactionDetail.Tipe.OSISTransaction, setTDetailIds).amount;
                            data[j][4] = data4;
                        }
                        if(Control.selectTDetail(TransactionDetail.Tipe.OSISTransaction, setTDetailIds).paymentMethod == TransactionDetail.PaymentMethod.BEASISWA){
                            data5 += Control.selectTDetail(TransactionDetail.Tipe.OSISTransaction, setTDetailIds).amount;
                            data[j][5] = data5;
                        }
                        if(Control.selectTDetail(TransactionDetail.Tipe.OSISTransaction, setTDetailIds).paymentMethod == TransactionDetail.PaymentMethod.BEASISWA_COST){
                            data6 += Control.selectTDetail(TransactionDetail.Tipe.OSISTransaction, setTDetailIds).amount;
                            data[j][6] = data6;
                        }
                    }
                    if(data[j][3] == null){
                        data[j][3] = 0f;
                    }
                    if(data[j][4] == null){
                        data[j][4] = 0f;
                    }
                    if(data[j][5] == null){
                        data[j][5] = 0f;
                    }
                    if(data[j][6] == null){
                        data[j][6] = 0f;
                    }
                            
                }else{
                    data[j][2] = new Boolean(false);
                    if(entry.getValue().entries.get(j).transactDetailIDs.size() > 0){
                        for(Long setTDetailIds:entry.getValue().entries.get(j).transactDetailIDs){
                            System.out.println(setTDetailIds + " Set TDetailsID");
                            if(Control.selectTDetail(TransactionDetail.Tipe.OSISTransaction, setTDetailIds).paymentMethod == TransactionDetail.PaymentMethod.CASH){
                                data[j][3] = Control.selectTDetail(TransactionDetail.Tipe.OSISTransaction, setTDetailIds).amount;
                            }
                            if(Control.selectTDetail(TransactionDetail.Tipe.OSISTransaction, setTDetailIds).paymentMethod == TransactionDetail.PaymentMethod.IDD){
                                data[j][4] = Control.selectTDetail(TransactionDetail.Tipe.OSISTransaction, setTDetailIds).amount;
                            }
                            if(Control.selectTDetail(TransactionDetail.Tipe.OSISTransaction, setTDetailIds).paymentMethod == TransactionDetail.PaymentMethod.BEASISWA){
                                data[j][5] = Control.selectTDetail(TransactionDetail.Tipe.OSISTransaction, setTDetailIds).amount;
                            }
                            if(Control.selectTDetail(TransactionDetail.Tipe.OSISTransaction, setTDetailIds).paymentMethod == TransactionDetail.PaymentMethod.BEASISWA_COST){
                                data[j][6] = Control.selectTDetail(TransactionDetail.Tipe.OSISTransaction, setTDetailIds).amount;
                            }
                        }
                        if(data[j][3] == null){
                        data[j][3] = 0f;
                        }
                        if(data[j][4] == null){
                            data[j][4] = 0f;
                        }
                        if(data[j][5] == null){
                            data[j][5] = 0f;
                        }
                        if(data[j][6] == null){
                            data[j][6] = 0f;
                        }
                    }else{
                        data[j][3]=0f;
                        data[j][4]=0f;
                        data[j][5]=0f;
                        data[j][6]=0f;
                    }
                }
                
                osisFromDB.entries.add(entry.getValue().entries.get(j));
                //canEdit[j] = (entry.getValue().entries.get(j).transactDetailIDs.size() > 0);
                
                for(Long id : entry.getValue().entries.get(j).transactDetailIDs){
                    canEdit[j] = Control.selectTDetail(TransactionDetail.Tipe.OSISTransaction, id).settled;
                }
                
                
            }
            osisFromDB.id = entry.getValue().id;
            osisFromDB.noInduk = entry.getValue().noInduk;
            osisFromDB.chargedLevel = entry.getValue().chargedLevel;
            i++;
        }
        TableModel tm = new DefaultTableModel(data, columnNames){
            boolean[] chooseEdit = new boolean[]{false,false,true,true,true,true,true};
            
           @Override
            public boolean isCellEditable(int row, int column) {
                //all cells false for editable
                if(!itfs.jDialogTransactionSummary.isVisible()){
                    if((Boolean)getValueAt(row, 2)){
                    //if((Float)getValueAt(row,1) == 0f){
                        if((column == 0 || column ==1)){
                            return column == 2;
                        //return false;
                        }
                        return !canEdit[row];
                    }
                    if((column == 0 && column ==1)|| column == 2){
                            //return column == 2;
                        return chooseEdit[column];
                    }

                    return false;
               }else{
                    return false;
                }
            }
            public Class getColumnClass(int c) {
                return getValueAt(0, c).getClass();
            }
       };
       
       return tm;
       }else{
           TableModel tm = new DefaultTableModel(data, columnNames);
           JOptionPane.showMessageDialog(rootPane, "OSIS Belum Di Setting!\r\n");
           this.dispose();
           return null;
       }
       
       
    }
    public TableModel buildOSISSubmitTableModel(Profil profil, int tahun) throws SQLException, KasirException {
       String columnNames[] = {"OSIS", "Biaya OSIS", "Check Box", "Tunai", "Iuran Dibayar Dimuka", "Beasiswa", "Beasiswa Yayasan"};
       Object[][] data = new Object[1][7];
       
       final boolean[] canEdit = new boolean [1];
         
        for(int i = 0 ; i < osisCurrent.entries.size(); i++){
                data[i][0]= namaBulan[i];//entry.getValue().entries.get(j).period;
                data[i][1]= osisFromDB.entries.get(i).amount; // ANEH NIH MASA BEGINI, DI KALI DUA SIH?
                if(osisCurrent.entries.get(i) != null){
//                    if(jTableOSIS != null){
//                        data[j][2]=jTableOSIS.getValueAt(j,2);
//                    }else{
                        data[i][2] = new Boolean(true);
//                        data[i][3] = osisFromDB.entries.get(i).amount-(iDDAmounts.get(i)+beasiswaAmounts.get(i)+beasiswaCostAmounts.get(i));
                        data[i][3] = oSISAmounts.get(i);
                        data[i][4] = iDDAmounts.get(i);
                        data[i][5] = beasiswaAmounts.get(i);
                        data[i][6] = beasiswaCostAmounts.get(i);
//                    }
                }else{
//                    if(jTableOSIS !=null){
//                        data[j][2]=jTableOSIS.getValueAt(j,2);
//                    }else{
                        data[i][2] = new Boolean(false);
//                        data[i][3] = osisFromDB.entries.get(i).amount-(iDDAmounts.get(i)+beasiswaAmounts.get(i)+beasiswaCostAmounts.get(i));
                        data[i][3] = oSISAmounts.get(i);
                        data[i][4] = iDDAmounts.get(i);
                        data[i][5] = beasiswaAmounts.get(i);
                        data[i][6] = beasiswaCostAmounts.get(i);
//                    }
                }
       }
       
       TableModel tm = new DefaultTableModel(data, columnNames){
            boolean[] chooseEdit = new boolean[]{false,false,true};
            
           @Override
            public boolean isCellEditable(int row, int column) {
                //all cells false for editable
                if(!itfs.jDialogTransactionSummary.isVisible()){
                    if((Boolean)getValueAt(row, 2)){
                        if((column == 0 || column ==1)){
                            return column == 2;
                        //return false;
                        }
                        return !canEdit[row];
                    }
                    if((column == 0 && column ==1)|| column == 2){
                            //return column == 2;
                        return chooseEdit[column];
                    }

                    return false;
               }else{
                    return false;
                }
            }
            public Class getColumnClass(int c) {
                return getValueAt(0, c).getClass();
            }
       };
       
       return tm;
    }
    
private ComboBoxModel buildOSIStahunComboBoxModel(Profil profil) throws SQLException, KasirException {
       Set<OSIS> osisFilters = new HashSet<>();
       ArrayList<Entry> entries = new ArrayList();
       osisFilters.add(new OSIS(profil.noInduk, null, entries));
       Map<Long, OSIS> searchResultMap = Control.exactFilterSelectIurans(Iuran.Tipe.OSIS, osisFilters);
       this.tahunOSIS = new ArrayList<>();
       List<String> tahunAjaran = new ArrayList<>();
       Object[][] data = new Object[searchResultMap.size()][2];
       int i = 0;
       if(searchResultMap.size() > 0){
        for(Map.Entry<Long, OSIS> entry: searchResultMap.entrySet()){
            data[i][0]= entry.getValue().entries.get(0);
            data[i][1]= entry.getValue().entries.get(0).amount;
            this.tahunOSIS.add(entry.getValue().chargedLevel.tahun);
            tahunAjaran.add(String.valueOf(entry.getValue().chargedLevel.tahun).concat(" - ").concat(String.valueOf(entry.getValue().chargedLevel.tahun+1)));
            i++;
        }
       }
       calculateUnpaidOSIS(profil, tahunOSIS);
       //== bikin tunggakan beans ===
       
       
       //== end bikin tunggakan beans ===
       
       tahunComboBoxModel = new DefaultComboBoxModel(tahunAjaran.toArray());
       return tahunComboBoxModel;
    }

private float calculateUnpaidOSIS(Profil profil, List<Integer> tahuns) throws SQLException, KasirException {
       Set<OSIS> osisFilters = new HashSet<>();
       float retVal = 0;
       ArrayList<Entry> entries = new ArrayList<>();
       osisFilters.clear();
       int targetMonth = Calendar.getInstance().get(Calendar.MONTH);
       int targetYear = Calendar.getInstance().get(Calendar.YEAR);
       if(targetMonth>5){//JULY - DECEMBER
           targetMonth = targetMonth - 5;
       }else{//JANUARY - JUNE
           targetMonth = targetMonth + 7;
           targetYear = targetYear - 1;
       }
       System.out.println("Month INT: "+Calendar.getInstance().get(Calendar.MONTH));
       for(int i = 0; i< tahuns.size(); i++){
           osisFilters.add(new OSIS(profil.noInduk, new Level(null,null,null,tahuns.get(i)), entries));
           
        }
       Map<Long, OSIS> searchResultMap = Control.exactFilterSelectIurans(Iuran.Tipe.OSIS, osisFilters);
        if(searchResultMap.size() > 0){
            for(Map.Entry<Long, OSIS> entry: searchResultMap.entrySet()){
                for(int j =0 ; j< entry.getValue().entries.size(); j++){
                    if((entry.getValue().entries.get(0).transactDetailIDs.isEmpty()) 
                            && ((entry.getValue().chargedLevel.tahun < targetYear)? true:(entry.getValue().entries.get(0).period <= targetMonth))){
                        retVal += entry.getValue().entries.get(0).amount;
                    }else if(entry.getValue().entries.get(0).transactDetailIDs.size() > 0){
                        Float temp = 0f;
                        for(Long l : entry.getValue().entries.get(0).transactDetailIDs){
                            temp += Control.selectTDetail(TransactionDetail.Tipe.OSISTransaction, l).amount;
                        }
                        if(temp < entry.getValue().entries.get(0).amount){
                            retVal += entry.getValue().entries.get(0).amount-temp;
                        } 
                    }
                }
            }
        }
       unpaidOSIS = retVal;
       return retVal;
    }
    
    public ArrayList<TunggakanBean> calculateUnpaidOSISs(ArrayList<Profil> profils, List<Integer> tahuns) throws SQLException, KasirException {
       Set<OSIS> osisFilters = new HashSet<>();
       ArrayList<TunggakanBean> retVals = new ArrayList<>();
       float retVal = 0;
       ArrayList<Entry> entries = new ArrayList<>();
       osisFilters.clear();
       int targetMonth = Calendar.getInstance().get(Calendar.MONTH);
       int targetYear = Calendar.getInstance().get(Calendar.YEAR);
       if(targetMonth>5){//JULY - DECEMBER
           targetMonth = targetMonth - 5;
       }else{//JANUARY - JUNE
           targetMonth = targetMonth + 7;
           targetYear = targetYear - 1;
       }
       System.out.println("Month INT: "+Calendar.getInstance().get(Calendar.MONTH));
       ArrayList<String> noInduks = new ArrayList<>();
       for(int i = 0; i< profils.size() ; i++){
           noInduks.add(profils.get(i).noInduk);
            for(int j = 0; j< tahuns.size(); j++){
                osisFilters.add(new OSIS(profils.get(i).noInduk, new Level(null,null,null,tahuns.get(j)), entries));

            }
       }
       List<OSIS> test = Control.selectIurans(Iuran.Tipe.OSIS, OSIS.noIndukColName, false, noInduks.toArray(new String[0]));
       
       for(int i = 0 ; i< test.size(); i++){
           TunggakanBean tb = new TunggakanBean();
           for(int j = 0 ; j < test.get(i).entries.size(); j++){
               if(j==0) retVal=0;
               Float totalAmountOSISTDetails = 0f;
               for(Long l : test.get(i).entries.get(0).transactDetailIDs){
                   totalAmountOSISTDetails += Control.selectTDetail(TransactionDetail.Tipe.OSISTransaction, l).amount;
               }
               if((totalAmountOSISTDetails < test.get(i).entries.get(0).amount)
                   && ((test.get(i).chargedLevel.tahun < targetYear? true: (test.get(i).entries.get(0).period <= targetMonth)))){
                    
                            
                            retVal += test.get(i).entries.get(0).amount-totalAmountOSISTDetails;
                            tunggakanOSISString = tunggakanOSISString.concat("OSIS Semester ");
                            tunggakanOSISString = tunggakanOSISString.concat(getMonthName(test.get(i).entries.get(0).period));
                            tunggakanOSISString = tunggakanOSISString.concat(" "+String.valueOf(test.get(i).chargedLevel.tahun)+"/"+String.valueOf(1+test.get(i).chargedLevel.tahun));
                            tunggakanOSISString = tunggakanOSISString.concat("\r\n");
                            
                            tunggakanOSISEachAmountString = tunggakanOSISEachAmountString.concat("Rp. ");
                            tunggakanOSISEachAmountString = tunggakanOSISEachAmountString.concat(String.valueOf(Math.round(test.get(i).entries.get(0).amount-totalAmountOSISTDetails)));
                            tunggakanOSISEachAmountString = tunggakanOSISEachAmountString.concat("\r\n");
               }
               
                
               
               
           }
           tb.setProfil(profils.get(i));
           tb.setTunggakanOSIS(retVal);
           retVals.add(tb);
           System.out.println(test.get(i).noInduk);
       }
       unpaidOSIS = retVal;
       return retVals;
    }
   
    private String getMonthName(int p){
        String ret;
        switch(p){
            case 1: ret = "OSIS";
                break;
            default: ret = "Invalid";
                break;
        }
        return ret;
        
    }

    public boolean isOSISEnough(Set<Long> transactDetailIDs, float amountOSISinTable) throws SQLException, KasirException {
        Float totalAmountTDetail = 0f;
        for(Long l : transactDetailIDs){
            totalAmountTDetail += Control.selectTDetail(TransactionDetail.Tipe.OSISTransaction, l).amount;
        }
        if(totalAmountTDetail < amountOSISinTable){
            return false;
        }else{
            return true;
        }
    }
    
    
    public float calculatePaidOSIS(Set<Long> transactDetailIDs) throws SQLException, KasirException{
        Float retVal = 0f;
        for(Long l: transactDetailIDs){
            retVal += Control.selectTDetail(TransactionDetail.Tipe.OSISTransaction, l).amount;
        }
        return retVal;
    }
    
}
