/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import iuran.Iuran;
import iuran.Sumbangan;
import iuran.SumbanganTransactionDetail;
import iuran.TransactionDetail;
import java.awt.Component;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumnModel;
import javax.swing.table.TableModel;
import kasir.Control;
import org.openide.util.Exceptions;
import pelajar.Profil;
import sak.Kalender;
import sak.KasirException;




/**
 *
 * @author Master
 */
public class InputTransactionSumbangan extends javax.swing.JFrame {
    Profil profil;
    private Sumbangan sumbangan;
    private List<Sumbangan> sumbanganS;
    private List<Sumbangan> sumbanganSToDB;
    private float unpaidSumbangan = 0f;
    private InputTransactionFrameSeparated itfs;
    private TableModel tableModelSumbangan;
    /**
     * Creates new form InputTransactionSumbangan
     */
    public InputTransactionSumbangan(Profil profil, InputTransactionFrameSeparated itfs) {
        this.profil = profil;
        this.itfs = itfs;
        try{
            tableModelSumbangan = buildSumbanganTableModel(profil);
        }catch(SQLException ex){
            ex.printStackTrace();
        }catch(KasirException ex){
            ex.printStackTrace();
        }
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelSeragam = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableSumbangan = new javax.swing.JTable();
        jLabel19 = new javax.swing.JLabel();
        jUnpaidSumbangan = new javax.swing.JTextField();
        jButtonBayarIll = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jPanelSeragam.setMinimumSize(new java.awt.Dimension(440, 550));
        jPanelSeragam.setPreferredSize(new java.awt.Dimension(480, 302));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel10.setText(org.openide.util.NbBundle.getMessage(InputTransactionSumbangan.class, "InputTransactionSumbangan.jLabel10.text")); // NOI18N

        try{
            tableModelSumbangan = buildSumbanganTableModel(profil);
        }catch(Exception e){
            e.printStackTrace();
        }
        jTableSumbangan.setModel(tableModelSumbangan);
        jTableSumbangan.getColumn("Detail / History").setCellRenderer(new SumbanganButtonRenderer());
        jTableSumbangan.getColumn("Detail / History").setCellEditor(
            new SumbanganButtonEditor(new JCheckBox()));
        jTableSumbangan.removeColumn(jTableSumbangan.getColumn("IuranID"));
        jTableSumbangan.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jTableSumbanganPropertyChange(evt);
            }
        });
        jScrollPane2.setViewportView(jTableSumbangan);

        jLabel19.setText(org.openide.util.NbBundle.getMessage(InputTransactionSumbangan.class, "InputTransactionSumbangan.jLabel19.text")); // NOI18N

        jUnpaidSumbangan.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jUnpaidSumbangan.setText(String.valueOf(unpaidSumbangan));
        jUnpaidSumbangan.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jUnpaidSumbangan.setEnabled(false);

        jButtonBayarIll.setText(org.openide.util.NbBundle.getMessage(InputTransactionSumbangan.class, "InputTransactionSumbangan.jButtonBayarIll.text")); // NOI18N
        jButtonBayarIll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBayarIllActionPerformed(evt);
            }
        });

        jLabel1.setText(profil.biodata.nama);

        javax.swing.GroupLayout jPanelSeragamLayout = new javax.swing.GroupLayout(jPanelSeragam);
        jPanelSeragam.setLayout(jPanelSeragamLayout);
        jPanelSeragamLayout.setHorizontalGroup(
            jPanelSeragamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSeragamLayout.createSequentialGroup()
                .addGroup(jPanelSeragamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 609, Short.MAX_VALUE)
                    .addGroup(jPanelSeragamLayout.createSequentialGroup()
                        .addGroup(jPanelSeragamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelSeragamLayout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(104, 104, 104)
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jUnpaidSumbangan, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelSeragamLayout.createSequentialGroup()
                                .addGap(285, 285, 285)
                                .addComponent(jButtonBayarIll))
                            .addComponent(jLabel1))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelSeragamLayout.setVerticalGroup(
            jPanelSeragamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSeragamLayout.createSequentialGroup()
                .addGroup(jPanelSeragamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel19)
                    .addComponent(jUnpaidSumbangan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonBayarIll)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelSeragam, javax.swing.GroupLayout.DEFAULT_SIZE, 619, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelSeragam, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTableSumbanganPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jTableSumbanganPropertyChange
        // TODO add your handling code here:
        sumbanganSToDB = new ArrayList<>();
        if (jTableSumbangan.getRowCount() > 0) {
            for (int i = 0; i < jTableSumbangan.getRowCount(); i++) {
//                if((Boolean)jTableSumbangan.getValueAt(i,3) && (sumbanganS.get(i).transactDetailIDs.size() == 0)){
                if(jTableSumbangan.getModel().getValueAt(i,5) != null){
                    if((Float)jTableSumbangan.getModel().getValueAt(i,5) > 0){
                        sumbanganS.get(i).amount = (Float)jTableSumbangan.getModel().getValueAt(i,5);
                        sumbanganSToDB.add(sumbanganS.get(i));
                    }
                }
                //                    try {
                //sumbangan = Control.selectIuran(Iuran.Tipe.Sumbangan, Sumbangan.noIndukColName, false , profil.noInduk);
                //sumbanganS.remove(i);
//                    } catch (SQLException ex) {
//                        Exceptions.printStackTrace(ex);
//                    } catch (KasirException ex) {
//                        Exceptions.printStackTrace(ex);
//                    }
//                }
            }
        }
    }//GEN-LAST:event_jTableSumbanganPropertyChange

    private void jButtonBayarIllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBayarIllActionPerformed
        // TODO add your handling code here:
        float sumbanganAmountTemp = 0f;

        for (int i = 0; i < sumbanganSToDB.size(); i++) {
            if (sumbanganSToDB.get(i) != null) {

                //sumbanganAmountTemp = sumbanganAmountTemp + (Float) jTableSumbangan.getModel().getValueAt(i, 3);
                sumbanganAmountTemp = sumbanganAmountTemp + sumbanganSToDB.get(i).amount;

            }
        }
        itfs.jTextFieldSumbanganAmountSimple.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0"))));
        itfs.jTextFieldSumbanganAmountSimple.setValue(sumbanganAmountTemp);
        try {
            itfs.jTextFieldSumbanganAmountSimple.commitEdit();
        } catch (ParseException ex) {
            Exceptions.printStackTrace(ex);
        }
        itfs.sumbanganSToDB = sumbanganSToDB;
        itfs.sumbanganS = sumbanganS;
        this.setVisible(false);
    }//GEN-LAST:event_jButtonBayarIllActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public TableModel buildSumbanganTableModel(Profil profil) throws SQLException, KasirException{
       String columnNames[] = {"Kelas","Detail / History", "Transaksi Sumbangan", "Biaya", "Sisa", "Pembayaran", "IuranID"};
       Set<Sumbangan> sumbanganFilters = new HashSet<>();
       sumbanganFilters.add(new Sumbangan(profil.noInduk,null, null, 0F, null));
       Map<Long, Sumbangan> searchResultMap = new HashMap<>();
       searchResultMap = Control.exactFilterSelectIurans(Iuran.Tipe.Sumbangan, sumbanganFilters);
       
       Set<Long> transactDetailIDsTemp = new HashSet<Long>();
       int j = 0;
       sumbanganS = new ArrayList<>();
       ArrayList<Long> sumbanganSPaid = new ArrayList<Long>();
       ArrayList<String> sumbanganSTransactionDate = new ArrayList<String>();
       ArrayList<SumbanganTransactionDetail> stds = new ArrayList<SumbanganTransactionDetail>();
       if(searchResultMap.size() > 0){
        for(Map.Entry<Long, Sumbangan> entry: searchResultMap.entrySet()){
            transactDetailIDsTemp.clear();
            transactDetailIDsTemp = entry.getValue().transactDetailIDs;
            long paidSumbangan = 0l;
            String lastTransactionDate = "";
            SimpleDateFormat formatIndo = new SimpleDateFormat("dd-MM-yyyy");
            SumbanganTransactionDetail std = new SumbanganTransactionDetail();
            stds.clear();
            for(Long l : transactDetailIDsTemp){
                std = Control.selectTDetail(TransactionDetail.Tipe.SumbanganTransaction, l);
                paidSumbangan += std.amount;
                lastTransactionDate = formatIndo.format(std.lastUpdateDate.toDate());
                sumbanganSTransactionDate.add(lastTransactionDate);
                stds.add(std);
            }
            
            if(entry.getValue().amount > paidSumbangan){
                sumbanganS.add(entry.getValue());
                sumbanganSPaid.add(paidSumbangan);
            }
            j++;
        }
       }
       Object[][] data = new Object[sumbanganS.size()][columnNames.length];
       for(int i =0; i < sumbanganS.size(); i++){
            
            data[i][0]= sumbanganS.get(i).chargedLevel;
            data[i][1]= "Detail";
            data[i][2]= sumbanganS.get(i).transactName;
            data[i][3]= sumbanganS.get(i).amount;
            data[i][4]= sumbanganS.get(i).amount-sumbanganSPaid.get(i);
            data[i][5]= 0f;
            data[i][6]= sumbanganS.get(i).id;
//            if(sumbanganS.get(i).transactDetailIDs.size()>0){
//                data[i][3] = new Boolean(true);
//            }else{
//                data[i][3] = new Boolean(false);
//            }
       }
       itfs.unpaidSumbangan = calculateUnpaidSumbangan(profil);
       if(data.length > 0){
       TableModel tm = new DefaultTableModel(data, columnNames){
           @Override
            public boolean isCellEditable(int row, int column) {
                //all cells false for editable
               if(itfs.jDialogTransactionSummary.isVisible()){
                    return false;
               }else{
                    return true;
               }
            }
            public Class getColumnClass(int c) {
                return getValueAt(0, c).getClass();
            }
       };
       
       return tm;
       }else{
           TableModel tm = new DefaultTableModel(columnNames, columnNames.length);
           return tm;
       }
   }
    
    public TableModel buildSumbanganSubmitTableModel(Profil profil, List<Sumbangan> stdb) throws SQLException, KasirException{
       String columnNames[] = {"Kelas","Detail / History", "Transaksi Sumbangan", "Biaya", "Sisa", "Pembayaran", "IuranID"};
       
       Set<Sumbangan> sumbanganFilters = new HashSet<>();
       Set<Long> sumbanganIDs = new HashSet<>();
       for(int i = 0 ; i < stdb.size(); i++){
           sumbanganIDs.add(stdb.get(i).id);
       }
       sumbanganFilters.addAll(stdb);
       Map<Long, Sumbangan> searchResultMap = new HashMap<>();
       //searchResultMap = Control.exactFilterSelectIurans(Iuran.Tipe.Sumbangan, sumbanganFilters);
       searchResultMap = Control.selectIurans(Iuran.Tipe.Sumbangan, sumbanganIDs);
       Set<Long> transactDetailIDsTemp = new HashSet<Long>();
       int j = 0;
       long paidSumbangan = 0l;
       sumbanganS = new ArrayList<>();  
       ArrayList<Long> sumbanganSPaid = new ArrayList<Long>();
       ArrayList<Kalender> sumbanganSTransactionDate = new ArrayList<Kalender>();
       if(searchResultMap.size() > 0){
        for(Map.Entry<Long, Sumbangan> entry: searchResultMap.entrySet()){
            transactDetailIDsTemp.clear();
            transactDetailIDsTemp = entry.getValue().transactDetailIDs;
            paidSumbangan = 0l;
            Kalender lastTransactionDate = new Kalender();
            SumbanganTransactionDetail std = new SumbanganTransactionDetail();
            for(Long l : transactDetailIDsTemp){
                std = Control.selectTDetail(TransactionDetail.Tipe.SumbanganTransaction, l);
                paidSumbangan += std.amount;
                lastTransactionDate = std.lastUpdateDate;
                sumbanganSTransactionDate.add(lastTransactionDate);
            }
            if(transactDetailIDsTemp.isEmpty()){
                sumbanganSTransactionDate.add(new Kalender());
            }
            
            if(entry.getValue().amount > paidSumbangan){
                sumbanganS.add(entry.getValue());
                sumbanganSPaid.add(paidSumbangan);
                
            }
            j++;
        }
       }
       Object[][] data = new Object[sumbanganS.size()][columnNames.length];
       for(int i =0; i < sumbanganS.size(); i++){
            data[i][0]= sumbanganS.get(i).chargedLevel;
            data[i][1]= sumbanganSTransactionDate.get(i);
            data[i][2]= sumbanganS.get(i).transactName;
            data[i][3] = sumbanganS.get(i).amount;
            data[i][4] = sumbanganS.get(i).amount - stdb.get(i).amount - sumbanganSPaid.get(i);
            data[i][5] = stdb.get(i).amount;
            data[i][6] = sumbanganS.get(i).id;
            itfs.unpaidSumbangan = itfs.unpaidSumbangan - stdb.get(i).amount;
       }
       
      
       if(data.length > 0){
       TableModel tm = new DefaultTableModel(data, columnNames){
           @Override
            public boolean isCellEditable(int row, int column) {
                //all cells false for editable
               if(itfs.jDialogTransactionSummary.isVisible()){
                    return false;
               }else{
                    return true;
               }
            }
            public Class getColumnClass(int c) {
                return getValueAt(0, c).getClass();
            }
       };
       
       return tm;
       }else{
           TableModel tm = new DefaultTableModel(columnNames, columnNames.length);
           return tm;
       }
   }
    
    private float calculateUnpaidSumbangan(Profil profil) throws SQLException, KasirException {
       float retVal = 0;
       Set<Sumbangan> sumbanganFilters = new HashSet<>();
       sumbanganFilters.add(new Sumbangan(profil.noInduk,null, null, 0F, null));
       Map<Long, Sumbangan> searchResultMap = new HashMap<>();
       Set<Long> transactDetailIDsTemp = new HashSet<Long>();
       searchResultMap = Control.exactFilterSelectIurans(Iuran.Tipe.Sumbangan, sumbanganFilters);
       sumbanganS = new ArrayList<>();
       
       if(searchResultMap.size() > 0){
        for(Map.Entry<Long, Sumbangan> entry: searchResultMap.entrySet()){
            transactDetailIDsTemp.clear();
            transactDetailIDsTemp = entry.getValue().transactDetailIDs;
            long paidSumbangan = 0l;
            for(Long l : transactDetailIDsTemp){
                paidSumbangan += Control.selectTDetail(TransactionDetail.Tipe.SumbanganTransaction, l).amount;
            }
            
            if(entry.getValue().amount > paidSumbangan){
                sumbanganS.add(entry.getValue());
            }
            retVal += entry.getValue().amount - paidSumbangan;
        }
       }
       unpaidSumbangan = retVal;
       System.out.println("unpaid Sumbangan");
       System.out.println(unpaidSumbangan);
       return retVal;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBayarIll;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JPanel jPanelSeragam;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JTable jTableSumbangan;
    private javax.swing.JTextField jUnpaidSumbangan;
    // End of variables declaration//GEN-END:variables
}
class SumbanganButtonRenderer extends JButton implements TableCellRenderer {

  public SumbanganButtonRenderer() {
    setOpaque(true);
  }

  public Component getTableCellRendererComponent(JTable table, Object value,
      boolean isSelected, boolean hasFocus, int row, int column) {
    if (isSelected) {
      setForeground(table.getSelectionForeground());
      setBackground(table.getSelectionBackground());
    } else {
      setForeground(table.getForeground());
      setBackground(UIManager.getColor("Button.background"));
    }
    setText((value == null) ? "" : value.toString());
    return this;
  }
}

/**
 * @version 1.0 11/09/98
 */

class SumbanganButtonEditor extends DefaultCellEditor {
  protected JButton button;

  private String label;
  private String detail;
  private boolean isPushed;
  private JTable detailTable;
  private JScrollPane scrollPane;
  private ArrayList<SumbanganTransactionDetail> stds;
  public SumbanganButtonEditor(JCheckBox checkBox) {
    super(checkBox);
    button = new JButton();
    button.setOpaque(true);
    button.addActionListener(new ActionListener() {
      public void actionPerformed(ActionEvent e) {
        fireEditingStopped();
      }
    });
  }

  public Component getTableCellEditorComponent(JTable table, Object value,
      boolean isSelected, int row, int column) {
    if (isSelected) {
      button.setForeground(table.getSelectionForeground());
      button.setBackground(table.getSelectionBackground());
    } else {
      button.setForeground(table.getForeground());
      button.setBackground(table.getBackground());
    }
    SimpleDateFormat formatIndo = new SimpleDateFormat("dd-MM-yyyy hh:mm:ss");
    Set<Long> transactDetailIDsTemp = new HashSet<Long>();
    Sumbangan s;
    Long sumbanganID = (Long)table.getModel().getValueAt(row, 6);
    try {
        s = Control.selectIuran(Iuran.Tipe.Sumbangan, sumbanganID);
        transactDetailIDsTemp = s.transactDetailIDs;
    } catch (SQLException ex) {
        Exceptions.printStackTrace(ex);
    } catch (KasirException ex) {
        Exceptions.printStackTrace(ex);
    }
    SumbanganTransactionDetail std = new SumbanganTransactionDetail();
    detail = "";
    
    String columnNames[] = {"No", "Tanggal", "Pembayaran"};
    Object[][] data = new Object[transactDetailIDsTemp.size()][columnNames.length];
    int i = 0;
    for(Long l : transactDetailIDsTemp){
            try {
                std = Control.selectTDetail(TransactionDetail.Tipe.SumbanganTransaction, l);
            } catch (SQLException ex) {
                Exceptions.printStackTrace(ex);
            } catch (KasirException ex) {
                Exceptions.printStackTrace(ex);
            }
            
            detail += String.valueOf(i);
            detail += ". Rp ";
            detail += String.valueOf(std.amount);
            detail += "\t";
            detail += formatIndo.format(std.lastUpdateDate.toDate());
            detail += "\r\n";
            
            data[i][0] = i+1;
            data[i][1] = formatIndo.format(std.lastUpdateDate.toDate());
            data[i][2] = "Rp ".concat(String.valueOf((Float)std.amount));
            i++;
    }
    
    TableModel tm = new DefaultTableModel(data, columnNames){
           @Override
            public boolean isCellEditable(int row, int column) {
                //all cells false for editable
               return false;
            }
            public Class getColumnClass(int c) {
                return getValueAt(0, c).getClass();
            }
       };
    
    detailTable = new JTable(tm){
        public Class getColumnClass(int c){
            return getValueAt(0, c).getClass();
        }
    };
    
    
    scrollPane = new JScrollPane(detailTable);
    
    
    label = (value == null) ? "" : value.toString();
    
    button.setText(label);
    isPushed = true;
    return button;
  }

  public Object getCellEditorValue() {
    if (isPushed) {
      // 
      // 
      JOptionPane.showMessageDialog(button, scrollPane, "Sumbangan", JOptionPane.INFORMATION_MESSAGE);
      
      // System.out.println(label + ": Ouch!");
    }
    isPushed = false;
    return new String(label);
  }

  public boolean stopCellEditing() {
    isPushed = false;
    return super.stopCellEditing();
  }

  protected void fireEditingStopped() {
    super.fireEditingStopped();
  }
}
