/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import iuran.Iuran;
import iuran.Seragam;
import iuran.SeragamTransactionDetail;
import iuran.TransactionDetail;
import java.awt.Component;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumnModel;
import javax.swing.table.TableModel;
import kasir.Control;
import org.openide.util.Exceptions;
import pelajar.Profil;
import sak.Kalender;
import sak.KasirException;

/**
 *
 * @author Master
 */
public class InputTransactionSeragam extends javax.swing.JFrame {
    Profil profil;
    private Seragam seragam;
    private List<Seragam> seragamS;
    private List<Seragam> seragamSToDB;
    private float unpaidSeragam = 0f;
    private InputTransactionFrameSeparated itfs;
    private TableModel tableModelSeragam;
    /**
     * Creates new form InputTransactionSeragam
     */
    public InputTransactionSeragam(Profil profil, InputTransactionFrameSeparated itfs) {
        this.profil = profil;
        this.itfs = itfs;
        try{
            tableModelSeragam = buildSeragamTableModel(profil);
        }catch(SQLException ex){
            ex.printStackTrace();
        }catch(KasirException ex){
            ex.printStackTrace();
        }
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelSeragam = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableSeragam = new javax.swing.JTable();
        jLabel19 = new javax.swing.JLabel();
        jUnpaidSeragam = new javax.swing.JTextField();
        jButtonBayarSeragam = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jPanelSeragam.setMinimumSize(new java.awt.Dimension(440, 550));
        jPanelSeragam.setPreferredSize(new java.awt.Dimension(480, 302));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel10.setText(org.openide.util.NbBundle.getMessage(InputTransactionSeragam.class, "InputTransactionSeragam.jLabel10.text")); // NOI18N

        try{
            tableModelSeragam = buildSeragamTableModel(profil);
        }catch(Exception e){
            e.printStackTrace();
        }
        jTableSeragam.setModel(tableModelSeragam);
        jTableSeragam.getColumn("Detail / History").setCellRenderer(new SeragamButtonRenderer());
        jTableSeragam.getColumn("Detail / History").setCellEditor(
            new SeragamButtonEditor(new JCheckBox()));
        jTableSeragam.removeColumn(jTableSeragam.getColumn("IuranID"));
        jTableSeragam.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jTableSeragamPropertyChange(evt);
            }
        });
        jScrollPane2.setViewportView(jTableSeragam);

        jLabel19.setText(org.openide.util.NbBundle.getMessage(InputTransactionSeragam.class, "InputTransactionSeragam.jLabel19.text")); // NOI18N

        jUnpaidSeragam.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jUnpaidSeragam.setText(String.valueOf(unpaidSeragam));
        jUnpaidSeragam.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jUnpaidSeragam.setEnabled(false);

        jButtonBayarSeragam.setText(org.openide.util.NbBundle.getMessage(InputTransactionSeragam.class, "InputTransactionSeragam.jButtonBayarSeragam.text")); // NOI18N
        jButtonBayarSeragam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBayarSeragamActionPerformed(evt);
            }
        });

        jLabel1.setText(profil.biodata.nama);

        javax.swing.GroupLayout jPanelSeragamLayout = new javax.swing.GroupLayout(jPanelSeragam);
        jPanelSeragam.setLayout(jPanelSeragamLayout);
        jPanelSeragamLayout.setHorizontalGroup(
            jPanelSeragamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSeragamLayout.createSequentialGroup()
                .addGroup(jPanelSeragamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 609, Short.MAX_VALUE)
                    .addGroup(jPanelSeragamLayout.createSequentialGroup()
                        .addGroup(jPanelSeragamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelSeragamLayout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(104, 104, 104)
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jUnpaidSeragam, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelSeragamLayout.createSequentialGroup()
                                .addGap(285, 285, 285)
                                .addComponent(jButtonBayarSeragam))
                            .addComponent(jLabel1))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelSeragamLayout.setVerticalGroup(
            jPanelSeragamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSeragamLayout.createSequentialGroup()
                .addGroup(jPanelSeragamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel19)
                    .addComponent(jUnpaidSeragam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonBayarSeragam)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelSeragam, javax.swing.GroupLayout.DEFAULT_SIZE, 619, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelSeragam, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTableSeragamPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jTableSeragamPropertyChange
        // TODO add your handling code here:
        seragamSToDB = new ArrayList<>();
        if (jTableSeragam.getRowCount() > 0) {
            for (int i = 0; i < jTableSeragam.getRowCount(); i++) {
//                if((Boolean)jTableSeragam.getValueAt(i,3) && (seragamS.get(i).transactDetailIDs.size() == 0)){
                if(jTableSeragam.getModel().getValueAt(i,5) != null){
                    if((Float)jTableSeragam.getModel().getValueAt(i,5) > 0){
                        seragamS.get(i).amount = (Float)jTableSeragam.getModel().getValueAt(i,5);
                        seragamSToDB.add(seragamS.get(i));
                    }
                }
                //                    try {
                //seragam = Control.selectIuran(Iuran.Tipe.Seragam, Seragam.noIndukColName, false , profil.noInduk);
                //seragamS.remove(i);
//                    } catch (SQLException ex) {
//                        Exceptions.printStackTrace(ex);
//                    } catch (KasirException ex) {
//                        Exceptions.printStackTrace(ex);
//                    }
//                }
            }
        }
    }//GEN-LAST:event_jTableSeragamPropertyChange

    private void jButtonBayarSeragamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBayarSeragamActionPerformed
        // TODO add your handling code here:
        float seragamAmountTemp = 0f;

        for (int i = 0; i < seragamSToDB.size(); i++) {
            if (seragamSToDB.get(i) != null) {

                //seragamAmountTemp = seragamAmountTemp + (Float) jTableSeragam.getModel().getValueAt(i, 3);
                seragamAmountTemp = seragamAmountTemp + seragamSToDB.get(i).amount;

            }
        }
        itfs.jTextFieldSeragamAmountSimple.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0"))));
        itfs.jTextFieldSeragamAmountSimple.setValue(seragamAmountTemp);
        try {
            itfs.jTextFieldSeragamAmountSimple.commitEdit();
        } catch (ParseException ex) {
            Exceptions.printStackTrace(ex);
        }
        itfs.seragamSToDB = seragamSToDB;
        itfs.seragamS = seragamS;
        this.setVisible(false);
    }//GEN-LAST:event_jButtonBayarSeragamActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public TableModel buildSeragamTableModel(Profil profil) throws SQLException, KasirException{
       String columnNames[] = {"Kelas","Detail / History", "Transaksi Seragam", "Biaya", "Sisa", "Pembayaran", "IuranID"};
       Set<Seragam> seragamFilters = new HashSet<>();
       seragamFilters.add(new Seragam(profil.noInduk,null, null, 0F, null));
       Map<Long, Seragam> searchResultMap = new HashMap<>();
       searchResultMap = Control.exactFilterSelectIurans(Iuran.Tipe.Seragam, seragamFilters);
       
       Set<Long> transactDetailIDsTemp = new HashSet<Long>();
       int j = 0;
       seragamS = new ArrayList<>();
       ArrayList<Long> seragamSPaid = new ArrayList<Long>();
       ArrayList<String> seragamSTransactionDate = new ArrayList<String>();
       ArrayList<SeragamTransactionDetail> stds = new ArrayList<SeragamTransactionDetail>();
       if(searchResultMap.size() > 0){
        for(Map.Entry<Long, Seragam> entry: searchResultMap.entrySet()){
            transactDetailIDsTemp.clear();
            transactDetailIDsTemp = entry.getValue().transactDetailIDs;
            long paidSeragam = 0l;
            String lastTransactionDate = "";
            SimpleDateFormat formatIndo = new SimpleDateFormat("dd-MM-yyyy");
            SeragamTransactionDetail std = new SeragamTransactionDetail();
            stds.clear();
            for(Long l : transactDetailIDsTemp){
                std = Control.selectTDetail(TransactionDetail.Tipe.SeragamTransaction, l);
                paidSeragam += std.amount;
                lastTransactionDate = formatIndo.format(std.lastUpdateDate.toDate());
                seragamSTransactionDate.add(lastTransactionDate);
                stds.add(std);
            }
            
            if(entry.getValue().amount > paidSeragam){
                seragamS.add(entry.getValue());
                seragamSPaid.add(paidSeragam);
            }
            j++;
        }
       }
       Object[][] data = new Object[seragamS.size()][columnNames.length];
       for(int i =0; i < seragamS.size(); i++){
            
            data[i][0]= seragamS.get(i).chargedLevel;
            data[i][1]= "Detail";
            data[i][2]= seragamS.get(i).transactName;
            data[i][3]= seragamS.get(i).amount;
            data[i][4]= seragamS.get(i).amount-seragamSPaid.get(i);
            data[i][5]= 0f;
            data[i][6]= seragamS.get(i).id;
//            if(seragamS.get(i).transactDetailIDs.size()>0){
//                data[i][3] = new Boolean(true);
//            }else{
//                data[i][3] = new Boolean(false);
//            }
       }
       itfs.unpaidSeragam = calculateUnpaidSeragam(profil);
       if(data.length > 0){
       TableModel tm = new DefaultTableModel(data, columnNames){
           @Override
            public boolean isCellEditable(int row, int column) {
                //all cells false for editable
               if(itfs.jDialogTransactionSummary.isVisible()){
                    return false;
               }else{
                    return true;
               }
            }
            public Class getColumnClass(int c) {
                return getValueAt(0, c).getClass();
            }
       };
       
       return tm;
       }else{
           TableModel tm = new DefaultTableModel(columnNames, columnNames.length);
           return tm;
       }
   }
    
    public TableModel buildSeragamSubmitTableModel(Profil profil, List<Seragam> stdb) throws SQLException, KasirException{
       String columnNames[] = {"Kelas","Detail / History", "Transaksi Seragam", "Biaya", "Sisa", "Pembayaran", "IuranID"};
       
       Set<Seragam> seragamFilters = new HashSet<>();
       Set<Long> seragamIDs = new HashSet<>();
       for(int i = 0 ; i < stdb.size(); i++){
           seragamIDs.add(stdb.get(i).id);
       }
       seragamFilters.addAll(stdb);
       Map<Long, Seragam> searchResultMap = new HashMap<>();
       //searchResultMap = Control.exactFilterSelectIurans(Iuran.Tipe.Seragam, seragamFilters);
       searchResultMap = Control.selectIurans(Iuran.Tipe.Seragam, seragamIDs);
       Set<Long> transactDetailIDsTemp = new HashSet<Long>();
       int j = 0;
       long paidSeragam = 0l;
       seragamS = new ArrayList<>();  
       ArrayList<Long> seragamSPaid = new ArrayList<Long>();
       ArrayList<Kalender> seragamSTransactionDate = new ArrayList<Kalender>();
       if(searchResultMap.size() > 0){
        for(Map.Entry<Long, Seragam> entry: searchResultMap.entrySet()){
            transactDetailIDsTemp.clear();
            transactDetailIDsTemp = entry.getValue().transactDetailIDs;
            paidSeragam = 0l;
            Kalender lastTransactionDate = new Kalender();
            SeragamTransactionDetail std = new SeragamTransactionDetail();
            for(Long l : transactDetailIDsTemp){
                std = Control.selectTDetail(TransactionDetail.Tipe.SeragamTransaction, l);
                paidSeragam += std.amount;
                lastTransactionDate = std.lastUpdateDate;
                seragamSTransactionDate.add(lastTransactionDate);
            }
            if(transactDetailIDsTemp.isEmpty()){
                seragamSTransactionDate.add(new Kalender());
            }
            
            if(entry.getValue().amount > paidSeragam){
                seragamS.add(entry.getValue());
                seragamSPaid.add(paidSeragam);
                
            }
            j++;
        }
       }
       Object[][] data = new Object[seragamS.size()][columnNames.length];
       for(int i =0; i < seragamS.size(); i++){
            data[i][0]= seragamS.get(i).chargedLevel;
            data[i][1]= seragamSTransactionDate.get(i);
            data[i][2]= seragamS.get(i).transactName;
            data[i][3] = seragamS.get(i).amount;
            data[i][4] = seragamS.get(i).amount - stdb.get(i).amount - seragamSPaid.get(i);
            data[i][5] = stdb.get(i).amount;
            data[i][6] = seragamS.get(i).id;
            itfs.unpaidSeragam = itfs.unpaidSeragam - stdb.get(i).amount;
       }
       
      
       if(data.length > 0){
       TableModel tm = new DefaultTableModel(data, columnNames){
           @Override
            public boolean isCellEditable(int row, int column) {
                //all cells false for editable
               if(itfs.jDialogTransactionSummary.isVisible()){
                    return false;
               }else{
                    return true;
               }
            }
            public Class getColumnClass(int c) {
                return getValueAt(0, c).getClass();
            }
       };
       
       return tm;
       }else{
           TableModel tm = new DefaultTableModel(columnNames, columnNames.length);
           return tm;
       }
   }
    
    private float calculateUnpaidSeragam(Profil profil) throws SQLException, KasirException {
       float retVal = 0;
       Set<Seragam> seragamFilters = new HashSet<>();
       seragamFilters.add(new Seragam(profil.noInduk,null, null, 0F, null));
       Map<Long, Seragam> searchResultMap = new HashMap<>();
       Set<Long> transactDetailIDsTemp = new HashSet<Long>();
       searchResultMap = Control.exactFilterSelectIurans(Iuran.Tipe.Seragam, seragamFilters);
       seragamS = new ArrayList<>();
       
       if(searchResultMap.size() > 0){
        for(Map.Entry<Long, Seragam> entry: searchResultMap.entrySet()){
            transactDetailIDsTemp.clear();
            transactDetailIDsTemp = entry.getValue().transactDetailIDs;
            long paidSeragam = 0l;
            for(Long l : transactDetailIDsTemp){
                paidSeragam += Control.selectTDetail(TransactionDetail.Tipe.SeragamTransaction, l).amount;
            }
            
            if(entry.getValue().amount > paidSeragam){
                seragamS.add(entry.getValue());
            }
            retVal += entry.getValue().amount - paidSeragam;
        }
       }
       unpaidSeragam = retVal;
       System.out.println("unpaid Seragam");
       System.out.println(unpaidSeragam);
       return retVal;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBayarSeragam;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JPanel jPanelSeragam;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableSeragam;
    private javax.swing.JTextField jUnpaidSeragam;
    // End of variables declaration//GEN-END:variables
}

/**
 * @version 1.0 11/09/98
 */

class SeragamButtonRenderer extends JButton implements TableCellRenderer {

  public SeragamButtonRenderer() {
    setOpaque(true);
  }

  public Component getTableCellRendererComponent(JTable table, Object value,
      boolean isSelected, boolean hasFocus, int row, int column) {
    if (isSelected) {
      setForeground(table.getSelectionForeground());
      setBackground(table.getSelectionBackground());
    } else {
      setForeground(table.getForeground());
      setBackground(UIManager.getColor("Button.background"));
    }
    setText((value == null) ? "" : value.toString());
    return this;
  }
}

/**
 * @version 1.0 11/09/98
 */

class SeragamButtonEditor extends DefaultCellEditor {
  protected JButton button;

  private String label;
  private String detail;
  private boolean isPushed;
  private JTable detailTable;
  private JScrollPane scrollPane;
  private ArrayList<SeragamTransactionDetail> stds;
  public SeragamButtonEditor(JCheckBox checkBox) {
    super(checkBox);
    button = new JButton();
    button.setOpaque(true);
    button.addActionListener(new ActionListener() {
      public void actionPerformed(ActionEvent e) {
        fireEditingStopped();
      }
    });
  }

  public Component getTableCellEditorComponent(JTable table, Object value,
      boolean isSelected, int row, int column) {
    if (isSelected) {
      button.setForeground(table.getSelectionForeground());
      button.setBackground(table.getSelectionBackground());
    } else {
      button.setForeground(table.getForeground());
      button.setBackground(table.getBackground());
    }
    SimpleDateFormat formatIndo = new SimpleDateFormat("dd-MM-yyyy hh:mm:ss");
    Set<Long> transactDetailIDsTemp = new HashSet<Long>();
    Seragam s;
    Long seragamID = (Long)table.getModel().getValueAt(row, 6);
    try {
        s = Control.selectIuran(Iuran.Tipe.Seragam, seragamID);
        transactDetailIDsTemp = s.transactDetailIDs;
    } catch (SQLException ex) {
        Exceptions.printStackTrace(ex);
    } catch (KasirException ex) {
        Exceptions.printStackTrace(ex);
    }
    SeragamTransactionDetail std = new SeragamTransactionDetail();
    detail = "";
    
    String columnNames[] = {"No", "Tanggal", "Pembayaran"};
    Object[][] data = new Object[transactDetailIDsTemp.size()][columnNames.length];
    int i = 0;
    for(Long l : transactDetailIDsTemp){
            try {
                std = Control.selectTDetail(TransactionDetail.Tipe.SeragamTransaction, l);
            } catch (SQLException ex) {
                Exceptions.printStackTrace(ex);
            } catch (KasirException ex) {
                Exceptions.printStackTrace(ex);
            }
            
            detail += String.valueOf(i);
            detail += ". Rp ";
            detail += String.valueOf(std.amount);
            detail += "\t";
            detail += formatIndo.format(std.lastUpdateDate.toDate());
            detail += "\r\n";
            
            data[i][0] = i+1;
            data[i][1] = formatIndo.format(std.lastUpdateDate.toDate());
            data[i][2] = "Rp ".concat(String.valueOf((Float)std.amount));
            i++;
    }
    
    TableModel tm = new DefaultTableModel(data, columnNames){
           @Override
            public boolean isCellEditable(int row, int column) {
                //all cells false for editable
               return false;
            }
            public Class getColumnClass(int c) {
                return getValueAt(0, c).getClass();
            }
       };
    
    detailTable = new JTable(tm){
        public Class getColumnClass(int c){
            return getValueAt(0, c).getClass();
        }
    };
    
    
    scrollPane = new JScrollPane(detailTable);
    
    
    label = (value == null) ? "" : value.toString();
    
    button.setText(label);
    isPushed = true;
    return button;
  }

  public Object getCellEditorValue() {
    if (isPushed) {
      // 
      // 
      JOptionPane.showMessageDialog(button, scrollPane, "Seragam", JOptionPane.INFORMATION_MESSAGE);
      
      // System.out.println(label + ": Ouch!");
    }
    isPushed = false;
    return new String(label);
  }

  public boolean stopCellEditing() {
    isPushed = false;
    return super.stopCellEditing();
  }

  protected void fireEditingStopped() {
    super.fireEditingStopped();
  }
}
