/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import iuran.*;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.*;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import kasir.Control;
import org.openide.util.Exceptions;
import pelajar.Level;
import pelajar.Profil;
import printout.TunggakanBean;
import sak.KasirException;

/**
 *
 * @author Master
 */
public class InputTransactionIKS extends javax.swing.JFrame {
    Profil profil;
    private TableModel tableModelIKS;
    private IKS iksFromDB;
    public List<Integer> tahunIKS;
    public ArrayList<Float> iDDAmounts;
    public ArrayList<Float> beasiswaAmounts;
    public ArrayList<Float> beasiswaCostAmounts;
    public ArrayList<Float> iKSAmounts;
    private IKS iksCurrent;
    private IKS iksStoreToDB;
    private IDD idd;
    private InputTransactionFrameSeparated itfs;
    private final String[] namaBulan = {"IKS"};
    private float unpaidIKS;
    private ComboBoxModel tahunComboBoxModel;
    private String tunggakanIKSString = new String("");
    private String tunggakanIKSEachAmountString = new String("");
    private float iksDebt;
    /**
     * Creates new form InputTransactionIKS
     */
    
    public InputTransactionIKS(Profil profil, InputTransactionFrameSeparated itfs) {
        this.profil = profil;
        this.itfs = itfs;
        try {
            tableModelIKS = buildIKSTableModel(profil, profil.currentLevel.tahun);
        } catch (SQLException ex) {
            Exceptions.printStackTrace(ex);
        } catch (KasirException ex) {
            Exceptions.printStackTrace(ex);
        }
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelIPP = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabelTahun = new javax.swing.JLabel();
        jComboBoxTahun = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jUnpaidIKS = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTableIKS = new javax.swing.JTable();
        jButtonBayarIUS = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jFormattedTextFieldIDDSaldo = new javax.swing.JFormattedTextField();
        jTextFieldIKSDebt = new javax.swing.JFormattedTextField();

        setTitle(org.openide.util.NbBundle.getMessage(InputTransactionIKS.class, "InputTransactionIKS.title")); // NOI18N

        jPanelIPP.setMinimumSize(new java.awt.Dimension(570, 380));
        jPanelIPP.setPreferredSize(new java.awt.Dimension(680, 450));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText(org.openide.util.NbBundle.getMessage(InputTransactionIKS.class, "InputTransactionIKS.jLabel1.text")); // NOI18N

        jLabelTahun.setText(org.openide.util.NbBundle.getMessage(InputTransactionIKS.class, "InputTransactionIKS.jLabelTahun.text")); // NOI18N

        try{
            tahunComboBoxModel = buildIKStahunComboBoxModel(profil);
        }catch(SQLException ex){
            ex.printStackTrace();
        }catch(KasirException ex){
            ex.printStackTrace();
        }
        jComboBoxTahun.setModel(tahunComboBoxModel);
        jComboBoxTahun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTahunActionPerformed(evt);
            }
        });
        jComboBoxTahun.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jComboBoxTahunPropertyChange(evt);
            }
        });

        jLabel2.setText(org.openide.util.NbBundle.getMessage(InputTransactionIKS.class, "InputTransactionIKS.jLabel2.text")); // NOI18N

        jUnpaidIKS.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jUnpaidIKS.setText(String.valueOf(unpaidIKS));
        jUnpaidIKS.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jUnpaidIKS.setEnabled(false);

        jTableIKS.setModel(tableModelIKS);
        jTableIKS.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jTableIKS.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTableIKSFocusLost(evt);
            }
        });
        jTableIKS.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jTableIKSPropertyChange(evt);
            }
        });
        jScrollPane5.setViewportView(jTableIKS);

        jButtonBayarIUS.setText(org.openide.util.NbBundle.getMessage(InputTransactionIKS.class, "InputTransactionIKS.jButtonBayarIUS.text")); // NOI18N
        jButtonBayarIUS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBayarIUSActionPerformed(evt);
            }
        });

        jLabel3.setText(org.openide.util.NbBundle.getMessage(InputTransactionIKS.class, "InputTransactionIKS.jLabel3.text")); // NOI18N

        jFormattedTextFieldIDDSaldo.setText(org.openide.util.NbBundle.getMessage(InputTransactionIKS.class, "InputTransactionIKS.jFormattedTextFieldIDDSaldo.text")); // NOI18N
        jFormattedTextFieldIDDSaldo.setEnabled(false);

        jTextFieldIKSDebt.setEditable(false);
        jTextFieldIKSDebt.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0"))));

        javax.swing.GroupLayout jPanelIPPLayout = new javax.swing.GroupLayout(jPanelIPP);
        jPanelIPP.setLayout(jPanelIPPLayout);
        jPanelIPPLayout.setHorizontalGroup(
            jPanelIPPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelIPPLayout.createSequentialGroup()
                .addGroup(jPanelIPPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelIPPLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE))
                    .addGroup(jPanelIPPLayout.createSequentialGroup()
                        .addGroup(jPanelIPPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelIPPLayout.createSequentialGroup()
                                .addGap(248, 248, 248)
                                .addComponent(jButtonBayarIUS))
                            .addGroup(jPanelIPPLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1)
                                .addGap(29, 29, 29)
                                .addComponent(jLabelTahun)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanelIPPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jComboBoxTahun, 0, 101, Short.MAX_VALUE)
                                    .addComponent(jTextFieldIKSDebt))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanelIPPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanelIPPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jUnpaidIKS, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jFormattedTextFieldIDDSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 77, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelIPPLayout.setVerticalGroup(
            jPanelIPPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelIPPLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanelIPPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxTahun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTahun)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jUnpaidIKS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelIPPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jFormattedTextFieldIDDSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldIKSDebt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonBayarIUS)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelIPP, javax.swing.GroupLayout.DEFAULT_SIZE, 570, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelIPP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxTahunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTahunActionPerformed
        // TODO add your handling code here:
        try {
            this.tableModelIKS = (DefaultTableModel) buildIKSTableModel(this.profil, this.tahunIKS.get(jComboBoxTahun.getSelectedIndex()));
            jTableIKS.setModel(this.tableModelIKS);
            jTextFieldIKSDebt.setValue(iksDebt);
        } catch (SQLException ex) {
            ex.printStackTrace();
        } catch (KasirException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jComboBoxTahunActionPerformed

    private void jComboBoxTahunPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jComboBoxTahunPropertyChange
        // TODO add your handling code here:
        try {
            if (this.jComboBoxTahun.getSelectedItem() != null) {
                this.tableModelIKS = (DefaultTableModel) buildIKSTableModel(this.profil, this.tahunIKS.get(jComboBoxTahun.getSelectedIndex()));
                jTableIKS.setModel(this.tableModelIKS);
                jTextFieldIKSDebt.setValue(iksDebt);
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(rootPane, "Koneksi Error!\r\n".concat(ex.toString()));
        } catch (KasirException ex) {
            JOptionPane.showMessageDialog(rootPane, "IKS Belum Di Setting!\r\n".concat(ex.toString()));
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jComboBoxTahunPropertyChange

    private void jTableIKSFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTableIKSFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTableIKSFocusLost

    private void jTableIKSPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jTableIKSPropertyChange
        // TODO add your handling code here:
        //IDD, Beasiswa, Beasiswa Cost
        iKSAmounts = new ArrayList();
        iDDAmounts = new ArrayList();
        beasiswaAmounts = new ArrayList();
        beasiswaCostAmounts = new ArrayList();
        /////BLOOOOOOOOOOM SELESAIIIIIIIIIIIIIIIIIIII
        int i = 0;
        iksCurrent = new IKS();
        iksStoreToDB = new IKS();
        ArrayList<Entry> entry = new ArrayList<>();
        if (iksFromDB.entries.size() != 0) {
            for (i = 0; i < jTableIKS.getRowCount(); i++) {
                iksCurrent.entries.add((Boolean) jTableIKS.getValueAt(i, 2) ? ((iksFromDB.entries.get(i).transactDetailIDs.size() > 0) ? new Entry(i, iksFromDB.entries.get(i).amount, iksFromDB.entries.get(i).debt, iksFromDB.entries.get(i).transactDetailIDs) : new Entry(i, iksFromDB.entries.get(i).amount)) : null);
                //below condition is when jTableIKS checkBox is UNCHECK ????
                if (iksCurrent.entries.get(i) == null) {
                    iksStoreToDB.entries.add(null);
                    jTableIKS.setValueAt(0f, i, 3);
                    jTableIKS.setValueAt(0f, i, 4);
                    jTableIKS.setValueAt(0f, i, 5);
                    jTableIKS.setValueAt(0f, i, 6);
                    iKSAmounts.add(0f);
                    iDDAmounts.add(0f);
                    beasiswaAmounts.add(0f);
                    beasiswaCostAmounts.add(0f);
                    //below is when jTableIKS property changed, especially check box is Changed or Editing IDD, Beasiswa, Beasiswa Cost 
                } else if ((iksCurrent.entries.get(i) != null) ^ (iksFromDB.entries.get(i).transactDetailIDs.size() > 0)) {
                    System.out.println("IDD dari db ");
                    if (idd != null) {
                        System.out.println(idd.amount);
                    }
                    iKSAmounts.add((Float) jTableIKS.getModel().getValueAt(i,3));
                    iDDAmounts.add((Float) jTableIKS.getValueAt(i, 4));
                    beasiswaAmounts.add((Float) jTableIKS.getValueAt(i, 5));
                    beasiswaCostAmounts.add((Float) jTableIKS.getValueAt(i, 6));
                    //jTableIKS.setValueAt(iksFromDB.entries.get(i).amount - (iDDAmounts.get(i) + beasiswaAmounts.get(i) + beasiswaCostAmounts.get(i)), i, 3);
                    //iksStoreToDB.entries.add(new Entry(i, iksFromDB.entries.get(i).amount));
                    iksStoreToDB.entries.add(new Entry(i, iKSAmounts.get(i)+iDDAmounts.get(i)+beasiswaAmounts.get(i)+beasiswaCostAmounts.get(i)));
                } else {
                    try {
                        if(isIKSEnough(iksFromDB.entries.get(i).transactDetailIDs, iksFromDB.entries.get(i).amount)){
                            iKSAmounts.add(0f);
                            iDDAmounts.add(0f);
                            beasiswaAmounts.add(0f);
                            beasiswaCostAmounts.add(0f);
                            iksStoreToDB.entries.add(null);
                        }else{
                            iKSAmounts.add((Float) jTableIKS.getModel().getValueAt(i,3));
                            iDDAmounts.add((Float) jTableIKS.getValueAt(i, 4));
                            beasiswaAmounts.add((Float) jTableIKS.getValueAt(i, 5));
                            beasiswaCostAmounts.add((Float) jTableIKS.getValueAt(i, 6));
                            iksStoreToDB.entries.add(new Entry(i, iKSAmounts.get(i)+iDDAmounts.get(i)+beasiswaAmounts.get(i)+beasiswaCostAmounts.get(i)));
                        }
                    } catch (SQLException ex) {
                        Exceptions.printStackTrace(ex);
                    } catch (KasirException ex) {
                        Exceptions.printStackTrace(ex);
                    }
                    

                }
                //iksCurrent.entries.add((Boolean)jTableIKS.getValueAt(i,2)? new IKS(profil.noInduk, new Level(null,null,null,(Integer)jComboBoxTahun.getSelectedItem()),entry).entries.get(i): null);
                //iksStoreToDB.entries.add(iksCurrent.entries.get(i)==null?null:(((iksCurrent.entries.get(i)!=null)^(iksFromDB.entries.get(i)!=null))? new IKS(profil.noInduk, new Level(null,null,null,(int)jComboBoxTahun.getSelectedItem()),entry).entries.get(i):iksCurrent.entries.get(i)));
                //System.out.println("IKS Period: "+iksCurrent.entries.get(i).period);
            }
        }
    }//GEN-LAST:event_jTableIKSPropertyChange

    private void jButtonBayarIUSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBayarIUSActionPerformed
        // TODO add your handling code here:
        float iksAmountTemp = 0f;
        for (int i = 0; i < 1; i++) {
            if (iksStoreToDB.entries.get(i) != null) {
                //iksAmountTemp = iksAmountTemp + iksFromDB.entries.get(i).amount;
                iksAmountTemp = iksAmountTemp + (Float)jTableIKS.getModel().getValueAt(i,3)
                                +(Float)jTableIKS.getModel().getValueAt(i,4)
                                +(Float)jTableIKS.getModel().getValueAt(i,5)
                                +(Float)jTableIKS.getModel().getValueAt(i,6);
            }
        }
        itfs.jTextFieldIKSAmountSimple.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0"))));
        itfs.jTextFieldIKSAmountSimple.setValue(iksAmountTemp);
        try {
            itfs.jTextFieldIKSAmountSimple.commitEdit();
        } catch (ParseException ex) {
            Exceptions.printStackTrace(ex);
        }
        itfs.iksCurrent = iksCurrent;
        itfs.iksFromDB = iksFromDB;
        itfs.iksStoreToDB = iksStoreToDB;
        this.setVisible(false);

    }//GEN-LAST:event_jButtonBayarIUSActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InputTransactionFrameSeparated.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InputTransactionFrameSeparated.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InputTransactionFrameSeparated.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InputTransactionFrameSeparated.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                //new InputTransactionIKS().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBayarIUS;
    public javax.swing.JComboBox jComboBoxTahun;
    private javax.swing.JFormattedTextField jFormattedTextFieldIDDSaldo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelTahun;
    private javax.swing.JPanel jPanelIPP;
    private javax.swing.JScrollPane jScrollPane5;
    public javax.swing.JTable jTableIKS;
    private javax.swing.JFormattedTextField jTextFieldIKSDebt;
    private javax.swing.JTextField jUnpaidIKS;
    // End of variables declaration//GEN-END:variables

    public TableModel buildIKSTableModel(Profil profil, int tahun) throws SQLException, KasirException {
       String columnNames[] = {"Semester", "Biaya IKS", "Check Box", "Tunai", "Iuran Dibayar Dimuka", "Beasiswa", "Beasiswa Yayasan"};
       Set<IKS> iksFilters = new HashSet<>();
       ArrayList<Entry> entries = new ArrayList<>();
       iksFilters.clear();
       iksFilters.add(new IKS(profil.noInduk, new Level(null,null,null,0), entries));
       Map<Long, IKS> searchResultMap = Control.exactFilterSelectIurans(Iuran.Tipe.IKS, iksFilters);
       Object[][] data = new Object[1][7];
       int i = 0;
       final boolean[] canEdit = new boolean [1];
       iksFromDB = new IKS();
       float amountIKSinTable;
       float amountIKSinTDetail;
       iksDebt = 0f;
       if(searchResultMap.size() > 0){
        for(Map.Entry<Long, IKS> entry: searchResultMap.entrySet()){
            for(int j =0 ; j< entry.getValue().entries.size(); j++){
                data[j][0]= namaBulan[j];//entry.getValue().entries.get(j).period;
                data[j][1]= entry.getValue().entries.get(j).amount - calculatePaidIKS(entry.getValue().entries.get(j).transactDetailIDs); // ANEH NIH MASA BEGINI, DI KALI DUA SIH?
                amountIKSinTable = entry.getValue().entries.get(j).amount;
                iksDebt += entry.getValue().entries.get(j).debt;
                //if(jTable2 != null){data[j][2]= jTable2.getModel().getValueAt(j,2);}else{data[j][2]= new Boolean(false);}
                //if(entry.getValue().entries.get(j).transactDetailIDs.size() > 0){
                if(isIKSEnough(entry.getValue().entries.get(j).transactDetailIDs, amountIKSinTable)){        
//                    
                    data[j][2] = new Boolean(true);
                    Float data3 = 0f;
                    Float data4 = 0f;
                    Float data5 = 0f;
                    Float data6 = 0f;
                    
                    for(Long setTDetailIds:entry.getValue().entries.get(j).transactDetailIDs){
                        System.out.println(setTDetailIds + " Set TDetailsID");
                        if(Control.selectTDetail(TransactionDetail.Tipe.IKSTransaction, setTDetailIds).paymentMethod == TransactionDetail.PaymentMethod.CASH){
                            data3 += Control.selectTDetail(TransactionDetail.Tipe.IKSTransaction, setTDetailIds).amount;
                            data[j][3] = data3;
                        }
                        if(Control.selectTDetail(TransactionDetail.Tipe.IKSTransaction, setTDetailIds).paymentMethod == TransactionDetail.PaymentMethod.IDD){
                            data4 += Control.selectTDetail(TransactionDetail.Tipe.IKSTransaction, setTDetailIds).amount;
                            data[j][4] = data4;
                        }
                        if(Control.selectTDetail(TransactionDetail.Tipe.IKSTransaction, setTDetailIds).paymentMethod == TransactionDetail.PaymentMethod.BEASISWA){
                            data5 += Control.selectTDetail(TransactionDetail.Tipe.IKSTransaction, setTDetailIds).amount;
                            data[j][5] = data5;
                        }
                        if(Control.selectTDetail(TransactionDetail.Tipe.IKSTransaction, setTDetailIds).paymentMethod == TransactionDetail.PaymentMethod.BEASISWA_COST){
                            data6 += Control.selectTDetail(TransactionDetail.Tipe.IKSTransaction, setTDetailIds).amount;
                            data[j][6] = data6;
                        }
                    }
                    if(data[j][3] == null){
                        data[j][3] = 0f;
                    }
                    if(data[j][4] == null){
                        data[j][4] = 0f;
                    }
                    if(data[j][5] == null){
                        data[j][5] = 0f;
                    }
                    if(data[j][6] == null){
                        data[j][6] = 0f;
                    }
                            
                }else{
                    data[j][2] = new Boolean(false);
                    if(entry.getValue().entries.get(j).transactDetailIDs.size() > 0){
                        for(Long setTDetailIds:entry.getValue().entries.get(j).transactDetailIDs){
                            System.out.println(setTDetailIds + " Set TDetailsID");
                            if(Control.selectTDetail(TransactionDetail.Tipe.IKSTransaction, setTDetailIds).paymentMethod == TransactionDetail.PaymentMethod.CASH){
                                data[j][3] = Control.selectTDetail(TransactionDetail.Tipe.IKSTransaction, setTDetailIds).amount;
                            }
                            if(Control.selectTDetail(TransactionDetail.Tipe.IKSTransaction, setTDetailIds).paymentMethod == TransactionDetail.PaymentMethod.IDD){
                                data[j][4] = Control.selectTDetail(TransactionDetail.Tipe.IKSTransaction, setTDetailIds).amount;
                            }
                            if(Control.selectTDetail(TransactionDetail.Tipe.IKSTransaction, setTDetailIds).paymentMethod == TransactionDetail.PaymentMethod.BEASISWA){
                                data[j][5] = Control.selectTDetail(TransactionDetail.Tipe.IKSTransaction, setTDetailIds).amount;
                            }
                            if(Control.selectTDetail(TransactionDetail.Tipe.IKSTransaction, setTDetailIds).paymentMethod == TransactionDetail.PaymentMethod.BEASISWA_COST){
                                data[j][6] = Control.selectTDetail(TransactionDetail.Tipe.IKSTransaction, setTDetailIds).amount;
                            }
                        }
                        if(data[j][3] == null){
                        data[j][3] = 0f;
                        }
                        if(data[j][4] == null){
                            data[j][4] = 0f;
                        }
                        if(data[j][5] == null){
                            data[j][5] = 0f;
                        }
                        if(data[j][6] == null){
                            data[j][6] = 0f;
                        }
                    }else{
                        data[j][3]=0f;
                        data[j][4]=0f;
                        data[j][5]=0f;
                        data[j][6]=0f;
                    }
                }
                
                iksFromDB.entries.add(entry.getValue().entries.get(j));
                //canEdit[j] = (entry.getValue().entries.get(j).transactDetailIDs.size() > 0);
                
                for(Long id : entry.getValue().entries.get(j).transactDetailIDs){
                    canEdit[j] = Control.selectTDetail(TransactionDetail.Tipe.IKSTransaction, id).settled;
                }
                
                
            }
            iksFromDB.id = entry.getValue().id;
            iksFromDB.noInduk = entry.getValue().noInduk;
            iksFromDB.chargedLevel = entry.getValue().chargedLevel;
            i++;
        }
        TableModel tm = new DefaultTableModel(data, columnNames){
            boolean[] chooseEdit = new boolean[]{false,false,true,true,true,true,true};
            
           @Override
            public boolean isCellEditable(int row, int column) {
                //all cells false for editable
                if(!itfs.jDialogTransactionSummary.isVisible()){
                    if((Boolean)getValueAt(row, 2)){
                    //if((Float)getValueAt(row,1) == 0f){
                        if((column == 0 || column ==1)){
                            return column == 2;
                        //return false;
                        }
                        return !canEdit[row];
                    }
                    if((column == 0 && column ==1)|| column == 2){
                            //return column == 2;
                        return chooseEdit[column];
                    }

                    return false;
               }else{
                    return false;
                }
            }
            public Class getColumnClass(int c) {
                return getValueAt(0, c).getClass();
            }
       };
       
       return tm;
       }else{
           TableModel tm = new DefaultTableModel(data, columnNames);
           JOptionPane.showMessageDialog(rootPane, "IKS Belum Di Setting!\r\n");
           this.dispose();
           return null;
       }
       
       
    }
    public TableModel buildIKSSubmitTableModel(Profil profil, int tahun) throws SQLException, KasirException {
       String columnNames[] = {"IKS", "Biaya IKS", "Check Box", "Tunai", "Iuran Dibayar Dimuka", "Beasiswa", "Beasiswa Yayasan"};
       Object[][] data = new Object[1][7];
       
       final boolean[] canEdit = new boolean [1];
         
        for(int i = 0 ; i < iksCurrent.entries.size(); i++){
                data[i][0]= namaBulan[i];//entry.getValue().entries.get(j).period;
                data[i][1]= iksFromDB.entries.get(i).amount; // ANEH NIH MASA BEGINI, DI KALI DUA SIH?
                if(iksCurrent.entries.get(i) != null){
//                    if(jTableIKS != null){
//                        data[j][2]=jTableIKS.getValueAt(j,2);
//                    }else{
                        data[i][2] = new Boolean(true);
//                        data[i][3] = iksFromDB.entries.get(i).amount-(iDDAmounts.get(i)+beasiswaAmounts.get(i)+beasiswaCostAmounts.get(i));
                        data[i][3] = iKSAmounts.get(i);
                        data[i][4] = iDDAmounts.get(i);
                        data[i][5] = beasiswaAmounts.get(i);
                        data[i][6] = beasiswaCostAmounts.get(i);
//                    }
                }else{
//                    if(jTableIKS !=null){
//                        data[j][2]=jTableIKS.getValueAt(j,2);
//                    }else{
                        data[i][2] = new Boolean(false);
//                        data[i][3] = iksFromDB.entries.get(i).amount-(iDDAmounts.get(i)+beasiswaAmounts.get(i)+beasiswaCostAmounts.get(i));
                        data[i][3] = iKSAmounts.get(i);
                        data[i][4] = iDDAmounts.get(i);
                        data[i][5] = beasiswaAmounts.get(i);
                        data[i][6] = beasiswaCostAmounts.get(i);
//                    }
                }
       }
       
       TableModel tm = new DefaultTableModel(data, columnNames){
            boolean[] chooseEdit = new boolean[]{false,false,true};
            
           @Override
            public boolean isCellEditable(int row, int column) {
                //all cells false for editable
                if(!itfs.jDialogTransactionSummary.isVisible()){
                    if((Boolean)getValueAt(row, 2)){
                        if((column == 0 || column ==1)){
                            return column == 2;
                        //return false;
                        }
                        return !canEdit[row];
                    }
                    if((column == 0 && column ==1)|| column == 2){
                            //return column == 2;
                        return chooseEdit[column];
                    }

                    return false;
               }else{
                    return false;
                }
            }
            public Class getColumnClass(int c) {
                return getValueAt(0, c).getClass();
            }
       };
       
       return tm;
    }
    
private ComboBoxModel buildIKStahunComboBoxModel(Profil profil) throws SQLException, KasirException {
       Set<IKS> iksFilters = new HashSet<>();
       ArrayList<Entry> entries = new ArrayList();
       iksFilters.add(new IKS(profil.noInduk, null, entries));
       Map<Long, IKS> searchResultMap = Control.exactFilterSelectIurans(Iuran.Tipe.IKS, iksFilters);
       this.tahunIKS = new ArrayList<>();
       List<String> tahunAjaran = new ArrayList<>();
       Object[][] data = new Object[searchResultMap.size()][2];
       int i = 0;
       if(searchResultMap.size() > 0){
        for(Map.Entry<Long, IKS> entry: searchResultMap.entrySet()){
            data[i][0]= entry.getValue().entries.get(0);
            data[i][1]= entry.getValue().entries.get(0).amount;
            this.tahunIKS.add(entry.getValue().chargedLevel.tahun);
            tahunAjaran.add(String.valueOf(entry.getValue().chargedLevel.tahun).concat(" - ").concat(String.valueOf(entry.getValue().chargedLevel.tahun+1)));
            i++;
        }
       }
       calculateUnpaidIKS(profil, tahunIKS);
       //== bikin tunggakan beans ===
       
       
       //== end bikin tunggakan beans ===
       
       tahunComboBoxModel = new DefaultComboBoxModel(tahunAjaran.toArray());
       return tahunComboBoxModel;
    }

private float calculateUnpaidIKS(Profil profil, List<Integer> tahuns) throws SQLException, KasirException {
       Set<IKS> iksFilters = new HashSet<>();
       float retVal = 0;
       ArrayList<Entry> entries = new ArrayList<>();
       iksFilters.clear();
       int targetMonth = Calendar.getInstance().get(Calendar.MONTH);
       int targetYear = Calendar.getInstance().get(Calendar.YEAR);
       if(targetMonth>5){//JULY - DECEMBER
           targetMonth = targetMonth - 5;
       }else{//JANUARY - JUNE
           targetMonth = targetMonth + 7;
           targetYear = targetYear - 1;
       }
       System.out.println("Month INT: "+Calendar.getInstance().get(Calendar.MONTH));
       for(int i = 0; i< tahuns.size(); i++){
           iksFilters.add(new IKS(profil.noInduk, new Level(null,null,null,tahuns.get(i)), entries));
           
        }
       Map<Long, IKS> searchResultMap = Control.exactFilterSelectIurans(Iuran.Tipe.IKS, iksFilters);
        if(searchResultMap.size() > 0){
            for(Map.Entry<Long, IKS> entry: searchResultMap.entrySet()){
                for(int j =0 ; j< entry.getValue().entries.size(); j++){
                    if((entry.getValue().entries.get(0).transactDetailIDs.isEmpty()) 
                            && ((entry.getValue().chargedLevel.tahun < targetYear)? true:(entry.getValue().entries.get(0).period <= targetMonth))){
                        retVal += entry.getValue().entries.get(0).amount;
                    }else if(entry.getValue().entries.get(0).transactDetailIDs.size() > 0){
                        Float temp = 0f;
                        for(Long l : entry.getValue().entries.get(0).transactDetailIDs){
                            temp += Control.selectTDetail(TransactionDetail.Tipe.IKSTransaction, l).amount;
                        }
                        if(temp < entry.getValue().entries.get(0).amount){
                            retVal += entry.getValue().entries.get(0).amount-temp;
                        } 
                    }
                }
            }
        }
       unpaidIKS = retVal;
       return retVal;
    }
    
    public ArrayList<TunggakanBean> calculateUnpaidIKSs(ArrayList<Profil> profils, List<Integer> tahuns) throws SQLException, KasirException {
       Set<IKS> iksFilters = new HashSet<>();
       ArrayList<TunggakanBean> retVals = new ArrayList<>();
       float retVal = 0;
       ArrayList<Entry> entries = new ArrayList<>();
       iksFilters.clear();
       int targetMonth = Calendar.getInstance().get(Calendar.MONTH);
       int targetYear = Calendar.getInstance().get(Calendar.YEAR);
       if(targetMonth>5){//JULY - DECEMBER
           targetMonth = targetMonth - 5;
       }else{//JANUARY - JUNE
           targetMonth = targetMonth + 7;
           targetYear = targetYear - 1;
       }
       System.out.println("Month INT: "+Calendar.getInstance().get(Calendar.MONTH));
       ArrayList<String> noInduks = new ArrayList<>();
       for(int i = 0; i< profils.size() ; i++){
           noInduks.add(profils.get(i).noInduk);
            for(int j = 0; j< tahuns.size(); j++){
                iksFilters.add(new IKS(profils.get(i).noInduk, new Level(null,null,null,tahuns.get(j)), entries));

            }
       }
       List<IKS> test = Control.selectIurans(Iuran.Tipe.IKS, IKS.noIndukColName, false, noInduks.toArray(new String[0]));
       
       for(int i = 0 ; i< test.size(); i++){
           TunggakanBean tb = new TunggakanBean();
           for(int j = 0 ; j < test.get(i).entries.size(); j++){
               if(j==0) retVal=0;
               Float totalAmountIKSTDetails = 0f;
               for(Long l : test.get(i).entries.get(0).transactDetailIDs){
                   totalAmountIKSTDetails += Control.selectTDetail(TransactionDetail.Tipe.IKSTransaction, l).amount;
               }
               if((totalAmountIKSTDetails < test.get(i).entries.get(0).amount)
                   && ((test.get(i).chargedLevel.tahun < targetYear? true: (test.get(i).entries.get(0).period <= targetMonth)))){
                    
                            
                            retVal += test.get(i).entries.get(0).amount-totalAmountIKSTDetails;
                            tunggakanIKSString = tunggakanIKSString.concat("IKS Semester ");
                            tunggakanIKSString = tunggakanIKSString.concat(getMonthName(test.get(i).entries.get(0).period));
                            tunggakanIKSString = tunggakanIKSString.concat(" "+String.valueOf(test.get(i).chargedLevel.tahun)+"/"+String.valueOf(1+test.get(i).chargedLevel.tahun));
                            tunggakanIKSString = tunggakanIKSString.concat("\r\n");
                            
                            tunggakanIKSEachAmountString = tunggakanIKSEachAmountString.concat("Rp. ");
                            tunggakanIKSEachAmountString = tunggakanIKSEachAmountString.concat(String.valueOf(Math.round(test.get(i).entries.get(0).amount-totalAmountIKSTDetails)));
                            tunggakanIKSEachAmountString = tunggakanIKSEachAmountString.concat("\r\n");
               }
               
                
               
               
           }
           tb.setProfil(profils.get(i));
           tb.setTunggakanIKS(retVal);
           retVals.add(tb);
           System.out.println(test.get(i).noInduk);
       }
       unpaidIKS = retVal;
       return retVals;
    }
   
    private String getMonthName(int p){
        String ret;
        switch(p){
            case 1: ret = "IKS";
                break;
            default: ret = "Invalid";
                break;
        }
        return ret;
        
    }

    public boolean isIKSEnough(Set<Long> transactDetailIDs, float amountIKSinTable) throws SQLException, KasirException {
        Float totalAmountTDetail = 0f;
        for(Long l : transactDetailIDs){
            totalAmountTDetail += Control.selectTDetail(TransactionDetail.Tipe.IKSTransaction, l).amount;
        }
        if(totalAmountTDetail < amountIKSinTable){
            return false;
        }else{
            return true;
        }
    }
    
    
    public float calculatePaidIKS(Set<Long> transactDetailIDs) throws SQLException, KasirException{
        Float retVal = 0f;
        for(Long l: transactDetailIDs){
            retVal += Control.selectTDetail(TransactionDetail.Tipe.IKSTransaction, l).amount;
        }
        return retVal;
    }
    
}
