/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import iuran.Iuran;
import iuran.Almamater;
import iuran.AlmamaterTransactionDetail;
import iuran.TransactionDetail;
import java.awt.Component;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumnModel;
import javax.swing.table.TableModel;
import kasir.Control;
import org.openide.util.Exceptions;
import pelajar.Profil;
import sak.Kalender;
import sak.KasirException;

/**
 *
 * @author Master
 */
public class InputTransactionAlmamater extends javax.swing.JFrame {
    Profil profil;
    private Almamater almamater;
    private List<Almamater> almamaterS;
    private List<Almamater> almamaterSToDB;
    private float unpaidAlmamater = 0f;
    private InputTransactionFrameSeparated itfs;
    private TableModel tableModelAlmamater;
    /**
     * Creates new form InputTransactionAlmamater
     */
    public InputTransactionAlmamater(Profil profil, InputTransactionFrameSeparated itfs) {
        this.profil = profil;
        this.itfs = itfs;
        try{
            tableModelAlmamater = buildAlmamaterTableModel(profil);
        }catch(SQLException ex){
            ex.printStackTrace();
        }catch(KasirException ex){
            ex.printStackTrace();
        }
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelSeragam = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableAlmamater = new javax.swing.JTable();
        jLabel19 = new javax.swing.JLabel();
        jUnpaidAlmamater = new javax.swing.JTextField();
        jButtonBayarAlmamater = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jPanelSeragam.setMinimumSize(new java.awt.Dimension(440, 550));
        jPanelSeragam.setPreferredSize(new java.awt.Dimension(480, 302));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel10.setText(org.openide.util.NbBundle.getMessage(InputTransactionAlmamater.class, "InputTransactionAlmamater.jLabel10.text_1")); // NOI18N

        try{
            tableModelAlmamater = buildAlmamaterTableModel(profil);
        }catch(Exception e){
            e.printStackTrace();
        }
        jTableAlmamater.setModel(tableModelAlmamater);
        jTableAlmamater.getColumn("Detail / History").setCellRenderer(new SeragamButtonRenderer());
        jTableAlmamater.getColumn("Detail / History").setCellEditor(
            new SeragamButtonEditor(new JCheckBox()));
        jTableAlmamater.removeColumn(jTableAlmamater.getColumn("IuranID"));
        jTableAlmamater.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jTableAlmamaterPropertyChange(evt);
            }
        });
        jScrollPane2.setViewportView(jTableAlmamater);

        jLabel19.setText(org.openide.util.NbBundle.getMessage(InputTransactionAlmamater.class, "InputTransactionAlmamater.jLabel19.text_1")); // NOI18N

        jUnpaidAlmamater.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jUnpaidAlmamater.setText(String.valueOf(unpaidAlmamater));
        jUnpaidAlmamater.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jUnpaidAlmamater.setEnabled(false);

        jButtonBayarAlmamater.setText(org.openide.util.NbBundle.getMessage(InputTransactionAlmamater.class, "InputTransactionAlmamater.jButtonBayarAlmamater.text")); // NOI18N
        jButtonBayarAlmamater.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBayarAlmamaterActionPerformed(evt);
            }
        });

        jLabel1.setText(profil.biodata.nama);

        javax.swing.GroupLayout jPanelSeragamLayout = new javax.swing.GroupLayout(jPanelSeragam);
        jPanelSeragam.setLayout(jPanelSeragamLayout);
        jPanelSeragamLayout.setHorizontalGroup(
            jPanelSeragamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSeragamLayout.createSequentialGroup()
                .addGroup(jPanelSeragamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 609, Short.MAX_VALUE)
                    .addGroup(jPanelSeragamLayout.createSequentialGroup()
                        .addGroup(jPanelSeragamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelSeragamLayout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(104, 104, 104)
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jUnpaidAlmamater, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelSeragamLayout.createSequentialGroup()
                                .addGap(285, 285, 285)
                                .addComponent(jButtonBayarAlmamater))
                            .addComponent(jLabel1))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelSeragamLayout.setVerticalGroup(
            jPanelSeragamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSeragamLayout.createSequentialGroup()
                .addGroup(jPanelSeragamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel19)
                    .addComponent(jUnpaidAlmamater, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonBayarAlmamater)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelSeragam, javax.swing.GroupLayout.DEFAULT_SIZE, 619, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelSeragam, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTableAlmamaterPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jTableAlmamaterPropertyChange
        // TODO add your handling code here:
        almamaterSToDB = new ArrayList<>();
        if (jTableAlmamater.getRowCount() > 0) {
            for (int i = 0; i < jTableAlmamater.getRowCount(); i++) {
//                if((Boolean)jTableAlmamater.getValueAt(i,3) && (almamaterS.get(i).transactDetailIDs.size() == 0)){
                if(jTableAlmamater.getModel().getValueAt(i,5) != null){
                    if((Float)jTableAlmamater.getModel().getValueAt(i,5) > 0){
                        almamaterS.get(i).amount = (Float)jTableAlmamater.getModel().getValueAt(i,5);
                        almamaterSToDB.add(almamaterS.get(i));
                    }
                }
                //                    try {
                //almamater = Control.selectIuran(Iuran.Tipe.Almamater, Almamater.noIndukColName, false , profil.noInduk);
                //almamaterS.remove(i);
//                    } catch (SQLException ex) {
//                        Exceptions.printStackTrace(ex);
//                    } catch (KasirException ex) {
//                        Exceptions.printStackTrace(ex);
//                    }
//                }
            }
        }
    }//GEN-LAST:event_jTableAlmamaterPropertyChange

    private void jButtonBayarAlmamaterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBayarAlmamaterActionPerformed
        // TODO add your handling code here:
        float almamaterAmountTemp = 0f;

        for (int i = 0; i < almamaterSToDB.size(); i++) {
            if (almamaterSToDB.get(i) != null) {

                //almamaterAmountTemp = almamaterAmountTemp + (Float) jTableAlmamater.getModel().getValueAt(i, 3);
                almamaterAmountTemp = almamaterAmountTemp + almamaterSToDB.get(i).amount;

            }
        }
        itfs.jTextFieldAlmamaterAmountSimple.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0"))));
        itfs.jTextFieldAlmamaterAmountSimple.setValue(almamaterAmountTemp);
        try {
            itfs.jTextFieldAlmamaterAmountSimple.commitEdit();
        } catch (ParseException ex) {
            Exceptions.printStackTrace(ex);
        }
        itfs.almamaterSToDB = almamaterSToDB;
        itfs.almamaterS = almamaterS;
        this.setVisible(false);
    }//GEN-LAST:event_jButtonBayarAlmamaterActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public TableModel buildAlmamaterTableModel(Profil profil) throws SQLException, KasirException{
       String columnNames[] = {"Kelas","Detail / History", "Transaksi Almamater", "Biaya", "Sisa", "Pembayaran", "IuranID"};
       Set<Almamater> almamaterFilters = new HashSet<>();
       almamaterFilters.add(new Almamater(profil.noInduk,null, null, 0F, null));
       Map<Long, Almamater> searchResultMap = new HashMap<>();
       searchResultMap = Control.exactFilterSelectIurans(Iuran.Tipe.Almamater, almamaterFilters);
       
       Set<Long> transactDetailIDsTemp = new HashSet<Long>();
       int j = 0;
       almamaterS = new ArrayList<>();
       ArrayList<Long> almamaterSPaid = new ArrayList<Long>();
       ArrayList<String> almamaterSTransactionDate = new ArrayList<String>();
       ArrayList<AlmamaterTransactionDetail> stds = new ArrayList<AlmamaterTransactionDetail>();
       if(searchResultMap.size() > 0){
        for(Map.Entry<Long, Almamater> entry: searchResultMap.entrySet()){
            transactDetailIDsTemp.clear();
            transactDetailIDsTemp = entry.getValue().transactDetailIDs;
            long paidAlmamater = 0l;
            String lastTransactionDate = "";
            SimpleDateFormat formatIndo = new SimpleDateFormat("dd-MM-yyyy");
            AlmamaterTransactionDetail std = new AlmamaterTransactionDetail();
            stds.clear();
            for(Long l : transactDetailIDsTemp){
                std = Control.selectTDetail(TransactionDetail.Tipe.AlmamaterTransaction, l);
                paidAlmamater += std.amount;
                lastTransactionDate = formatIndo.format(std.lastUpdateDate.toDate());
                almamaterSTransactionDate.add(lastTransactionDate);
                stds.add(std);
            }
            
            if(entry.getValue().amount > paidAlmamater){
                almamaterS.add(entry.getValue());
                almamaterSPaid.add(paidAlmamater);
            }
            j++;
        }
       }
       Object[][] data = new Object[almamaterS.size()][columnNames.length];
       for(int i =0; i < almamaterS.size(); i++){
            
            data[i][0]= almamaterS.get(i).chargedLevel;
            data[i][1]= "Detail";
            data[i][2]= almamaterS.get(i).transactName;
            data[i][3]= almamaterS.get(i).amount;
            data[i][4]= almamaterS.get(i).amount-almamaterSPaid.get(i);
            data[i][5]= 0f;
            data[i][6]= almamaterS.get(i).id;
//            if(almamaterS.get(i).transactDetailIDs.size()>0){
//                data[i][3] = new Boolean(true);
//            }else{
//                data[i][3] = new Boolean(false);
//            }
       }
       itfs.unpaidAlmamater = calculateUnpaidAlmamater(profil);
       if(data.length > 0){
       TableModel tm = new DefaultTableModel(data, columnNames){
           @Override
            public boolean isCellEditable(int row, int column) {
                //all cells false for editable
               if(itfs.jDialogTransactionSummary.isVisible()){
                    return false;
               }else{
                    return true;
               }
            }
            public Class getColumnClass(int c) {
                return getValueAt(0, c).getClass();
            }
       };
       
       return tm;
       }else{
           TableModel tm = new DefaultTableModel(columnNames, columnNames.length);
           return tm;
       }
   }
    
    public TableModel buildAlmamaterSubmitTableModel(Profil profil, List<Almamater> stdb) throws SQLException, KasirException{
       String columnNames[] = {"Kelas","Detail / History", "Transaksi Almamater", "Biaya", "Sisa", "Pembayaran", "IuranID"};
       
       Set<Almamater> almamaterFilters = new HashSet<>();
       Set<Long> almamaterIDs = new HashSet<>();
       for(int i = 0 ; i < stdb.size(); i++){
           almamaterIDs.add(stdb.get(i).id);
       }
       almamaterFilters.addAll(stdb);
       Map<Long, Almamater> searchResultMap = new HashMap<>();
       //searchResultMap = Control.exactFilterSelectIurans(Iuran.Tipe.Almamater, almamaterFilters);
       searchResultMap = Control.selectIurans(Iuran.Tipe.Almamater, almamaterIDs);
       Set<Long> transactDetailIDsTemp = new HashSet<Long>();
       int j = 0;
       long paidAlmamater = 0l;
       almamaterS = new ArrayList<>();  
       ArrayList<Long> almamaterSPaid = new ArrayList<Long>();
       ArrayList<Kalender> almamaterSTransactionDate = new ArrayList<Kalender>();
       if(searchResultMap.size() > 0){
        for(Map.Entry<Long, Almamater> entry: searchResultMap.entrySet()){
            transactDetailIDsTemp.clear();
            transactDetailIDsTemp = entry.getValue().transactDetailIDs;
            paidAlmamater = 0l;
            Kalender lastTransactionDate = new Kalender();
            AlmamaterTransactionDetail std = new AlmamaterTransactionDetail();
            for(Long l : transactDetailIDsTemp){
                std = Control.selectTDetail(TransactionDetail.Tipe.AlmamaterTransaction, l);
                paidAlmamater += std.amount;
                lastTransactionDate = std.lastUpdateDate;
                almamaterSTransactionDate.add(lastTransactionDate);
            }
            if(transactDetailIDsTemp.isEmpty()){
                almamaterSTransactionDate.add(new Kalender());
            }
            
            if(entry.getValue().amount > paidAlmamater){
                almamaterS.add(entry.getValue());
                almamaterSPaid.add(paidAlmamater);
                
            }
            j++;
        }
       }
       Object[][] data = new Object[almamaterS.size()][columnNames.length];
       for(int i =0; i < almamaterS.size(); i++){
            data[i][0]= almamaterS.get(i).chargedLevel;
            data[i][1]= almamaterSTransactionDate.get(i);
            data[i][2]= almamaterS.get(i).transactName;
            data[i][3] = almamaterS.get(i).amount;
            data[i][4] = almamaterS.get(i).amount - stdb.get(i).amount - almamaterSPaid.get(i);
            data[i][5] = stdb.get(i).amount;
            data[i][6] = almamaterS.get(i).id;
            itfs.unpaidAlmamater = itfs.unpaidAlmamater - stdb.get(i).amount;
       }
       
      
       if(data.length > 0){
       TableModel tm = new DefaultTableModel(data, columnNames){
           @Override
            public boolean isCellEditable(int row, int column) {
                //all cells false for editable
               if(itfs.jDialogTransactionSummary.isVisible()){
                    return false;
               }else{
                    return true;
               }
            }
            public Class getColumnClass(int c) {
                return getValueAt(0, c).getClass();
            }
       };
       
       return tm;
       }else{
           TableModel tm = new DefaultTableModel(columnNames, columnNames.length);
           return tm;
       }
   }
    
    private float calculateUnpaidAlmamater(Profil profil) throws SQLException, KasirException {
       float retVal = 0;
       Set<Almamater> almamaterFilters = new HashSet<>();
       almamaterFilters.add(new Almamater(profil.noInduk,null, null, 0F, null));
       Map<Long, Almamater> searchResultMap = new HashMap<>();
       Set<Long> transactDetailIDsTemp = new HashSet<Long>();
       searchResultMap = Control.exactFilterSelectIurans(Iuran.Tipe.Almamater, almamaterFilters);
       almamaterS = new ArrayList<>();
       
       if(searchResultMap.size() > 0){
        for(Map.Entry<Long, Almamater> entry: searchResultMap.entrySet()){
            transactDetailIDsTemp.clear();
            transactDetailIDsTemp = entry.getValue().transactDetailIDs;
            long paidAlmamater = 0l;
            for(Long l : transactDetailIDsTemp){
                paidAlmamater += Control.selectTDetail(TransactionDetail.Tipe.AlmamaterTransaction, l).amount;
            }
            
            if(entry.getValue().amount > paidAlmamater){
                almamaterS.add(entry.getValue());
            }
            retVal += entry.getValue().amount - paidAlmamater;
        }
       }
       unpaidAlmamater = retVal;
       System.out.println("unpaid Almamater");
       System.out.println(unpaidAlmamater);
       return retVal;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBayarAlmamater;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JPanel jPanelSeragam;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableAlmamater;
    private javax.swing.JTextField jUnpaidAlmamater;
    // End of variables declaration//GEN-END:variables
}

/**
 * @version 1.0 11/09/98
 */

class AlmamaterButtonRenderer extends JButton implements TableCellRenderer {

  public AlmamaterButtonRenderer() {
    setOpaque(true);
  }

  public Component getTableCellRendererComponent(JTable table, Object value,
      boolean isSelected, boolean hasFocus, int row, int column) {
    if (isSelected) {
      setForeground(table.getSelectionForeground());
      setBackground(table.getSelectionBackground());
    } else {
      setForeground(table.getForeground());
      setBackground(UIManager.getColor("Button.background"));
    }
    setText((value == null) ? "" : value.toString());
    return this;
  }
}

/**
 * @version 1.0 11/09/98
 */

class AlmamaterButtonEditor extends DefaultCellEditor {
  protected JButton button;

  private String label;
  private String detail;
  private boolean isPushed;
  private JTable detailTable;
  private JScrollPane scrollPane;
  private ArrayList<AlmamaterTransactionDetail> stds;
  public AlmamaterButtonEditor(JCheckBox checkBox) {
    super(checkBox);
    button = new JButton();
    button.setOpaque(true);
    button.addActionListener(new ActionListener() {
      public void actionPerformed(ActionEvent e) {
        fireEditingStopped();
      }
    });
  }

  public Component getTableCellEditorComponent(JTable table, Object value,
      boolean isSelected, int row, int column) {
    if (isSelected) {
      button.setForeground(table.getSelectionForeground());
      button.setBackground(table.getSelectionBackground());
    } else {
      button.setForeground(table.getForeground());
      button.setBackground(table.getBackground());
    }
    SimpleDateFormat formatIndo = new SimpleDateFormat("dd-MM-yyyy hh:mm:ss");
    Set<Long> transactDetailIDsTemp = new HashSet<Long>();
    Almamater s;
    Long almamaterID = (Long)table.getModel().getValueAt(row, 6);
    try {
        s = Control.selectIuran(Iuran.Tipe.Almamater, almamaterID);
        transactDetailIDsTemp = s.transactDetailIDs;
    } catch (SQLException ex) {
        Exceptions.printStackTrace(ex);
    } catch (KasirException ex) {
        Exceptions.printStackTrace(ex);
    }
    AlmamaterTransactionDetail std = new AlmamaterTransactionDetail();
    detail = "";
    
    String columnNames[] = {"No", "Tanggal", "Pembayaran"};
    Object[][] data = new Object[transactDetailIDsTemp.size()][columnNames.length];
    int i = 0;
    for(Long l : transactDetailIDsTemp){
            try {
                std = Control.selectTDetail(TransactionDetail.Tipe.AlmamaterTransaction, l);
            } catch (SQLException ex) {
                Exceptions.printStackTrace(ex);
            } catch (KasirException ex) {
                Exceptions.printStackTrace(ex);
            }
            
            detail += String.valueOf(i);
            detail += ". Rp ";
            detail += String.valueOf(std.amount);
            detail += "\t";
            detail += formatIndo.format(std.lastUpdateDate.toDate());
            detail += "\r\n";
            
            data[i][0] = i+1;
            data[i][1] = formatIndo.format(std.lastUpdateDate.toDate());
            data[i][2] = "Rp ".concat(String.valueOf((Float)std.amount));
            i++;
    }
    
    TableModel tm = new DefaultTableModel(data, columnNames){
           @Override
            public boolean isCellEditable(int row, int column) {
                //all cells false for editable
               return false;
            }
            public Class getColumnClass(int c) {
                return getValueAt(0, c).getClass();
            }
       };
    
    detailTable = new JTable(tm){
        public Class getColumnClass(int c){
            return getValueAt(0, c).getClass();
        }
    };
    
    
    scrollPane = new JScrollPane(detailTable);
    
    
    label = (value == null) ? "" : value.toString();
    
    button.setText(label);
    isPushed = true;
    return button;
  }

  public Object getCellEditorValue() {
    if (isPushed) {
      // 
      // 
      JOptionPane.showMessageDialog(button, scrollPane, "Almamater", JOptionPane.INFORMATION_MESSAGE);
      
      // System.out.println(label + ": Ouch!");
    }
    isPushed = false;
    return new String(label);
  }

  public boolean stopCellEditing() {
    isPushed = false;
    return super.stopCellEditing();
  }

  protected void fireEditingStopped() {
    super.fireEditingStopped();
  }
}
