/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import iuran.*;
import iuran.Iuran.Tipe;
import java.awt.Container;
import java.sql.SQLException;
import java.util.*;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellEditor;
import javax.swing.table.TableModel;
import kasir.Clerk;
import kasir.Control;
import pelajar.Profil;
import org.netbeans.validation.api.Validator;
import org.netbeans.validation.api.ValidatorUtils;
import org.netbeans.validation.api.ui.swing.ValidationPanel;
import org.netbeans.validation.api.builtin.stringvalidation.StringValidators;
import org.openide.util.Exceptions;
import pelajar.Level;
import sak.KasirException;
/**
 *
 * @author Master
 */
public class InputBeasiswaFrame extends javax.swing.JFrame {
    private Clerk clerk;
    private Profil profil;
    private final ValidationPanel validationPanel = new ValidationPanel();
    private DefaultTableModel dtm;
    private TableCellEditor tableCellEditor;
    private ArrayList<IDD> iddS;
    private ArrayList<Beasiswa> beasiswaS;
    private ArrayList<BeasiswaCost> beasiswaCostS;
    private TableModel tableModelIDD;
    private IDD idd;
    private Beasiswa beasiswa;
    private BeasiswaCost beasiswaCost;
    private Level level;
    /**
     * Creates new form InputIuranFrame
     */
    public InputBeasiswaFrame() {
        initComponents();
    }
    
    public InputBeasiswaFrame(Clerk clerk, Profil profil){
        this.clerk = clerk;
        this.profil = profil;
        this.level = profil.currentLevel;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelMain = new javax.swing.JPanel();
        jPanelProfil1 = new javax.swing.JPanel();
        jLableProfilTitle1 = new javax.swing.JLabel();
        jLabelNama1 = new javax.swing.JLabel();
        jLabelLevel2Level4 = new javax.swing.JLabel();
        jLabelNoInduk1 = new javax.swing.JLabel();
        jLabelLevel2 = new javax.swing.JLabel();
        jTextFieldNama1 = new javax.swing.JTextField();
        jTextFieldNomorInduk1 = new javax.swing.JTextField();
        jTextFieldLevel2Level4 = new javax.swing.JTextField();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        DefaultComboBoxModel level1ComboBoxModel = new DefaultComboBoxModel(level.level1.values());
        DefaultComboBoxModel level2ComboBoxModel = new DefaultComboBoxModel(level.level2.values());
        DefaultComboBoxModel level3ComboBoxModel = new DefaultComboBoxModel(level.level3.values());
        jPanelIDD = new javax.swing.JPanel();
        jLabelIDDTitle = new javax.swing.JLabel();
        jLabelAmount3 = new javax.swing.JLabel();
        jTextFieldIDDAmount = new javax.swing.JTextField();
        jLabelIDDChargedLevel = new javax.swing.JLabel();
        jComboBoxIIDDLevel = new javax.swing.JComboBox();
        jLabelIDDChargedLevel2Level = new javax.swing.JLabel();
        jComboBoxIDDLevel2 = new javax.swing.JComboBox();
        jComboBoxIDDLevel3 = new javax.swing.JComboBox();
        jLabelNote2 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextAreaIDDNote = new javax.swing.JTextArea();
        jLabelAmount4 = new javax.swing.JLabel();
        jTextFieldIDDTransactionName = new javax.swing.JTextField();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTableIDD = new javax.swing.JTable();
        jPanelBeasiswa = new javax.swing.JPanel();
        jLabelIDDTitle1 = new javax.swing.JLabel();
        jLabelAmount7 = new javax.swing.JLabel();
        jTextFieldBeasiswaAmount = new javax.swing.JTextField();
        jLabelIDDChargedLevel1 = new javax.swing.JLabel();
        jComboBoxIBeasiswaLevel1 = new javax.swing.JComboBox();
        jLabelIDDChargedLevel2Level1 = new javax.swing.JLabel();
        jComboBoxBeasiswaLevel2 = new javax.swing.JComboBox();
        jComboBoxBeasiswaLevel3 = new javax.swing.JComboBox();
        jLabelNote4 = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        jTextAreaBeasiswaNote = new javax.swing.JTextArea();
        jLabelAmount8 = new javax.swing.JLabel();
        jTextFieldBeasiswaTransactionName = new javax.swing.JTextField();
        jScrollPane10 = new javax.swing.JScrollPane();
        jTableIDD1 = new javax.swing.JTable();
        jPanelBeasiswaCost = new javax.swing.JPanel();
        jLabelIDDTitle2 = new javax.swing.JLabel();
        jLabelAmount9 = new javax.swing.JLabel();
        jLabelIDDChargedLevel2 = new javax.swing.JLabel();
        jComboBoxIBeasiswaYayasanLevel1 = new javax.swing.JComboBox();
        jLabelIDDChargedLevel2Level2 = new javax.swing.JLabel();
        jComboBoxBeasiswaYayasanLevel2 = new javax.swing.JComboBox();
        jComboBoxBeasiswaYayasanLevel3 = new javax.swing.JComboBox();
        jLabelNote5 = new javax.swing.JLabel();
        jScrollPane11 = new javax.swing.JScrollPane();
        jTextAreaBeasiswaCostNote = new javax.swing.JTextArea();
        jLabelAmount10 = new javax.swing.JLabel();
        jScrollPane12 = new javax.swing.JScrollPane();
        jTableIDD2 = new javax.swing.JTable();
        jTextFieldBeasiswaCostTransactionName = new javax.swing.JTextField();
        jTextFieldBeasiswaCostAmount = new javax.swing.JTextField();
        jPanelButton = new javax.swing.JPanel();
        jButtonSaveAll = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("INPUT IURAN SISWA ".concat(profil.currentLevel.level1.toString()));

        tableModelIDD = new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "IDD", "Jumlah", "Catatan", "CheckBox"
            }
        );

        jLableProfilTitle1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLableProfilTitle1.setText(org.openide.util.NbBundle.getMessage(InputBeasiswaFrame.class, "InputBeasiswaFrame.jLableProfilTitle1.text")); // NOI18N

        jLabelNama1.setText(org.openide.util.NbBundle.getMessage(InputBeasiswaFrame.class, "InputBeasiswaFrame.jLabelNama1.text")); // NOI18N

        jLabelLevel2Level4.setText(org.openide.util.NbBundle.getMessage(InputBeasiswaFrame.class, "InputBeasiswaFrame.jLabelLevel2Level4.text")); // NOI18N

        jLabelNoInduk1.setText(org.openide.util.NbBundle.getMessage(InputBeasiswaFrame.class, "InputBeasiswaFrame.jLabelNoInduk1.text")); // NOI18N

        jLabelLevel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelLevel2.setText(profil.currentLevel.level1.toString());

        jTextFieldNama1.setText(profil.biodata.nama);
        jTextFieldNama1.setFocusable(false);
        jTextFieldNama1.setText(profil.biodata.nama);
        jTextFieldNama1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNama1ActionPerformed(evt);
            }
        });

        jTextFieldNomorInduk1.setText(profil.noInduk);
        jTextFieldNomorInduk1.setFocusable(false);

        jTextFieldLevel2Level4.setText(profil.currentLevel.level2.toString().concat(" "+profil.currentLevel.level3.toString()));
        jTextFieldLevel2Level4.setFocusable(false);

        javax.swing.GroupLayout jPanelProfil1Layout = new javax.swing.GroupLayout(jPanelProfil1);
        jPanelProfil1.setLayout(jPanelProfil1Layout);
        jPanelProfil1Layout.setHorizontalGroup(
            jPanelProfil1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProfil1Layout.createSequentialGroup()
                .addGroup(jPanelProfil1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelProfil1Layout.createSequentialGroup()
                        .addComponent(jLableProfilTitle1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelLevel2))
                    .addGroup(jPanelProfil1Layout.createSequentialGroup()
                        .addGroup(jPanelProfil1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelNama1)
                            .addComponent(jLabelNoInduk1)
                            .addComponent(jLabelLevel2Level4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelProfil1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextFieldNomorInduk1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldNama1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldLevel2Level4, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        jPanelProfil1Layout.setVerticalGroup(
            jPanelProfil1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProfil1Layout.createSequentialGroup()
                .addGroup(jPanelProfil1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLableProfilTitle1)
                    .addComponent(jLabelLevel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelProfil1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNama1)
                    .addComponent(jTextFieldNama1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanelProfil1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNoInduk1)
                    .addComponent(jTextFieldNomorInduk1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelProfil1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelLevel2Level4)
                    .addComponent(jTextFieldLevel2Level4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jTabbedPane1PropertyChange(evt);
            }
        });

        jPanelIDD.setPreferredSize(new java.awt.Dimension(1024, 176));

        jLabelIDDTitle.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelIDDTitle.setText(org.openide.util.NbBundle.getMessage(InputBeasiswaFrame.class, "InputBeasiswaFrame.jLabelIDDTitle.text")); // NOI18N

        jLabelAmount3.setText(org.openide.util.NbBundle.getMessage(InputBeasiswaFrame.class, "InputBeasiswaFrame.jLabelAmount3.text")); // NOI18N

        jTextFieldIDDAmount.setText(org.openide.util.NbBundle.getMessage(InputBeasiswaFrame.class, "InputBeasiswaFrame.jTextFieldIDDAmount.text")); // NOI18N
        jTextFieldIDDAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIDDAmountActionPerformed(evt);
            }
        });
        jTextFieldIDDAmount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldIDDAmountKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldIDDAmountKeyTyped(evt);
            }
        });

        jLabelIDDChargedLevel.setText(org.openide.util.NbBundle.getMessage(InputBeasiswaFrame.class, "InputBeasiswaFrame.jLabelIDDChargedLevel.text")); // NOI18N

        jComboBoxIIDDLevel.setModel(level1ComboBoxModel);
        jComboBoxIIDDLevel.setSelectedItem(profil.currentLevel.level1);
        jComboBoxIIDDLevel.setEnabled(false);

        jLabelIDDChargedLevel2Level.setText(org.openide.util.NbBundle.getMessage(InputBeasiswaFrame.class, "InputBeasiswaFrame.jLabelIDDChargedLevel2Level.text")); // NOI18N

        jComboBoxIDDLevel2.setModel(level2ComboBoxModel);

        jComboBoxIDDLevel3.setModel(level3ComboBoxModel);

        jLabelNote2.setText(org.openide.util.NbBundle.getMessage(InputBeasiswaFrame.class, "InputBeasiswaFrame.jLabelNote2.text")); // NOI18N

        jTextAreaIDDNote.setColumns(20);
        jTextAreaIDDNote.setRows(5);
        jScrollPane5.setViewportView(jTextAreaIDDNote);

        jLabelAmount4.setText(org.openide.util.NbBundle.getMessage(InputBeasiswaFrame.class, "InputBeasiswaFrame.jLabelAmount4.text")); // NOI18N

        jTextFieldIDDTransactionName.setText(org.openide.util.NbBundle.getMessage(InputBeasiswaFrame.class, "InputBeasiswaFrame.jTextFieldIDDTransactionName.text")); // NOI18N
        jTextFieldIDDTransactionName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIDDTransactionNameActionPerformed(evt);
            }
        });
        jTextFieldIDDTransactionName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldIDDTransactionNameKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldIDDTransactionNameKeyTyped(evt);
            }
        });

        try{
            tableModelIDD = buildIDDTableModel(profil);
        }catch(Exception e){
            e.printStackTrace();
        }
        jTableIDD.setModel(tableModelIDD);
        jScrollPane6.setViewportView(jTableIDD);

        javax.swing.GroupLayout jPanelIDDLayout = new javax.swing.GroupLayout(jPanelIDD);
        jPanelIDD.setLayout(jPanelIDDLayout);
        jPanelIDDLayout.setHorizontalGroup(
            jPanelIDDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelIDDLayout.createSequentialGroup()
                .addGroup(jPanelIDDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelIDDLayout.createSequentialGroup()
                        .addComponent(jLabelIDDTitle)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanelIDDLayout.createSequentialGroup()
                        .addGroup(jPanelIDDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelAmount3)
                            .addComponent(jLabelIDDChargedLevel)
                            .addComponent(jLabelNote2)
                            .addComponent(jLabelAmount4))
                        .addGap(29, 29, 29)
                        .addGroup(jPanelIDDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldIDDTransactionName)
                            .addComponent(jTextFieldIDDAmount)
                            .addGroup(jPanelIDDLayout.createSequentialGroup()
                                .addComponent(jComboBoxIIDDLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(jLabelIDDChargedLevel2Level)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jComboBoxIDDLevel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBoxIDDLevel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)))
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );
        jPanelIDDLayout.setVerticalGroup(
            jPanelIDDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelIDDLayout.createSequentialGroup()
                .addComponent(jLabelIDDTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelIDDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAmount4)
                    .addComponent(jTextFieldIDDTransactionName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelIDDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAmount3)
                    .addComponent(jTextFieldIDDAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelIDDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelIDDChargedLevel)
                    .addComponent(jComboBoxIIDDLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelIDDChargedLevel2Level)
                    .addComponent(jComboBoxIDDLevel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxIDDLevel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelIDDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelNote2)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                .addContainerGap())
        );

        jComboBoxIDDLevel2.setSelectedItem(profil.currentLevel.level2);
        jComboBoxIDDLevel3.setSelectedItem(profil.currentLevel.level3);

        jTabbedPane1.addTab(org.openide.util.NbBundle.getMessage(InputBeasiswaFrame.class, "InputBeasiswaFrame.jPanelIDD.TabConstraints.tabTitle"), jPanelIDD); // NOI18N

        jPanelBeasiswa.setPreferredSize(new java.awt.Dimension(1024, 176));

        jLabelIDDTitle1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelIDDTitle1.setText(org.openide.util.NbBundle.getMessage(InputBeasiswaFrame.class, "InputBeasiswaFrame.jLabelIDDTitle1.text")); // NOI18N

        jLabelAmount7.setText(org.openide.util.NbBundle.getMessage(InputBeasiswaFrame.class, "InputBeasiswaFrame.jLabelAmount7.text")); // NOI18N

        jTextFieldBeasiswaAmount.setText(org.openide.util.NbBundle.getMessage(InputBeasiswaFrame.class, "InputBeasiswaFrame.jTextFieldBeasiswaAmount.text")); // NOI18N
        jTextFieldBeasiswaAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldBeasiswaAmountActionPerformed(evt);
            }
        });
        jTextFieldBeasiswaAmount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldBeasiswaAmountKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldBeasiswaAmountKeyTyped(evt);
            }
        });

        jLabelIDDChargedLevel1.setText(org.openide.util.NbBundle.getMessage(InputBeasiswaFrame.class, "InputBeasiswaFrame.jLabelIDDChargedLevel1.text")); // NOI18N

        jComboBoxIBeasiswaLevel1.setModel(level1ComboBoxModel);
        jComboBoxIBeasiswaLevel1.setSelectedItem(profil.currentLevel.level1);
        jComboBoxIBeasiswaLevel1.setEnabled(false);

        jLabelIDDChargedLevel2Level1.setText(org.openide.util.NbBundle.getMessage(InputBeasiswaFrame.class, "InputBeasiswaFrame.jLabelIDDChargedLevel2Level1.text")); // NOI18N

        jComboBoxBeasiswaLevel2.setModel(level2ComboBoxModel);

        jComboBoxBeasiswaLevel3.setModel(level3ComboBoxModel);

        jLabelNote4.setText(org.openide.util.NbBundle.getMessage(InputBeasiswaFrame.class, "InputBeasiswaFrame.jLabelNote4.text")); // NOI18N

        jTextAreaBeasiswaNote.setColumns(20);
        jTextAreaBeasiswaNote.setRows(5);
        jScrollPane9.setViewportView(jTextAreaBeasiswaNote);

        jLabelAmount8.setText(org.openide.util.NbBundle.getMessage(InputBeasiswaFrame.class, "InputBeasiswaFrame.jLabelAmount8.text")); // NOI18N

        jTextFieldBeasiswaTransactionName.setText(org.openide.util.NbBundle.getMessage(InputBeasiswaFrame.class, "InputBeasiswaFrame.jTextFieldBeasiswaTransactionName.text")); // NOI18N
        jTextFieldBeasiswaTransactionName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldBeasiswaTransactionNameActionPerformed(evt);
            }
        });
        jTextFieldBeasiswaTransactionName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldBeasiswaTransactionNameKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldBeasiswaTransactionNameKeyTyped(evt);
            }
        });

        try{
            tableModelIDD = buildIDDTableModel(profil);
        }catch(Exception e){
            e.printStackTrace();
        }
        jTableIDD1.setModel(tableModelIDD);
        jScrollPane10.setViewportView(jTableIDD1);

        javax.swing.GroupLayout jPanelBeasiswaLayout = new javax.swing.GroupLayout(jPanelBeasiswa);
        jPanelBeasiswa.setLayout(jPanelBeasiswaLayout);
        jPanelBeasiswaLayout.setHorizontalGroup(
            jPanelBeasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBeasiswaLayout.createSequentialGroup()
                .addGroup(jPanelBeasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelBeasiswaLayout.createSequentialGroup()
                        .addComponent(jLabelIDDTitle1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanelBeasiswaLayout.createSequentialGroup()
                        .addGroup(jPanelBeasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelAmount7)
                            .addComponent(jLabelIDDChargedLevel1)
                            .addComponent(jLabelNote4)
                            .addComponent(jLabelAmount8))
                        .addGap(29, 29, 29)
                        .addGroup(jPanelBeasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldBeasiswaTransactionName)
                            .addComponent(jTextFieldBeasiswaAmount)
                            .addGroup(jPanelBeasiswaLayout.createSequentialGroup()
                                .addComponent(jComboBoxIBeasiswaLevel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(jLabelIDDChargedLevel2Level1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jComboBoxBeasiswaLevel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBoxBeasiswaLevel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane9, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)))
                    .addComponent(jScrollPane10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );
        jPanelBeasiswaLayout.setVerticalGroup(
            jPanelBeasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBeasiswaLayout.createSequentialGroup()
                .addComponent(jLabelIDDTitle1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelBeasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAmount8)
                    .addComponent(jTextFieldBeasiswaTransactionName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelBeasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAmount7)
                    .addComponent(jTextFieldBeasiswaAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelBeasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelIDDChargedLevel1)
                    .addComponent(jComboBoxIBeasiswaLevel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelIDDChargedLevel2Level1)
                    .addComponent(jComboBoxBeasiswaLevel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxBeasiswaLevel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelBeasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelNote4)
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane10, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                .addContainerGap())
        );

        jComboBoxBeasiswaLevel2.setSelectedItem(profil.currentLevel.level2);
        jComboBoxBeasiswaLevel3.setSelectedItem(profil.currentLevel.level3);

        jTabbedPane1.addTab(org.openide.util.NbBundle.getMessage(InputBeasiswaFrame.class, "InputBeasiswaFrame.jPanelBeasiswa.TabConstraints.tabTitle"), jPanelBeasiswa); // NOI18N

        jPanelBeasiswaCost.setPreferredSize(new java.awt.Dimension(1024, 176));

        jLabelIDDTitle2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelIDDTitle2.setText(org.openide.util.NbBundle.getMessage(InputBeasiswaFrame.class, "InputBeasiswaFrame.jLabelIDDTitle2.text")); // NOI18N

        jLabelAmount9.setText(org.openide.util.NbBundle.getMessage(InputBeasiswaFrame.class, "InputBeasiswaFrame.jLabelAmount9.text")); // NOI18N

        jLabelIDDChargedLevel2.setText(org.openide.util.NbBundle.getMessage(InputBeasiswaFrame.class, "InputBeasiswaFrame.jLabelIDDChargedLevel2.text")); // NOI18N

        jComboBoxIBeasiswaYayasanLevel1.setModel(level1ComboBoxModel);
        jComboBoxIBeasiswaYayasanLevel1.setSelectedItem(profil.currentLevel.level1);
        jComboBoxIBeasiswaYayasanLevel1.setEnabled(false);

        jLabelIDDChargedLevel2Level2.setText(org.openide.util.NbBundle.getMessage(InputBeasiswaFrame.class, "InputBeasiswaFrame.jLabelIDDChargedLevel2Level2.text")); // NOI18N

        jComboBoxBeasiswaYayasanLevel2.setModel(level2ComboBoxModel);

        jComboBoxBeasiswaYayasanLevel3.setModel(level3ComboBoxModel);

        jLabelNote5.setText(org.openide.util.NbBundle.getMessage(InputBeasiswaFrame.class, "InputBeasiswaFrame.jLabelNote5.text")); // NOI18N

        jTextAreaBeasiswaCostNote.setColumns(20);
        jTextAreaBeasiswaCostNote.setRows(5);
        jScrollPane11.setViewportView(jTextAreaBeasiswaCostNote);

        jLabelAmount10.setText(org.openide.util.NbBundle.getMessage(InputBeasiswaFrame.class, "InputBeasiswaFrame.jLabelAmount10.text")); // NOI18N

        try{
            tableModelIDD = buildIDDTableModel(profil);
        }catch(Exception e){
            e.printStackTrace();
        }
        jTableIDD2.setModel(tableModelIDD);
        jScrollPane12.setViewportView(jTableIDD2);

        jTextFieldBeasiswaCostTransactionName.setText(org.openide.util.NbBundle.getMessage(InputBeasiswaFrame.class, "InputBeasiswaFrame.jTextFieldBeasiswaCostTransactionName.text")); // NOI18N
        jTextFieldBeasiswaCostTransactionName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldBeasiswaCostTransactionNameActionPerformed(evt);
            }
        });
        jTextFieldBeasiswaCostTransactionName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldBeasiswaCostTransactionNameKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldBeasiswaCostTransactionNameKeyTyped(evt);
            }
        });

        jTextFieldBeasiswaCostAmount.setText(org.openide.util.NbBundle.getMessage(InputBeasiswaFrame.class, "InputBeasiswaFrame.jTextFieldBeasiswaCostAmount.text")); // NOI18N
        jTextFieldBeasiswaCostAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldBeasiswaCostAmountActionPerformed(evt);
            }
        });
        jTextFieldBeasiswaCostAmount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldBeasiswaCostAmountKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldBeasiswaCostAmountKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanelBeasiswaCostLayout = new javax.swing.GroupLayout(jPanelBeasiswaCost);
        jPanelBeasiswaCost.setLayout(jPanelBeasiswaCostLayout);
        jPanelBeasiswaCostLayout.setHorizontalGroup(
            jPanelBeasiswaCostLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(jPanelBeasiswaCostLayout.createSequentialGroup()
                .addGroup(jPanelBeasiswaCostLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelAmount9)
                    .addComponent(jLabelIDDChargedLevel2)
                    .addComponent(jLabelNote5)
                    .addComponent(jLabelAmount10)
                    .addComponent(jLabelIDDTitle2))
                .addGap(29, 29, 29)
                .addGroup(jPanelBeasiswaCostLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelBeasiswaCostLayout.createSequentialGroup()
                        .addComponent(jComboBoxIBeasiswaYayasanLevel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(jLabelIDDChargedLevel2Level2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBoxBeasiswaYayasanLevel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxBeasiswaYayasanLevel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane11, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBeasiswaCostLayout.createSequentialGroup()
                        .addGroup(jPanelBeasiswaCostLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextFieldBeasiswaCostTransactionName, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldBeasiswaCostAmount))
                        .addContainerGap())))
        );
        jPanelBeasiswaCostLayout.setVerticalGroup(
            jPanelBeasiswaCostLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBeasiswaCostLayout.createSequentialGroup()
                .addComponent(jLabelIDDTitle2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelBeasiswaCostLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAmount10)
                    .addComponent(jTextFieldBeasiswaCostTransactionName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelBeasiswaCostLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAmount9)
                    .addComponent(jTextFieldBeasiswaCostAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelBeasiswaCostLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelIDDChargedLevel2)
                    .addComponent(jComboBoxIBeasiswaYayasanLevel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelIDDChargedLevel2Level2)
                    .addComponent(jComboBoxBeasiswaYayasanLevel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxBeasiswaYayasanLevel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelBeasiswaCostLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelNote5)
                    .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane12, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                .addContainerGap())
        );

        jComboBoxBeasiswaYayasanLevel2.setSelectedItem(profil.currentLevel.level2);
        jComboBoxBeasiswaYayasanLevel3.setSelectedItem(profil.currentLevel.level3);

        jTabbedPane1.addTab(org.openide.util.NbBundle.getMessage(InputBeasiswaFrame.class, "InputBeasiswaFrame.jPanelBeasiswaCost.TabConstraints.tabTitle"), jPanelBeasiswaCost); // NOI18N

        jButtonSaveAll.setText(org.openide.util.NbBundle.getMessage(InputBeasiswaFrame.class, "InputBeasiswaFrame.jButtonSaveAll.text")); // NOI18N
        jButtonSaveAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveAllActionPerformed(evt);
            }
        });

        jButtonCancel.setText(org.openide.util.NbBundle.getMessage(InputBeasiswaFrame.class, "InputBeasiswaFrame.jButtonCancel.text")); // NOI18N
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelButtonLayout = new javax.swing.GroupLayout(jPanelButton);
        jPanelButton.setLayout(jPanelButtonLayout);
        jPanelButtonLayout.setHorizontalGroup(
            jPanelButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelButtonLayout.createSequentialGroup()
                .addComponent(jButtonSaveAll)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonCancel)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanelButtonLayout.setVerticalGroup(
            jPanelButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelButtonLayout.createSequentialGroup()
                .addGroup(jPanelButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSaveAll)
                    .addComponent(jButtonCancel))
                .addGap(0, 21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelMainLayout = new javax.swing.GroupLayout(jPanelMain);
        jPanelMain.setLayout(jPanelMainLayout);
        jPanelMainLayout.setHorizontalGroup(
            jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(jPanelProfil1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelMainLayout.setVerticalGroup(
            jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMainLayout.createSequentialGroup()
                .addComponent(jPanelProfil1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 381, Short.MAX_VALUE)
                .addGap(3, 3, 3)
                .addComponent(jPanelButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanelMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelMain, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setContentPane(validationPanel);
        validationPanel.setInnerComponent(jPanelMain);
        Validator<String> d = StringValidators.trimString(ValidatorUtils.merge(
            StringValidators.REQUIRE_NON_EMPTY_STRING,
            StringValidators.REQUIRE_VALID_NUMBER,
            StringValidators.REQUIRE_NON_NEGATIVE_NUMBER));
    //validationPanel.getValidationGroup().add(jTextFieldIPSPAmount, d);
    jButtonSaveAll.setEnabled(false);

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNama1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNama1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNama1ActionPerformed

    private void jButtonSaveAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveAllActionPerformed
        try {
            // TODO add your handling code here:
            saveInsertIuran();
            JOptionPane.showMessageDialog(rootPane, "Input Beasiswa Berhasil");
            this.dispose();
        } catch (SQLException ex) {
            Exceptions.printStackTrace(ex);
            JOptionPane.showMessageDialog(rootPane, "Input Beasiswa Gagal!\r\n".concat(ex.toString()));
        } catch (KasirException ex) {
            Exceptions.printStackTrace(ex);
            JOptionPane.showMessageDialog(rootPane, "Input Beasiswa Gagal!\r\n".concat(ex.toString()));
        }
    }//GEN-LAST:event_jButtonSaveAllActionPerformed

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButtonCancelActionPerformed

    private void jTabbedPane1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jTabbedPane1PropertyChange
        // TODO add your handling code here:

   }//GEN-LAST:event_jTabbedPane1PropertyChange

    private void jTextFieldIDDTransactionNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldIDDTransactionNameKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIDDTransactionNameKeyTyped

    private void jTextFieldIDDTransactionNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldIDDTransactionNameKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIDDTransactionNameKeyReleased

    private void jTextFieldIDDTransactionNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIDDTransactionNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIDDTransactionNameActionPerformed

    private void jTextFieldIDDAmountKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldIDDAmountKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIDDAmountKeyTyped

    private void jTextFieldIDDAmountKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldIDDAmountKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIDDAmountKeyReleased

    private void jTextFieldIDDAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIDDAmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIDDAmountActionPerformed

    private void jTextFieldBeasiswaAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldBeasiswaAmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldBeasiswaAmountActionPerformed

    private void jTextFieldBeasiswaAmountKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldBeasiswaAmountKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldBeasiswaAmountKeyReleased

    private void jTextFieldBeasiswaAmountKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldBeasiswaAmountKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldBeasiswaAmountKeyTyped

    private void jTextFieldBeasiswaTransactionNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldBeasiswaTransactionNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldBeasiswaTransactionNameActionPerformed

    private void jTextFieldBeasiswaTransactionNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldBeasiswaTransactionNameKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldBeasiswaTransactionNameKeyReleased

    private void jTextFieldBeasiswaTransactionNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldBeasiswaTransactionNameKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldBeasiswaTransactionNameKeyTyped

    private void jTextFieldBeasiswaCostAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldBeasiswaCostAmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldBeasiswaCostAmountActionPerformed

    private void jTextFieldBeasiswaCostAmountKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldBeasiswaCostAmountKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldBeasiswaCostAmountKeyReleased

    private void jTextFieldBeasiswaCostAmountKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldBeasiswaCostAmountKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldBeasiswaCostAmountKeyTyped

    private void jTextFieldBeasiswaCostTransactionNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldBeasiswaCostTransactionNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldBeasiswaCostTransactionNameActionPerformed

    private void jTextFieldBeasiswaCostTransactionNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldBeasiswaCostTransactionNameKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldBeasiswaCostTransactionNameKeyReleased

    private void jTextFieldBeasiswaCostTransactionNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldBeasiswaCostTransactionNameKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldBeasiswaCostTransactionNameKeyTyped

    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InputBeasiswaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InputBeasiswaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InputBeasiswaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InputBeasiswaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new InputBeasiswaFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonSaveAll;
    private javax.swing.JComboBox jComboBoxBeasiswaLevel2;
    private javax.swing.JComboBox jComboBoxBeasiswaLevel3;
    private javax.swing.JComboBox jComboBoxBeasiswaYayasanLevel2;
    private javax.swing.JComboBox jComboBoxBeasiswaYayasanLevel3;
    private javax.swing.JComboBox jComboBoxIBeasiswaLevel1;
    private javax.swing.JComboBox jComboBoxIBeasiswaYayasanLevel1;
    private javax.swing.JComboBox jComboBoxIDDLevel2;
    private javax.swing.JComboBox jComboBoxIDDLevel3;
    private javax.swing.JComboBox jComboBoxIIDDLevel;
    private javax.swing.JLabel jLabelAmount10;
    private javax.swing.JLabel jLabelAmount3;
    private javax.swing.JLabel jLabelAmount4;
    private javax.swing.JLabel jLabelAmount7;
    private javax.swing.JLabel jLabelAmount8;
    private javax.swing.JLabel jLabelAmount9;
    private javax.swing.JLabel jLabelIDDChargedLevel;
    private javax.swing.JLabel jLabelIDDChargedLevel1;
    private javax.swing.JLabel jLabelIDDChargedLevel2;
    private javax.swing.JLabel jLabelIDDChargedLevel2Level;
    private javax.swing.JLabel jLabelIDDChargedLevel2Level1;
    private javax.swing.JLabel jLabelIDDChargedLevel2Level2;
    private javax.swing.JLabel jLabelIDDTitle;
    private javax.swing.JLabel jLabelIDDTitle1;
    private javax.swing.JLabel jLabelIDDTitle2;
    private javax.swing.JLabel jLabelLevel2;
    private javax.swing.JLabel jLabelLevel2Level4;
    private javax.swing.JLabel jLabelNama1;
    private javax.swing.JLabel jLabelNoInduk1;
    private javax.swing.JLabel jLabelNote2;
    private javax.swing.JLabel jLabelNote4;
    private javax.swing.JLabel jLabelNote5;
    private javax.swing.JLabel jLableProfilTitle1;
    private javax.swing.JPanel jPanelBeasiswa;
    private javax.swing.JPanel jPanelBeasiswaCost;
    private javax.swing.JPanel jPanelButton;
    private javax.swing.JPanel jPanelIDD;
    private javax.swing.JPanel jPanelMain;
    private javax.swing.JPanel jPanelProfil1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTableIDD;
    private javax.swing.JTable jTableIDD1;
    private javax.swing.JTable jTableIDD2;
    private javax.swing.JTextArea jTextAreaBeasiswaCostNote;
    private javax.swing.JTextArea jTextAreaBeasiswaNote;
    private javax.swing.JTextArea jTextAreaIDDNote;
    private javax.swing.JTextField jTextFieldBeasiswaAmount;
    private javax.swing.JTextField jTextFieldBeasiswaCostAmount;
    private javax.swing.JTextField jTextFieldBeasiswaCostTransactionName;
    private javax.swing.JTextField jTextFieldBeasiswaTransactionName;
    private javax.swing.JTextField jTextFieldIDDAmount;
    private javax.swing.JTextField jTextFieldIDDTransactionName;
    private javax.swing.JTextField jTextFieldLevel2Level4;
    private javax.swing.JTextField jTextFieldNama1;
    private javax.swing.JTextField jTextFieldNomorInduk1;
    // End of variables declaration//GEN-END:variables

    
    private void saveInsertIuran() throws SQLException, KasirException {
        
        //IDD
        if(!jTextFieldIDDAmount.getText().equals("0") &&(!jTextFieldIDDTransactionName.getText().equals("") || jTextFieldIDDTransactionName.getText() != null )){
            IDD idd = new IDD(profil.noInduk, profil.currentLevel, jTextFieldIDDTransactionName.getText(), Float.valueOf(jTextFieldIDDAmount.getText()), jTextAreaIDDNote.getText());
            checkIDDRecordsThenInsertOrUpdate(idd);
        }
        
        //Beasiswa
        if(!jTextFieldBeasiswaAmount.getText().equals("0") &&(!jTextFieldBeasiswaTransactionName.getText().equals("") || jTextFieldBeasiswaTransactionName.getText() != null )){
            Beasiswa idd = new Beasiswa(profil.noInduk, profil.currentLevel, jTextFieldBeasiswaTransactionName.getText(), Float.valueOf(jTextFieldBeasiswaAmount.getText()), jTextAreaBeasiswaNote.getText());
            checkBeasiswaRecordsThenInsertOrUpdate(idd);
        }
        
        //BeasiswaCost
        if(!jTextFieldBeasiswaCostAmount.getText().equals("0") &&(!jTextFieldBeasiswaCostTransactionName.getText().equals("") || jTextFieldBeasiswaCostTransactionName.getText() != null )){
            BeasiswaCost idd = new BeasiswaCost(profil.noInduk, profil.currentLevel, jTextFieldBeasiswaCostTransactionName.getText(), Float.valueOf(jTextFieldBeasiswaCostAmount.getText()), jTextAreaBeasiswaCostNote.getText());
            checkBeasiswaCostRecordsThenInsertOrUpdate(idd);
        }
    }
    
    private boolean validatePanel(){
        return !validationPanel.isFatalProblem();
    }

   
    private TableModel buildIDDTableModel(Profil profil) throws SQLException, KasirException{
       String columnNames[] = {"Transaksi IDD", "Biaya", "Catatan", "Check Box"};
       Set<IDD> iddFilters = new HashSet<>();
       iddFilters.add(new IDD(profil.noInduk,null, null, 0F, null));
       Map<Long,IDD> searchResultMap = new HashMap<>();
       searchResultMap = Control.exactFilterSelectIurans(Iuran.Tipe.IDD, iddFilters);
       Object[][] data = new Object[searchResultMap.size()][5];
       
       int i = 0;
       iddS = new ArrayList<>();       
       if(searchResultMap.size() > 0){
        for(Map.Entry<Long, IDD> entry: searchResultMap.entrySet()){
            data[i][0]= entry.getValue().transactName;
            data[i][1]= entry.getValue().amount;
            data[i][2]= entry.getValue().note;
            if(entry.getValue().transactDetailIDs.size()>0){
                data[i][3] = new Boolean(true);
            }else{
                data[i][3] = new Boolean(false);
            }
            //if(jTableIDD != null){data[i][3]= jTableIDD.getValueAt(i,3);}else{data[i][3]= new Boolean(false);}
            iddS.add(entry.getValue());
            i++;
        }
       }
       if(data.length >0){
       TableModel tm = new DefaultTableModel(data, columnNames){
           @Override
            public boolean isCellEditable(int row, int column) {
                //all cells false for editable
               return false;
            }
            public Class getColumnClass(int c) {
                return getValueAt(0, c).getClass();
            }
       };
       
       return tm;
       }else{
           TableModel tm = new DefaultTableModel(columnNames, 4);
           return tm;
       }
   }
    
    private TableModel buildBeasiswaTableModel(Profil profil) throws SQLException, KasirException{
       String columnNames[] = {"Transaksi Beasiswa", "Biaya", "Catatan", "Check Box"};
       Set<Beasiswa> beasiswaFilters = new HashSet<>();
       beasiswaFilters.add(new Beasiswa(profil.noInduk,null, null, 0F, null));
       Map<Long,Beasiswa> searchResultMap = new HashMap<>();
       searchResultMap = Control.exactFilterSelectIurans(Iuran.Tipe.Beasiswa, beasiswaFilters);
       Object[][] data = new Object[searchResultMap.size()][5];
       
       int i = 0;
       beasiswaS = new ArrayList<>();       
       if(searchResultMap.size() > 0){
        for(Map.Entry<Long, Beasiswa> entry: searchResultMap.entrySet()){
            data[i][0]= entry.getValue().transactName;
            data[i][1]= entry.getValue().amount;
            data[i][2]= entry.getValue().note;
            if(entry.getValue().transactDetailIDs.size()>0){
                data[i][3] = new Boolean(true);
            }else{
                data[i][3] = new Boolean(false);
            }
            //if(jTableBeasiswa != null){data[i][3]= jTableBeasiswa.getValueAt(i,3);}else{data[i][3]= new Boolean(false);}
            beasiswaS.add(entry.getValue());
            i++;
        }
       }
       if(data.length >0){
       TableModel tm = new DefaultTableModel(data, columnNames){
           @Override
            public boolean isCellEditable(int row, int column) {
                //all cells false for editable
               return false;
            }
            public Class getColumnClass(int c) {
                return getValueAt(0, c).getClass();
            }
       };
       
       return tm;
       }else{
           TableModel tm = new DefaultTableModel(columnNames, 4);
           return tm;
       }
   }
    
    private TableModel buildBeasiswaCostTableModel(Profil profil) throws SQLException, KasirException{
       String columnNames[] = {"Transaksi BeasiswaCost", "Biaya", "Catatan", "Check Box"};
       Set<BeasiswaCost> beasiswacostFilters = new HashSet<>();
       beasiswacostFilters.add(new BeasiswaCost(profil.noInduk,null, null, 0F, null));
       Map<Long,BeasiswaCost> searchResultMap = new HashMap<>();
       searchResultMap = Control.exactFilterSelectIurans(Iuran.Tipe.BeasiswaCost, beasiswacostFilters);
       Object[][] data = new Object[searchResultMap.size()][5];
       
       int i = 0;
       beasiswaCostS = new ArrayList<>();       
       if(searchResultMap.size() > 0){
        for(Map.Entry<Long, BeasiswaCost> entry: searchResultMap.entrySet()){
            data[i][0]= entry.getValue().transactName;
            data[i][1]= entry.getValue().amount;
            data[i][2]= entry.getValue().note;
            if(entry.getValue().transactDetailIDs.size()>0){
                data[i][3] = new Boolean(true);
            }else{
                data[i][3] = new Boolean(false);
            }
            //if(jTableBeasiswaCost != null){data[i][3]= jTableBeasiswaCost.getValueAt(i,3);}else{data[i][3]= new Boolean(false);}
            beasiswaCostS.add(entry.getValue());
            i++;
        }
       }
       if(data.length >0){
       TableModel tm = new DefaultTableModel(data, columnNames){
           @Override
            public boolean isCellEditable(int row, int column) {
                //all cells false for editable
               return false;
            }
            public Class getColumnClass(int c) {
                return getValueAt(0, c).getClass();
            }
       };
       
       return tm;
       }else{
           TableModel tm = new DefaultTableModel(columnNames, 4);
           return tm;
       }
   }

    private void checkIDDRecordsThenInsertOrUpdate(IDD idd) throws SQLException{
        try {
            //Only UPDATE Amount and NOte for IDD
            Set<IDD> filterIDD = new HashSet<>();
            IDD temp = new IDD(idd.noInduk, idd.chargedLevel, null, 0.0f, null);
            
            filterIDD.add(temp);
            Map<Long,IDD> map = new HashMap<>();
            map = Control.filterSelectIurans(Iuran.Tipe.IDD, filterIDD);
             for(IDD tempIDD : map.values()){
                if(tempIDD.noInduk.equals(idd.noInduk) && (tempIDD.chargedLevel.tahun ==idd.chargedLevel.tahun))
                { 
                    idd.id = tempIDD.id;
                    idd.note = tempIDD.note.concat(" Biaya IDD Sebelumnya:").concat(String.valueOf(tempIDD.amount));
                    idd.amount = tempIDD.amount + Float.valueOf(jTextFieldIDDAmount.getText());
                    idd.note = jTextAreaIDDNote.getText().concat("<--").concat(idd.note);
                }
             }
             
             
            Control.updateIuran(Iuran.Tipe.IDD, idd);
        } catch (KasirException ex) {
            Exceptions.printStackTrace(ex);
            //INSERT New Amount and NOte for IDD
            if(ex.tipe.ROW_NOT_FOUND.equals(KasirException.Tipe.ROW_NOT_FOUND)){
                try {
                    idd.amount = Float.valueOf(jTextFieldIDDAmount.getText());
                    idd.note = jTextAreaIDDNote.getText();
                    Control.insertIuran(Iuran.Tipe.IDD, idd);
                } catch (KasirException ex1) {
                    Exceptions.printStackTrace(ex1);
                }
            }
        }
    }
    
    private void checkBeasiswaRecordsThenInsertOrUpdate(Beasiswa beasiswa) throws SQLException{
        try {
            //Only UPDATE Amount and NOte for Beasiswa
            Set<Beasiswa> filterBeasiswa = new HashSet<>();
            Beasiswa temp = new Beasiswa(beasiswa.noInduk, beasiswa.chargedLevel, null, 0.0f, null);
            
            filterBeasiswa.add(temp);
            Map<Long,Beasiswa> map = new HashMap<>();
            map = Control.filterSelectIurans(Iuran.Tipe.Beasiswa, filterBeasiswa);
             for(Beasiswa tempBeasiswa : map.values()){
                if(tempBeasiswa.noInduk.equals(beasiswa.noInduk) && (tempBeasiswa.chargedLevel.tahun ==beasiswa.chargedLevel.tahun))
                { 
                    beasiswa.id = tempBeasiswa.id;
                    beasiswa.note = tempBeasiswa.note.concat(" Biaya Beasiswa Sebelumnya:").concat(String.valueOf(tempBeasiswa.amount));
                    beasiswa.amount = tempBeasiswa.amount + Float.valueOf(jTextFieldBeasiswaAmount.getText());
                    beasiswa.note = jTextAreaBeasiswaNote.getText().concat("<--").concat(beasiswa.note);
                }
             }
             
             
            Control.updateIuran(Iuran.Tipe.Beasiswa, beasiswa);
        } catch (KasirException ex) {
            Exceptions.printStackTrace(ex);
            //INSERT New Amount and NOte for Beasiswa
            if(ex.tipe.ROW_NOT_FOUND.equals(KasirException.Tipe.ROW_NOT_FOUND)){
                try {
                    beasiswa.amount = Float.valueOf(jTextFieldBeasiswaAmount.getText());
                    beasiswa.note = jTextAreaBeasiswaNote.getText();
                    Control.insertIuran(Iuran.Tipe.Beasiswa, beasiswa);
                } catch (KasirException ex1) {
                    Exceptions.printStackTrace(ex1);
                }
            }
        }
    }
    
    private void checkBeasiswaCostRecordsThenInsertOrUpdate(BeasiswaCost beasiswacost) throws SQLException{
        try {
            //Only UPDATE Amount and NOte for BeasiswaCost
            Set<BeasiswaCost> filterBeasiswaCost = new HashSet<>();
            BeasiswaCost temp = new BeasiswaCost(beasiswacost.noInduk, beasiswacost.chargedLevel, null, 0.0f, null);
            
            filterBeasiswaCost.add(temp);
            Map<Long,BeasiswaCost> map = new HashMap<>();
            map = Control.filterSelectIurans(Iuran.Tipe.BeasiswaCost, filterBeasiswaCost);
             for(BeasiswaCost tempBeasiswaCost : map.values()){
                if(tempBeasiswaCost.noInduk.equals(beasiswacost.noInduk) && (tempBeasiswaCost.chargedLevel.tahun ==beasiswacost.chargedLevel.tahun))
                { 
                    beasiswacost.id = tempBeasiswaCost.id;
                    beasiswacost.note = tempBeasiswaCost.note.concat(" Biaya BeasiswaCost Sebelumnya:").concat(String.valueOf(tempBeasiswaCost.amount));
                    beasiswacost.amount = tempBeasiswaCost.amount + Float.valueOf(jTextFieldBeasiswaCostAmount.getText());
                    beasiswacost.note = jTextAreaBeasiswaCostNote.getText().concat("<--").concat(beasiswacost.note);
                }
             }
             
             
            Control.updateIuran(Iuran.Tipe.BeasiswaCost, beasiswacost);
        } catch (KasirException ex) {
            Exceptions.printStackTrace(ex);
            //INSERT New Amount and NOte for BeasiswaCost
            if(ex.tipe.ROW_NOT_FOUND.equals(KasirException.Tipe.ROW_NOT_FOUND)){
                try {
                    beasiswacost.amount = Float.valueOf(jTextFieldBeasiswaCostAmount.getText());
                    beasiswacost.note = jTextAreaBeasiswaCostNote.getText();
                    Control.insertIuran(Iuran.Tipe.BeasiswaCost, beasiswacost);
                } catch (KasirException ex1) {
                    Exceptions.printStackTrace(ex1);
                }
            }
        }
    }
}
